### PR TITLE
[grafana] Fix LOG_LEVEL in the sidecar container.

### PR DESCRIPTION
**Pull request by siavashs**
Fix the helm template value.
This bug was introduced in #1624 resulting in the following error:
```
Traceback (most recent call last):
  File "/app/sidecar.py", line 11, in <module>
    from helpers import REQ_RETRY_TOTAL, REQ_RETRY_CONNECT, REQ_RETRY_READ, REQ_RETRY_BACKOFF_FACTOR
  File "/app/helpers.py", line 8, in <module>
    from logger import get_logger
  File "/app/logger.py", line 69, in <module>
    root_logger.setLevel(level.upper() if isinstance(level, str) else level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: ''
```

Signed-off-by: Siavash Safi <git@hosted.run>

### CODE REVIEW

**Comment by ldaugusto** [comment]
Nice, I just notice this and had to put the 'logLevel' inside 'dashboards' as a workaround, so I came to check if there was a fix on the way.

**Comment by zanhsieh** [comment]
close in favour of https://github.com/grafana/helm-charts/pull/1624

**Comment by siavashs** [comment]
@zanhsieh I think you did not pay attention to the PR description.
This PR fixes the bug introduce by #1624 
You should not close it in favour of that :slightly_smiling_face:

**Comment by zanhsieh** [comment]
@siavashs 
Could you check file changes comparing with the main branch? I only see the Chart.yaml version increasing.

**Comment by siavashs** [comment]
It was fixed in https://github.com/grafana/helm-charts/pull/1628
You merged it yourself.
I'm closing this one.

**Pull request closed without merging**
