### PR TITLE
[enterprise-logs] Initial version of the GEL Helm chart

### PR DESCRIPTION
**Pull request by chaudum**
This is the initial version of the Grafana Enterprise Logs (GEL) Helm chart.
It is based on `loki-distributed` and extends it with additional services, configuration and license.

### CODE REVIEW

**Comment by chaudum** [comment]
CI fails with error `failed to sync secret cache: timed out waiting for the condition`. Not sure how to fix this.

```
2021-08-31T12:17:33.1993982Z 10m         Warning   FailedMount             pod/enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw                                             kubelet, chart-testing-control-plane                                                                 MountVolume.SetUp failed for volume "config" : failed to sync secret cache: timed out waiting for the condition                              10m          2       enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw.16a062c23b5d8b63
2021-08-31T12:17:33.2002130Z 10m         Warning   FailedMount             pod/enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw                                             kubelet, chart-testing-control-plane                                                                 MountVolume.SetUp failed for volume "license" : failed to sync secret cache: timed out waiting for the condition                             10m          2       enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw.16a062c23bc08f42
2021-08-31T12:17:33.2008755Z 10m         Warning   FailedMount             pod/enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw                                             kubelet, chart-testing-control-plane                                                                 MountVolume.SetUp failed for volume "kube-api-access-26vhp" : failed to sync configmap cache: timed out waiting for the condition            10m          1       enterprise-logs-0cmqd3h1ll-admin-api-96b7984b4-kz4mw.16a062c2934f77c3
```

**Review by jdbaldry — COMMENTED** [review]
I think the Kubernetes Event is a red herring here. It was a transient error as the Pod containers were later able to start which requires that all volume mounts are present.

Instead, I believe that CI is failing because GEL includes an additional check not present in GEM that will crash the admin-api on startup if there has not been successful bootstrapping of a cluster object.

I think that is likely that the GEL behavior is preferred as it provides faster feedback to the user in the case of a misconfigured cluster. However, that does mean we are going to need to solve the problem of providing a valid license in order for the admin-api to start and the chart to finish installing successfully.

**Comment by chaudum** [comment]
> I think the Kubernetes Event is a red herring here. It was a transient error as the Pod containers were later able to start which requires that all volume mounts are present.
> 
> Instead, I believe that CI is failing because GEL includes an additional check not present in GEM that will crash the admin-api on startup if there has not been successful bootstrapping of a cluster object.
> 
> I think that is likely that the GEL behavior is preferred as it provides faster feedback to the user in the case of a misconfigured cluster. However, that does mean we are going to need to solve the problem of providing a valid license in order for the admin-api to start and the chart to finish installing successfully.

Right, I just tested locally using `ct` and the admin-api Pod keeps crash-looping:

```
$ k -n enterprise-logs-pa7yxv91qw logs enterprise-logs-pa7yxv91qw-admin-api-66644b9556-xzv6b
level=info ts=2021-09-01T12:21:24.140566383Z caller=main.go:142 msg="Starting Grafana Enterprise Logs"
level=info ts=2021-09-01T12:21:24.140589991Z caller=main.go:143 version=v1.1.0 branch=HEAD Revision=be76ffe2 LokiVersion=v2.1.0-429+c44c12b9304751 LokiRevision=c44c12b9
level=warn ts=2021-09-01T12:21:24.141529922Z caller=manager.go:158 msg="unable to load local license" error="error parsing license token: square/go-jose: compact JWS format must have three parts"
level=warn ts=2021-09-01T12:21:24.143615331Z caller=manager.go:322 msg="unable to load license configured on path" error="error parsing license token: square/go-jose: compact JWS format must have three parts"
level=warn ts=2021-09-01T12:21:24.144066918Z caller=added_modules.go:109 msg="unable to find valid license for Grafana Enterprise Logs" error="unable to source a valid license"
level=info ts=2021-09-01T12:21:24.144194272Z caller=server.go:239 http=[::]:3100 grpc=[::]:9095 msg="server listening on addresses"
level=error ts=2021-09-01T12:21:24.145370621Z caller=log.go:106 msg="error running Grafana Enterprise Logs" err="failed to find cluster enterprise-logs-pa7yxv91qw on startup: unable to get cluster enterprise-logs-pa7yxv91qw from storage: not found\nerror initialising module: admin-api\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).initModule\n\t/src/enterprise-logs/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:105\ngithub.com/cortexproject/cortex/pkg/util/modules.(*Manager).InitModuleServices\n\t/src/enterprise-logs/vendor/github.com/cortexproject/cortex/pkg/util/modules/modules.go:75\ngithub.com/grafana/loki/pkg/loki.(*Loki).Run\n\t/src/enterprise-logs/vendor/github.com/grafana/loki/pkg/loki/loki.go:241\ngithub.com/grafana/loki-enterprise/pkg/enterprise/loki/init.(*LokiEnterprise).Run\n\t/src/enterprise-logs/pkg/enterprise/loki/init/loki.go:213\nmain.main\n\t/src/enterprise-logs/cmd/enterprise-logs/main.go:145\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"
```

**Comment by chaudum** [comment]
@unguiculus Since you're one of the maintainers of this repository, is there a way to exclude this chart from the `lint-test` check? The problem is that GEL requires a valid license to start and I could not find a good way how to provide one for testing. Maybe you have an idea?

**Review by jdbaldry — APPROVED** [review]
LGTM, thank you for all of your work on this!

**Comment by jdbaldry** [comment]
@unguiculus

We have had to temporarily exclude these charts from the chart-testing CI that performs a `helm install`. We really value the tooling but need to defer finding a solution to the problem of including secret material specifically for this chart and the enterprise-metrics chart.

**Comment by chaudum** [comment]
@techgnosis found another issue with the Helm chart. The frontend worker is not configured correctly (missing the frontend URL).

**Review by jdbaldry — DISMISSED** [review]
LGTM, thanks!

**Review by jdbaldry — APPROVED** [review]
Think we are good for an initial release, installs smoothly for me!

**Pull request merged**
