### PR TITLE
[grafana] fixed url link for persistent volume claim in values.yaml

### PR DESCRIPTION
**Pull request by usmangt**
The old link was using http and was not working. So updated it to https and now it works
Signed-off-by: Usman Ahmad <syed_usman_ahmed@hotmail.com>

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@usmangt 
Thanks for the contribution. Can you bump the version to latest in Chart.yaml and sign DCO please?

**Comment by usmangt** [comment]
Hi @zanhsieh ,

Can you please provide me the step-by-step instructions as how to sign the DCO?

Also, about bumping the chart version, should I download a new chart on my test-machine?

Apologies, as I am a bit new to these things.

**Comment by zanhsieh** [comment]
> Can you please provide me the step-by-step instructions as how to sign the DCO?
Instruction in below next to DCO (click Details). I put the link here:

https://github.com/grafana/helm-charts/pull/2881/checks?check_run_id=20208007426

> Also, about bumping the chart version, should I download a new chart on my test-machine?
You just need to change the chart version in Chart.yaml. Downloading a new chart is not needed.
https://github.com/grafana/helm-charts/blob/903fff0cdee698f647432c4f8b3f5bc99665db83/charts/grafana/Chart.yaml#L3

**Comment by usmangt** [comment]
Signed-off-by: Usman Ahmad <syed_usman_ahmed@hotmail.com>

**Comment by zanhsieh** [comment]
@usmangt The DCO signoff happens during you commit your change, not putting in the PR comment.

**Comment by jkroepke** [comment]
Hi, please do the following steps on you machine

```
git rebase HEAD~10 --signoff
git push --force-with-lease origin usmangt-patch-1
```

**Review by zanhsieh — APPROVED** [review]

**Review by jkroepke — APPROVED** [review]

**Pull request merged**
