### PR TITLE
[loki-distributed] Corrected date format

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Enclosed the date within double quotes as asked in the issue #2463

### CODE REVIEW

**Review by verejoel — APPROVED** [review]
LGTM

**Comment by Sheikh-Abubaker** [comment]
> LGTM

Hi @verejoel thanks for approving this PR, just wanted to know when is this PR going to be merged, I'm not in any sort of hurry but this is my 1st time participating in Hacktoberfest and I got 2 more PRs left to be merged to achieve 4/4 PR merged criteria in Hacktoberfest.

**Comment by verejoel** [comment]
@Sheikh-Abubaker sadly I am not an official maintainer. @zanhsieh can hopefully help out with the merge!

**Comment by Sheikh-Abubaker** [comment]
I have also updated this branch with main branch my latest [commit 3ee5555e3cb7432fb054332c2c3815b6c5b87c3b](https://github.com/grafana/helm-charts/pull/2731/commits/3ee5555e3cb7432fb054332c2c3815b6c5b87c3b)

**Comment by Sheikh-Abubaker** [comment]
Hi @zanhsieh can you please look into this PR if this is upto to the mark, I'm not in any sort of hurry but have participated in Hacktoberfest and it's almost end of Hacktoberfest2023 and I've still got 2 more PRs to be merged in order to reach 4/4 PRs merged criteria, so just wanted to know.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
