### PR TITLE
[grafana] Adding configmap annotation

### PR DESCRIPTION
**Pull request by jmiszczak83**
fixes https://github.com/grafana/helm-charts/issues/1811

Adding configmap annotation with example in values file how to use it with ArgoCD in case configmap is too big.

### CODE REVIEW

**Comment by maciej-zadora** [comment]
Hi @maorfr @torstenwalter @Xtigyro @zanhsieh can maybe any of you review the PR. It would be nice to have this fix merged.

**Comment by maciej-zadora** [comment]
@zanhsieh thank you for the approval. now we just need another one.

**Comment by lenastandke** [comment]
Hi, guys, there is a +1 for this merge. @torstenwalter , @Xtigyro , @maorfr , could someone make a PR, please? Thanks in advance!

**Comment by lenastandke** [comment]
HI @torstenwalter, @Xtigyro, @maorfr, is there any update? Could you please make a PR? Please comment if anything is missing to make a PR from your side. Thanks!

**Comment by maciej-zadora** [comment]
Hi @maorfr, @torstenwalter and @Xtigyro I am again asking for your support and review of this PR.

**Comment by maciej-zadora** [comment]
Hi guys @maorfr, @torstenwalter and @Xtigyro any updates with this PR?

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@jmiszczak83 Please resolve the conflicts.

**Pull request merged**
