### PR TITLE
[grafana] Use default auth type for CloudWatch  because it's working with token

### PR DESCRIPTION
**Pull request by zifter**

### CODE REVIEW

**Comment by zanhsieh** [comment]
@zifter 
Could you bump. the chart version to latest please?

**Comment by zanhsieh** [comment]
@zifter 
Not merge remote branch. Please change version in charts/grafana/Charts.yaml .

**Comment by AmitBaranes** [comment]
any update?

**Comment by zanhsieh** [comment]
@AmitBaranes 
Please contact @zifter . I cannot merge without his modification.

**Comment by zifter** [comment]
Chart version is bumped.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
