### PR TITLE
[promtail] fix ingress deployment

### PR DESCRIPTION
**Pull request by vquie**
I just discovered that we can now deploy an ingress and ran right into this issue that @rasta-rocket must've overseen in c0c9638.

I also created a ci values file that works just fine.

I didn't add it to any actions though.

Update:
This PR edits the ingress section to be configured per `extraPorts`.
Each `extraPort` will have its own ingress with own annotations, ingressclass, you name it.

Checks are working.

### CODE REVIEW

**Review by rasta-rocket — APPROVED** [review]

**Comment by rasta-rocket** [comment]
@zanhsieh do you think that you can review that ?
Sorry about that by the way 🙈

**Comment by vquie** [comment]
I just discovered that this MR does not spawn a service yet. I will add it and push it here.

**Comment by zanhsieh** [comment]
@vquie 
Also please don't forget sign DCO please.

**Comment by vquie** [comment]
Had to no some more changes.

With this PR the ingress will be configured in the `extraPorts` section. You can add an ingress per `extraPort`. You can add multiple hosts per ingress. It will reuse the port configured.

I also added an ingress to the previous ci check and remove my own check for it.

Since the previous release was not working I would't consider this a breaking change. Otherwise I would.

Please check and ask if there are any questions.

**Comment by vquie** [comment]
fixed both issues from the tests, the readme and the error in the ingress.yaml that could occur if `extraPorts` key is upper case.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
