### PR TITLE
[tempo-distributed] Added support for OTLP gRPC ingest on gateway.

### PR DESCRIPTION
**Pull request by dipu018**
**Background:** The gateway deployed by tempo-distributed helm chart did not support ingest over gRPC for OTLP.
**Changes:**

- added additionalPorts to gateway deployment so that port 4317 can be exposed if needed.
- added gRPC on 4317 in nginx config to route to distributor endpoint.

**Use:**
```yaml
gateway:
  additionalPorts: 
    - name: otlp-grpc
      port: 4317
      protocol: TCP
  service:
    additionalPorts: 
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
        protocol: TCP
```

### CODE REVIEW

**Comment by dipu018** [comment]
Fixes issue [#1389](https://github.com/grafana/helm-charts/issues/1389)

**Comment by dipu018** [comment]
Tested with [Telemetrygen v0.104.0](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/cmd/telemetrygen/v0.104.0/cmd/telemetrygen).

**Review by pratik-iiss — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@dipu018 could you please resolve the conflicts ? Thanks!!

**Review by zanhsieh — CHANGES_REQUESTED** [review]
Please remove under charts/grafana/README.md commit. Multiple charts in one PR won't pass CI.

**Comment by dipu018** [comment]
New PR https://github.com/grafana/helm-charts/pull/3261 raised with necessary changes.

**Comment by dipu018** [comment]
Closing this as new PR https://github.com/grafana/helm-charts/pull/3261 raised with necessary changes.

**Pull request closed without merging**
