### PR TITLE
[loki-distributed] feat: new var gateway.nginxConfig.resolver

### PR DESCRIPTION
**Pull request by joemiller**
Signed-off-by: joe miller <joeym@joeym.net>

Add a new variable `gateway.nginxConfig.resolver` to the gateway component of the loki-distributed chart.

This allows overriding the DNS resolver used by nginx. This is necessary to work around issues with UDP services that occur when kube-dns pods are restarted. More details: https://github.com/grafana/helm-charts/issues/1058

This setting, along with the `extraContainers` feature introduced in https://github.com/grafana/helm-charts/pull/1133, provides a path for working around issues with nginx's DNS resolution that occur when the kube-dns pods are restarted in certain clusters (any cluster using conntrack for keeping state on UDP flows, typically)

With these features a workaround can be deployed with the following gateway config:

```yaml
loki-distributed:
  gateway:

    extraContainers:
      - name: dnsmasq
        image: "janeczku/go-dnsmasq:release-1.0.7"
        imagePullPolicy: IfNotPresent
        args:
          - --listen
          - "127.0.0.1:8053"
          - --hostsfile=/etc/hosts
          - --enable-search
          - --verbose

    nginxConfig:
      resolver: "127.0.0.1:8053"
```

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
never run into this myself so I can't test it, but seems reasonable to me. LGTM!

**Comment by joemiller** [comment]
great. let's merge it? =)

**Comment by joemiller** [comment]
> [CLA assistant check](https://cla-assistant.io/grafana/helm-charts?pullRequest=1272) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1272) before we can accept your contribution.**0** out of **2** committers have signed the CLA.❌ joemiller❌ zanhsiehYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1272) it.

The CLA page seems broken. I just get this. I can't input anything, there's no selection/dropdown in the box here:

image

**Comment by zanhsieh** [comment]
@joemiller 
It seems CLA fixed. Click Details next to "license/cla" on the bottom of this PR to sign it.

**Pull request merged**
