### PR TITLE
[grafana] docs: Add example of datasource secret to README

### PR DESCRIPTION
**Pull request by matfiz**
I've added an example of k8 secret to make it easier for new users to complete the datasource configuration.

### CODE REVIEW

**Comment by pankdhnd** [comment]
This PR needs immediate merge. The example of datasource secret provided in the PR works like charm. I had been looking for the example quite some time and tried several combinations but nothing worked out. But this one, it just works. Thanks a lot @matfiz

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@matfiz 
Thanks for the contribution. Would you mind to bump the version in Chart.yaml to latest
and sign DCO so CI could get this merge ASAP?

**Comment by matfiz** [comment]
@zanhsieh Thanks, I've bumped the chart and grafana versions to the ones from main and signed the CLA.

**Comment by matfiz** [comment]
@zanhsieh I see the lint-test has failed on the version check. Shall I bump the version to 6.52.9 (as the current is 6.52.8)?

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
