### PR TITLE
[tempo-distributed] Add metrics max duration config

### PR DESCRIPTION
**Pull request by bvillanueva-mdsol**
Background:
We wanted to expand current metrics generator's config metrics.max_duration from default `3h` to something bigger.

Goal:
Allow update on metrics generator's config metrics.max_duration configuration. 

Doc: metrics.max_duration is found in this documentation: https://grafana.com/docs/tempo/latest/configuration/#query-frontend

### CODE REVIEW

**Comment by abenbachir** [comment]
When this config can be merged ?

**Comment by bvillanueva-mdsol** [comment]
Thanks for the ping @abenbachir. The PR was not updated to latest main. Just updated now. We can now able to merge 🙇

**Comment by abenbachir** [comment]
@Sheikh-Abubaker this PR needs to be reviewed.

**Comment by bvillanueva-mdsol** [comment]
Looks like as a workaround I saw this post in community slack channel: https://grafana.slack.com/archives/C01D981PEE5/p1728294653138369?thread_ts=1728293373.828449&cid=C01D981PEE5 
```
        tempo:
          structuredConfig:
            query_frontend:
              metrics:
                max_duration: 12h      
```
it works on my local too.

@abenbachir , looks like we dont need this PR anymore. What do you think?

**Comment by abenbachir** [comment]
> Looks like as a workaround I saw this post in community slack channel: https://grafana.slack.com/archives/C01D981PEE5/p1728294653138369?thread_ts=1728293373.828449&cid=C01D981PEE5
> 
> ```
>         tempo:
>           structuredConfig:
>             query_frontend:
>               metrics:
>                 max_duration: 12h      
> ```
> 
> it works on my local too.
> 
> @abenbachir , looks like we dont need this PR anymore. What do you think?

yeah i saw that thread as well.

**Comment by Sheikh-Abubaker** [comment]
@bvillanueva-mdsol could you please bump the chart version to 1.19.0

**Comment by bvillanueva-mdsol** [comment]
@Sheikh-Abubaker sorry for the late reply. Got it bumped to 1.20.0 on latest updates

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker sorry for the late reply. Got it bumped to 1.20.0 on latest updates

@bvillanueva-mdsol no worries!

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM!

**Comment by Sheikh-Abubaker** [comment]
@mapno could you please review this ?

**Review by mapno — APPROVED** [review]

**Pull request merged**
