### PR TITLE
[loki-distributed] reverted PR #627 (removed namespace declarations from the Helm Template files)

### LINKED ISSUE #665: [loki-distributed] nil pointer evaluating interface {}.Namespace
Starting version 0.37.0 Loki upgrades fail with the following error:
```
Error: UPGRADE FAILED: template: loki-distributed/templates/ruler/configmap-ruler.yaml:8:24: executing "loki-distributed/templates/ruler/configmap-ruler.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
```

Seems related to adding the namespaces https://github.com/grafana/helm-charts/commit/375a029360fb0aa53d214cdde088ebc287a07e97#diff-3363e3a709c48b693e37b75bdd2884425a850179123e52be7554b7374136d629

### PR DESCRIPTION
**Pull request by sherifkayad**
Reverted PR #627 (removed namespace declarations from the Helm Template files)

Fixes #665

Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>

### CODE REVIEW

**Comment by sherifkayad** [comment]
@Whyeasy sorry to bug you. Can you have a look at this one?

**Comment by Whyeasy** [comment]
@sherifkayad please see https://github.com/grafana/helm-charts/pull/627

**Comment by sherifkayad** [comment]
@Whyeasy so the plan would be reverting the whole PR done by @chrism417? .. happy to do so here in this PR

**Comment by Whyeasy** [comment]
@sherifkayad Yes I would so say. If you have time to do that, that would be great! sorry for the inconvenience.

**Comment by sherifkayad** [comment]
@Whyeasy done. Glad to help .. No worries ;)

**Comment by stevehipwell** [comment]
Thanks @sherifkayad, I was worried about the changes in #627. I'll wait on this before I test your Query Index changes.

**Review by Whyeasy — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
