### PR TITLE
[grafana] Adding jkroepke as maintainer

### PR DESCRIPTION
**Pull request by jkroepke**
I'm offering help as maintainer for the Grafana helm chart.

I contribute a lot to this [repository](https://github.com/grafana/helm-charts/pulls?q=is%3Apr+author%3Ajkroepke) and the [loki](https://github.com/grafana/loki/pulls?q=is%3Apr+author%3Ajkroepke) repository. 

Additionally, I'm kube-prometheus-stack chart maintainers and using the grafana helm chart in production.

In case the helm chart maintainer (@zanhsieh, @rtluckie, @maorfr, @Xtigyro, @torstenwalter) agree, I need a invite for that repository.

### CODE REVIEW

**Review by zalegrala — APPROVED** [review]
I support this.  Several good contributions can be seen here.

https://github.com/grafana/helm-charts/pulls?q=is%3Apr+author%3Ajkroepke+is%3Aclosed

**Comment by zalegrala** [comment]
Thank you for your offer to help support this chart.

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@jkroepke Could you please merge the `main` branch intro yours?

**Comment by jkroepke** [comment]
Done

**Comment by Xtigyro** [comment]
@zanhsieh Could you please also review this PR?

**Review by zanhsieh — APPROVED** [review]

**Comment by jkroepke** [comment]
Thank you all.

**Comment by jkroepke** [comment]
@zanhsieh  @zalegrala @Xtigyro What is the process it get an invite to this repository?

**Comment by Sheikh-Abubaker** [comment]
I've also contributed several times to this repository, If possible I'd also like to step up and help in maintaining helm charts in this repo, what do you think @zanhsieh @jkroepke @zalegrala @Xtigyro ?

**Comment by zalegrala** [comment]
We welcome community support.  Send a PR @Sheikh-Abubaker and let's review.

**Comment by Sheikh-Abubaker** [comment]
@zalegrala checkout PR #3195

**Pull request merged**
