### PR TITLE
[loki-distributed] Enabling Loki Index Gateway

### PR DESCRIPTION
**Pull request by sherifkayad**
As per #611 here's a PR to enable the Index Gateway component (introduced in Loki v2.3)

### CODE REVIEW

**Comment by sherifkayad** [comment]
@stevehipwell will be great if you can give that setup a try and test it ;)

**Comment by sherifkayad** [comment]
@Whyeasy @unguiculus could you please have a look at this PR? .. The `helm-docs` is causing some Linting failures .. probably has to do with the fact that I'm using a non-Linux machine?! I ran the helm-docs docker container and still the same issue .. That was the case in previous PRs with me .. I would appreciate it if you can run the helm-docs commands for me ..

**Comment by stevehipwell** [comment]
@sherifkayad you have some line ending issues that might be causing lint failures.

**Comment by stevehipwell** [comment]
@sherifkayad the changes look good to me, let me give it a try.

**Comment by sherifkayad** [comment]
@stevehipwell feel free to run the helm-docs from your machine .. not sure if that might help. Should I give you access to my personal repo?

**Comment by stevehipwell** [comment]
@sherifkayad the line endings are on some of the yaml files, the PR diff view shows them up with an icon and your editor should be able to fix them.

**Comment by sherifkayad** [comment]
@stevehipwell did you give it a try? how are the results?

**Comment by stevehipwell** [comment]
@sherifkayad I've given it a spin and everything looks correct, but I'd need a released chart to give it a more in depth and longer test.

I'd suggest disabling the index gateway by default for a release before setting it to default in the release after that, assuming there are no issues. I also assume that with the index gateway off the output of `helm template` is identical to the previous version?

**Comment by sherifkayad** [comment]
@stevehipwell yes .. the Output should be identical given that the gateway is off. That's a good idea with releasing a minor version now with the index-gateway off and later release a major one with it being off.

I would also like to get the opinion of the reviewers on this point @Whyeasy @unguiculus what do you think?

**Comment by sherifkayad** [comment]
@Whyeasy any feedback from your side?

**Comment by Whyeasy** [comment]
So I think it's better to have the index gateway off by default. This way it won't bring a long big changes for the people that are not interested in the change. The ones that are interested can simply turn it on.

**Comment by sherifkayad** [comment]
@Whyeasy Thanks for the feedback. Will adjust that accordingly. Do you think it should be a minor release then?

**Comment by Whyeasy** [comment]
It doesn't bring any breaking changes if people upgrade, so minor would be fine.

**Comment by sherifkayad** [comment]
@Whyeasy changes applied. Can you please have a look?

**Comment by Whyeasy** [comment]
@sherifkayad Update the chart version and we are good to go!

**Comment by sherifkayad** [comment]
@Whyeasy just rebased to the latest main. Looking forward to the merge once the build succeeds.

**Comment by sherifkayad** [comment]
@Whyeasy all green ;)

**Review by Whyeasy — APPROVED** [review]
LGTM! Thanks for all the work.

**Comment by sherifkayad** [comment]
@Whyeasy Sure thing! thank you for the quick feedback.

**Pull request merged**
