### PR TITLE
[tempo] Update statefulset.yaml

### PR DESCRIPTION
**Pull request by BenCoughlan15**
fixes indentation for annotations in sts. 

without the "-" it adds 8 spaces, not 4.

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for the fix. You will need to sign the DCO and CLA before we can merge.

**Comment by BitProcessor** [comment]
@BenCoughlan15 Please be so kind to sign the DCO and CLA so we can merge your contribution?

**Comment by BenCoughlan15** [comment]
Hey!

All signed, thanks!

**Comment by BitProcessor** [comment]
Hey @BenCoughlan15 ; the DCO one is still failing: https://github.com/grafana/helm-charts/pull/1669/checks?check_run_id=7893931132

Next to that, you'll also need a chart version bump: 0.16.1 for example

**Review by BitProcessor — CHANGES_REQUESTED** [review]
Chart version needs a bump

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
