### PR TITLE
[loki-distributed] Loki configuration through existing secret

### PR DESCRIPTION
**Pull request by ubergesundheit**
This PR adds a new configuration option to allow users of the loki-distributed helm chart to specify an existing secret containing the loki configuration. This enables the usage of sealed secrets.

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Hello @unguiculus @Whyeasy do you maybe have time in the near future to check this PR? :) Thanks!

**Comment by hkailantzis** [comment]
This looks really useful and would be great if it will get merged! :-)

**Comment by haimari** [comment]
Hello,
Would be very helpful to have this feature. It will allow to deploy Loki with `Flux` as `HelmRelease` + `Sealed-Secrets`
Can you please update what is the status of this MR ?

**Comment by Whyeasy** [comment]
Please update the version, after that I can/will merge it.

**Comment by ubergesundheit** [comment]
> Please update the version, after that I can/will merge it.

Bumped to 0.33.0. Is that alright?

**Review by Whyeasy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
