### PR TITLE
[promtail] update to 3.0.0

### PR DESCRIPTION
**Pull request by mjnagel**
Updates:
- Promtail 3.0.0 (does not appear to be any chart changes needed?)
- Switches configmap-reload to new ghcr location
- Allows for enabling service without servicemonitor

Previously made these changes in https://github.com/grafana/helm-charts/pull/3026/files but with the 3.0.0 release moved them here.

### CODE REVIEW

**Comment by mjnagel** [comment]
@zanhsieh rebased this and fixed linting issues if you are able to take another look!

**Review by zanhsieh — APPROVED** [review]

**Comment by jimmy-ungerman** [comment]
Would love to get this approved to match our Promtail installation to the Loki version

**Review by zalegrala — APPROVED** [review]
Thanks for the contribution.

**Comment by mjnagel** [comment]
@jkroepke I'll fix this shortly, thanks for bringing to my attention.

**Pull request merged**
