### PR TITLE
[promtail] Update _pod.tpl to fix name mismatch for config file between chart and container  that prevents pod to launch in k8s

### PR DESCRIPTION
**Pull request by gonzalochief**
The name of the config file is not matching the name in the official container image
 "-config.file=/etc/promtail/config.yml"
This causes an error when deploying the container with kubernetes
Replicate:
1. run docker pull docker.io/grafana/promtail:2.2.0
2. run docker inspect on the image (or you can check it on dockerhub)
3. compare with the template

Screen Shot 2022-08-19 at 8 19 36 PM

this would fix the error

### CODE REVIEW

**Comment by gonzalochief** [comment]
Screen Shot 2022-08-19 at 8 33 00 PM

**Comment by zanhsieh** [comment]
@gonzalochief 
Could you bump the Chart.yaml version and sign DCO please?

**Comment by gonzalochief** [comment]
The chart for the entire deployment is as follows:

filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: jxgh/grafana-dashboard
  version: 0.2.2
  name: grafana-dashboard
  values:
  - ../../versionStream/charts/jxgh/grafana-dashboard/values.yaml.gotmpl
  - jx-values.yaml
- chart: grafana/loki
  version: 2.5.0
  name: loki
  values:
  - ../../versionStream/charts/grafana/loki/values.yaml
  - jx-values.yaml
- chart: grafana/promtail
  version: 3.5.0
  name: promtail
  values:
  - ../../versionStream/charts/grafana/promtail/values.yaml
  - jx-values.yaml
- chart: grafana/tempo
  version: 0.6.8
  name: tempo
  values:
  - ../../versionStream/charts/grafana/tempo/values.yaml
  - jx-values.yaml
- chart: grafana/grafana
  version: 6.17.4
  name: grafana
  values:
  - ../../versionStream/charts/grafana/grafana/values.yaml.gotmpl
  - jx-values.yaml
- chart: prometheus-community/prometheus
  version: 13.6.0
  name: prometheus
  values:
  - ../../versionStream/charts/prometheus-community/prometheus/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}

The daemon set yaml is:

# Source: promtail/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  labels:
    helm.sh/chart: promtail-3.5.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: promtail
    app.kubernetes.io/version: "2.2.0"
    app.kubernetes.io/managed-by: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'promtail'
  namespace: jx-observability
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: promtail
      app.kubernetes.io/instance: promtail
  updateStrategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: promtail
        app.kubernetes.io/instance: promtail
      annotations:
        checksum/config: b7fbbaca1d3ebda96f03f974fd349255d5bdfc4cad0bbab14fca8da7e2406b11
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: promtail
      securityContext:
        runAsGroup: 0
        runAsUser: 0
      containers:
        - name: promtail
          image: "docker.io/grafana/promtail:2.2.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/promtail
            - name: run
              mountPath: /run/promtail
            - mountPath: /var/lib/docker/containers
              name: containers
              readOnly: true
            - mountPath: /var/log/pods
              name: pods
              readOnly: true
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: http-metrics
              containerPort: 3101
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
      volumes:
        - name: config
          secret:
            secretName: promtail
        - name: run
          hostPath:
            path: /run/promtail
        - hostPath:
            path: /var/lib/docker/containers
          name: containers
        - hostPath:
            path: /var/log/pods
          name: pods

Signed-off-by: Gonzalo Diaz Hoyos <gonzalochief@gmail.com>

**Comment by gonzalochief** [comment]
i'm creating a new one with proper sign off and unifying both PR

**Pull request closed without merging**
