### PR TITLE
[tempo-distributed] docs: Fix README markdown

### PR DESCRIPTION
**Pull request by rpriyanshu9**
Minor fix in `tempo-distributed` helm chart's README.

### CODE REVIEW

**Comment by rpriyanshu9** [comment]
Hi @zalegrala ! 
Can I get a review on this small PR please? Thanks.

**Comment by rpriyanshu9** [comment]
Also, please let me know if this requires a bump in the chart version. If it's not required, I'll remove the change.

**Comment by rpriyanshu9** [comment]
Hi @zanhsieh! Could you please take a look at this as well? Thank you.

Also do I need to bump the chart version after a change in README?

**Comment by zanhsieh** [comment]
> Hi @zanhsieh! Could you please take a look at this as well? Thank you.
> 
> Also do I need to bump the chart version after a change in README?

@rpriyanshu9 Yes. You need to bump the chart version, run helm-docs on the chart directory, then commit and push the change.

**Comment by rpriyanshu9** [comment]
@zanhsieh updated. Could you please review the changes? 

Thanks.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
