### PR TITLE
[grafana] Update app version to v10.4.3

### PR DESCRIPTION
**Pull request by xvilo**
As 10.4.3 has been released some time ago https://github.com/grafana/grafana/releases/tag/v10.4.3

### CODE REVIEW

**Comment by terop** [comment]
Also version [11.0.0](https://github.com/grafana/grafana/releases/tag/v11.0.0) has been released a few days ago. Would it make sense to update directly to it?

**Comment by xvilo** [comment]
Personally, I would definitely like to wait a while before updating to 11, so getting as much from 10.x as possible is preferred. Why not create a new release with this latest 10.x version anyway, I'm happy to create another one but I don't know if it needs additional changes in the chart, it's a major release after all.

**Comment by terop** [comment]
I updated my own Grafana instance to 11.0.0 and it seems to work fine. However my dashboards are very simple and thus do not "test" the changes in 11.0.0 thoroughly.

**Comment by xvilo** [comment]
Yeah, that is not the case for us. We have lots of dashboards and been using it since Grafana 5 or 6

**Comment by jkroepke** [comment]
> Also version [11.0.0](https://github.com/grafana/grafana/releases/tag/v11.0.0) has been released a few days ago. Would it make sense to update directly to it?

#3139

**Review by zanhsieh — APPROVED** [review]

**Comment by LarsStegman** [comment]
@gritzkoo @zalegrala since you recently this Chart, could you review this PR?

**Pull request merged**
