### PR TITLE
[promtail] Fix YAML parsing error

### PR DESCRIPTION
**Pull request by allanhung**
Re-procedure this issue:
```
$ helm pull --untar grafana/promtail --version 6.16.0
$ helm template --set serviceMonitor.enabled=true promtail/
Error: YAML parse error on promtail/templates/service-metrics.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key

Use --debug flag to render out invalid YAML
```

### CODE REVIEW

**Comment by davinkevin** [comment]
I bypassed it using this extra `values.yaml`

```
service:
  labels:
    uselessLabel: because-of-generation-issue
```

I subscribe to get notified when merged, so I can remove this hack.

thx

**Comment by pschichtel** [comment]
I usually prefer `with` instead of `if` in these cases

**Comment by allanhung** [comment]
> I usually prefer `with` instead of `if` in these cases

Thanks. I have updated the code to reflect this preference.

**Comment by allanhung** [comment]
duplicate with [#3164](https://github.com/grafana/helm-charts/pull/3164).

**Pull request closed without merging**
