### PR TITLE
[tempo-distributed] Add custom grpc configuration to server

### LINKED ISSUE #972: [tempo-distributed] Add custom grpc configuration for server
Hello
at the moment it's not possible to add a custom server grpc configuration in the [values file](https://github.com/grafana/helm-charts/blob/cf2c3ea0a45b0ba627a95581fc43a509211a9f03/charts/tempo-distributed/values.yaml#L468) unless you redefine the config like this:

```yaml
server:
  grpc_server_max_recv_msg_size: 1.34217728e+08
  grpc_server_max_send_msg_size: 1.34217728e+08
...
config: |
  server:
     grpc_server_max_recv_msg_size: {{ .Values.server.grpc_server_max_recv_msg_size }}
     grpc_server_max_send_msg_size: {{ .Values.server.grpc_server_max_send_msg_size }}
```

It would be useful to allow this configuration in the values file directly, like for compactor [storage retention](https://github.com/grafana/helm-charts/blob/c490602c674b108b61ee4a4d2807e621f278bdf4/charts/tempo-distributed/values.yaml#L196)

### PR DESCRIPTION
**Pull request by irizzant**
Closes #972 
This PR allows users to specify a custom server grpc client config, see #972

### CODE REVIEW

**Comment by irizzant** [comment]
@joe-elliott can you please have a look ad this?

**Review by annanay25 — DISMISSED** [review]
Thanks, can you please fix the lint issues and then we can merge.

**Comment by irizzant** [comment]
@annanay25 can you please provide guidance for this? I don't understand where those trailing spaces are

**Comment by irizzant** [comment]
@annanay25 never mind, done

**Review by annanay25 — APPROVED** [review]
Thanks @irizzant!

**Comment by irizzant** [comment]
Thank you!

**Pull request merged**
