### PR TITLE
[tempo-vulture] add installation guide to tempo chart

### PR DESCRIPTION
**Pull request by yonahd**
Signed-off-by: ydissen <yonahdissen@gmail.com>

### CODE REVIEW

**Review by mapno — APPROVED** [review]

**Comment by mapno** [comment]
The README is built from the template in the same folder

**Comment by yonahd** [comment]
@mapno Moved the changes to the template

**Comment by yonahd** [comment]
@mapno what is failing the ci here?

**Comment by yonahd** [comment]
Thanks!

**Comment by mapno** [comment]
Thanks

**Pull request merged**
