### PR TITLE
[grafana] chore: grafana: remove namespace from podsecuritypolicy

### PR DESCRIPTION
**Pull request by takirala**
> A Pod Security Policy is a cluster-level resource that controls security sensitive aspects of the pod specification.

https://kubernetes.io/docs/concepts/policy/pod-security-policy/#what-is-a-pod-security-policy

### CODE REVIEW

**Comment by zanhsieh** [comment]
@takirala 
Could you bump the chart version to latest please? The build system won't allow to merge without bumping the version in Chart.yaml.

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@torstenwalter 
How do I reset the test platform?
```
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  62s (x8 over 10m)  default-scheduler  0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.
```

**Comment by torstenwalter** [comment]
@zanhsieh just re-trigger the pipeline. The cluster is created using GitHub action https://github.com/grafana/helm-charts/blob/main/.github/workflows/lint-test.yaml#L40-L42 just for the pipeline run.

**Comment by zanhsieh** [comment]
> @zanhsieh just re-trigger the pipeline. The cluster is created using GitHub action https://github.com/grafana/helm-charts/blob/main/.github/workflows/lint-test.yaml#L40-L42 just for the pipeline run.

Retriggered. Still failed.

**Pull request closed without merging**
