### PR TITLE
[tempo-distributed] Add Custom Labels on Gateway Ingress.

### LINKED ISSUE #2912: [TEMPO] Allow Setting Custom Labels on Gateway Ingress
We require a label on the ingress, to allow `external dns` to know to create a DNS record.

https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml#L1682
https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/templates/gateway/ingress-gateway.yaml#L12

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #2912

### CODE REVIEW

**Comment by jseiser** [comment]
I think you messed up the values.yaml.  You created a default label on a service.

**Comment by Sheikh-Abubaker** [comment]
> I think you messed up the values.yaml. You created a default label on a service.

would it be only `externalDns` instead of what I defined there ?

**Comment by jseiser** [comment]
What i mean is, you want the ability to add labels on the ingress, if they are defined.

```
    {{- with .Values.gateway.ingress.labels }}
    {{- toYaml . | nindent 4}}
    {{- end}}
```

But you set hardcoded labels on a service.  `.Values.gateway.service.labels`

https://github.com/grafana/helm-charts/blob/0247d81b443982353e257fe6f43c980e7c225533/charts/tempo-distributed/values.yaml#L1679

You want to set the `service.labels` back to empty, then just add an empty labels entry under `gateway.ingress`

**Comment by Sheikh-Abubaker** [comment]
> You still have an issue here: https://github.com/grafana/helm-charts/pull/2913/files#diff-5414418aa29e8ed64794c82c7095aa92f5086272f5bd83c823d2c97c7d108d31R1692
> 
> ```
>     labels:
>       external-dns.alpha.kubernetes.io/hostname: ""
> ```
> 
> Should be
> 
> ```
>     labels: {}
> ```
> 
> Otherwise you are forcing people to label their ingress when they may not want too.

so d

> You still have an issue here: https://github.com/grafana/helm-charts/pull/2913/files#diff-5414418aa29e8ed64794c82c7095aa92f5086272f5bd83c823d2c97c7d108d31R1692
> 
> ```
>     labels:
>       external-dns.alpha.kubernetes.io/hostname: ""
> ```
> 
> Should be
> 
> ```
>     labels: {}
> ```
> 
> Otherwise you are forcing people to label their ingress when they may not want too.

so do you mean it should be this ?

```
 labels: {}
       external-dns.alpha.kubernetes.io/hostname: ""
```

**Comment by jseiser** [comment]
That looks correct.

**Comment by Sheikh-Abubaker** [comment]
> That looks correct.

Thank you.

**Review by zanhsieh — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@zalegrala can you please check this PR and approve if it is up to mark.

**Review by zalegrala — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@zalegrala I think there is some issue here, the automatic merging isn't happening.

**Comment by zalegrala** [comment]
Hmm, can you push an empty commit to force the CI again?

**Comment by Sheikh-Abubaker** [comment]
> Hmm, can you push an empty commit to force the CI again?

It didn't work, is there any way you can do it manually ?

**Comment by Sheikh-Abubaker** [comment]
@zalegrala all checks have been passed.

**Pull request merged**
