### PR TITLE
[tempo-distributed] Fix global.extraEnv key support for metrics-generator statefulset

### PR DESCRIPTION
**Pull request by bruksnys**
Fixes global.extraEnv key support for metrics-generator when it is deployed as kind: StatefulSet

Resolves: #3346

### CODE REVIEW

**Comment by Sheikh-Abubaker** [comment]
Hey @bruksnys Thanks for the contribution! could you please address the failed CI check by running `helm-docs` inside [charts/tempo-distributed](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed) and then we are good to go!

**Comment by bruksnys** [comment]
> Hey @bruksnys Thanks for the contribution! could you please address the failed CI check by running `helm-docs` inside [charts/tempo-distributed](https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed) and then we are good to go!

Sure thing! I've already re-run the helm-docs and will be waiting for the green pipeline! 👍

**Comment by bruksnys** [comment]
@Sheikh-Abubaker All of the checks are now passing, please let me know if anything else is needed on my side. Thank you!

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM!!

**Comment by bruksnys** [comment]
updated, signed CLA.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
