### PR TITLE
[promtail] Avoid unnecessary pod restart on each helm chart version

### PR DESCRIPTION
**Pull request by jkroepke**
This PR changes the the input of the config checksum which triggers the reload.

On main branch, the whole configmap/secret checksum is included as checksum input. The configmap contains labels which includes the helm chart version. Each new helm chart version forces a pod restart which is not always necessary.

For example: #2221 would not require a pod restart.

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by jkroepke** [comment]
@zanhsieh I fixed the version conflict.

**Comment by zanhsieh** [comment]
@zalegrala Can you review this PR please?

**Comment by zalegrala** [comment]
I believe this will mean that you never restart your pods, even if there is a major version bump, correct?  Are we sure this is desireable?

**Comment by jkroepke** [comment]
If a major version of a helm chart does not modify config or podSpec, whats the reason for the restart?

**Comment by zalegrala** [comment]
Would a major version bump of promtail be caught here?

**Comment by jkroepke** [comment]
> Would a major version bump of promtail be caught here?

Sure, if the major version bump changes podSpec (which includes the image version) or config, it would restart the promtail as expected.

**Review by zalegrala — APPROVED** [review]

**Pull request merged**
