### PR TITLE
[loki-distributed] Add optional appProtocol to memberlist svc

### PR DESCRIPTION
**Pull request by jdgeisler**
This PR references the same issue as https://github.com/grafana/helm-charts/issues/1099, but for the loki-distributed helm-chart.

Using istio protocol selection, the ports break in the memberlist service and throw the following error:
```
level=warn ts=2021-08-13T10:42:42.205933Z caller=client.go:344 component=client host=api.*.appdomain.cloud msg=“error sending batch, will retry” status=500 error="server returned HTTP status 500 Internal Server Error (500): empty ring"
```

This can be fixed by adding the `appProtocol` field in the memberlist service and setting it to `tcp` for loki-distributed. If appProtocol is left empty, then it will be ignored and not included in the service.

### CODE REVIEW

**Review by trevorwhitney — APPROVED** [review]
lgtm

**Comment by CharlieC3** [comment]
@jdgeisler After specifying the `appProtocol` as `tcp`, I started seeing these warnings every few seconds for all loki microservices:
```
Was able to connect to loki-<component> over TCP but UDP probes failed, network may be misconfigured
```

Are you seeing this too? Any idea how to resolve this problem without removing the istio sidecar from Loki?

**Comment by jdgeisler** [comment]
@CharlieC3 hmm we are not seeing that error in any of our loki microservices with `appProtocol` set to `tcp` in memberlist.

What is your current configuration? Maybe something else could be conflicting with it.

**Comment by rlex** [comment]
memberlist protocol is specified as TCP anyway, so UDP probes will always fail with or without appProtocol

**Comment by CharlieC3** [comment]
@jdgeisler You said you're using `istio` too, right? I can confirm if I disable sidecar injection for all Loki pods, I don't see this error anymore. It's only when istio injects a sidecar into the Loki pods.

I don't think I'm doing anything special. I have a pretty vanilla deployment of the loki-distributed Helm chart deployed to a cluster in GKE (with a dataplane v2 network), shipping logs to GCS. The Istio deployment is pretty simple as well, coming from [their Helm charts](https://github.com/istio/istio/tree/master/manifests/charts).

Any ideas what could be happening?

**Comment by CharlieC3** [comment]
For posterity, I was able to get around this by adding the following labels to all Loki pods (not deployments/STSs) in the chart:
```
traffic.sidecar.istio.io/excludeInboundPorts: "7946"
traffic.sidecar.istio.io/excludeOutboundPorts: "7946"
```

However, am still curious as to why this is happening. Running a manual UDP test shows the ports are open and able to communicate. I had to add these annotations to my Grafana Mimir deployment as well since that uses the memberlist/gossip-ring protocol too.

**Comment by jdgeisler** [comment]
@CharlieC3 yes, we are using Istio and have the loki-distributed helm chart deployed to an EKS cluster. 

I attempted to reproduce your issue but was unable to replicate that behavior. From what I've seen though, this may just be an ignorable error from memberlist. Do you see ingestion or querying impacted from these errors, or is everything working as expected?

Here is a sort of related thread for Tempo https://github.com/grafana/tempo/issues/927#issuecomment-1155103282

**Comment by CharlieC3** [comment]
@jdgeisler I didn't see any performance impact while the issue was happening. I haven't been able to find anyone that's having the same problem as me either. I feel it may be specific to GKE clusters running a certain version of Cilium, but don't have an hard evidence to support that.

**Pull request merged**
