### PR TITLE
[loki-distributed] fix: s3 example documentation in README.md

### PR DESCRIPTION
**Pull request by benjyiw**
using the example documentation for s3 results in failure to parse the yaml config. this pr updates the example with the correct fields.

ref this output from the loki components when using the example config:
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
  line 2: field boltdb_shipper not found in type loki.ConfigWrapper
```
and then also
```
failed parsing config: /etc/loki/config/config.yaml: yaml: unmarshal errors:
  line 81: field shared_storage not found in type shipper.Config
```

### CODE REVIEW

**Comment by zanhsieh** [comment]
@benjyiw 
Please bump the chart version to latest. Thank you.

**Comment by vlad-diachenko** [comment]
@benjyiw could you please move your changes to `charts/loki-distributed/README.md.gotmpl` template file, bump the version of the chart and run the command in the root of git repository: 
```bash
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

this command will generate RADME.md file with your changes and with a new version of the chart.

**Review by vlad-diachenko — CHANGES_REQUESTED** [review]
thanks for your fix. could you please check my comment https://github.com/grafana/helm-charts/pull/1130#issuecomment-1090270668

**Comment by benjyiw** [comment]
@vlad-diachenko thanks for the instruction. that's complete!

**Review by vlad-diachenko — APPROVED** [review]
LGTM, thanks @benjyiw

**Pull request merged**
