### PR TITLE
[tempo-distributed] Enable security context for pods and containers

### PR DESCRIPTION
**Pull request by warrenhodg**
Enable security context for pods and containers as per the style of
the loki-distributed chart.

Signed-off-by: Warren Hodgkinson <warren.hodgkinson@gmail.com>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@warrenhodg 
Could you bump the chart version to latest? Please bump minor version since previously this chart does not have security context.

**Comment by joe-elliott** [comment]
Thanks for the contribution. As @zanhsieh noted it needs a version bump. Also please run helm-docs or the linter won't pass:

```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

One question:
Will this break upgrades? If we change the use that Tempo is running as I'm concerned the ingesters will not be able to access all the files it created when it comes back up.

**Comment by zanhsieh** [comment]
@warrenhodg 
Could you bump Chart.yaml version to latest please?

**Comment by joe-elliott** [comment]
Does this recently merged PR accomplish what you want?

https://github.com/grafana/helm-charts/pull/1443

**Pull request closed without merging**
