### PR TITLE
[loki-distributed] update to loki version 2.7.1

### PR DESCRIPTION
**Pull request by gasmick**
Add upgrading notes, because a few changes to config are necessary:
* [`fifocache` has been renamed to `embedded_cache`](https://grafana.com/docs/loki/next/upgrading/#270)
* [`compactor_address` is expected in `common` settings](https://github.com/grafana/loki/issues/7222)

### CODE REVIEW

**Comment by den-is** [comment]
It might be good to have a stanza for compactor config too

**Comment by gasmick** [comment]
Added stanzas, as suggested:

The in-memory `fifocache` has been renamed to more general `embedded_cache`, which currently doesn't have a `max_size_items` attribute.

```yaml
loki:
  config: |
    chunk_store_config:
      chunk_cache_config:
        embedded_cache:
          enabled: false
```

`compactor_address` has to be explicitly set in the `common` section of the config.
```yaml
loki:
  config: |
    common:
      compactor_address: {{ include "loki.compactorFullname" . }}:3100
```

**Comment by id-tari** [comment]
First of all huge thanks for all your work.
But I have described "stanzas" badly.
I was talking not about configuration example stanzas in README.md but actual configuration stanzas in loki.config yaml template

I.e:
How to add custom compactor config to existing template without completely overriding this "huge text" template variable:
```yaml
compactor:
  compaction_interval: 10m
  delete_request_cancel_period: 15m
  deletion_mode: filter-and-delete
  retention_delete_delay: 2h
  retention_enabled: true
  shared_store: s3
```

**Comment by den-is** [comment]
First of all huge thanks for all your work.
But I have described "stanzas" badly.
I was talking not about configuration example stanzas in README.md but actual configuration stanzas in loki.config yaml template

I.e:
How to add custom compactor config to existing template without completely overriding this "huge text" template variable:
```yaml
compactor:
  compaction_interval: 10m
  delete_request_cancel_period: 15m
  deletion_mode: filter-and-delete
  retention_delete_delay: 2h
  retention_enabled: true
  shared_store: s3
```

**Comment by gasmick** [comment]
@den-is if I've understood you correctly, then this might be helpful,
since`loki.structuredConfig` takes precedence over `loki.config`

```yaml
loki:
  structuredConfig:
    compactor:
      shared_store: s3
```

**Comment by den-is** [comment]
@gasmick thanks! Indeed! I somehow have overseen this option.

**Comment by patsevanton** [comment]
https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/Chart.yaml have version: 0.68.1

**Comment by gasmick** [comment]
@patsevanton thank you for the tip - updated

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
