### PR TITLE
[tempo-distributed] add persistentVolumeClaimRetentionPolicy for ingester

### PR DESCRIPTION
**Pull request by pohldk**
This was added to Loki distributed chart but would be useful for tempo distributed chart as well.

### CODE REVIEW

**Comment by Sheikh-Abubaker** [comment]
Hey @pohldk, could you please bump the chart version to `1.23.0` in order to fix the CI lint test.

**Comment by pohldk** [comment]
@Sheikh-Abubaker 
done 👍

**Comment by jkroepke** [comment]
Please create a distinct PR for each chart. 

The CI and approval process is not designed for PR over multiple charts.

**Comment by pohldk** [comment]
Please reopen, clearly a mistake @jkroepke we simply need to only run helmdocs on tempo. My bad.

**Comment by pohldk** [comment]
@jkroepke if you reopen you it should update the PR with the corrected commit on the branch:

https://github.com/grafana/helm-charts/commit/bb63dd6c235a37f0308da6eaa7e1d2ccdf6882cd

**Comment by jkroepke** [comment]
It seems like you do a force-push with prevents a reopen.

image

Please create a new PR, thanks!

**Comment by pohldk** [comment]
@jkroepke https://github.com/grafana/helm-charts/pull/3429 done

**Pull request closed without merging**
