### PR TITLE
[grafana] autoMount set to false in values.yaml

### LINKED ISSUE #2976: [grafana] Service account automountServiceAccountToken should be set to false
Disabling automatic token mounting with automountServiceAccountToken set to false enhances security and control in Kubernetes by reducing attack surface, providing explicit control over token usage, avoiding unnecessary access, and meeting compliance and security requirements.

While looking at the grafana service, I noticed that the automountServiceAccountToken flag is set to true and I'm trying to understand if there is a reason for this, if not, I'm interested in setting the flag to false.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #2976

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by Xtigyro — APPROVED** [review]

**Comment by onedr0p** [comment]
# Please revert this, it is a breaking change for anyone using the sidecar for dashboards

**Comment by onedr0p** [comment]
@Sheikh-Abubaker 
A PR should be made to revert this in a new version to `7.3.2`, and then if ya'll really want this token disabled by default,, create a new release with `8.0.0` with the change. All of these steps will require maintainers to review and merge.

**Comment by Sheikh-Abubaker** [comment]
@onedr0p 
> IMO I don't think that this token should be disabled by default because it breaks an important feature of the helm chart which is grafana chart discovery from configmaps in your cluster.

Makes sense, but I'm wondering if I should revert this PR right way or wait for the maintainers comment ? as the PR was reviewed and approved by two of them ?

**Comment by onedr0p** [comment]
@Sheikh-Abubaker 

I would at least get a PR ready to undo this. Who knows when the maintainers are going be respond to this.

**Comment by Sheikh-Abubaker** [comment]
Alright I'll open a PR to revert this and  wait for the maintainer's to review this.

**Comment by diranged** [comment]
Just chiming in support here - maintainers, please revert this. This is a breaking change.

**Pull request merged**
