### PR TITLE
[tempo-distributed] feat: add cli flag for zone aware ingestion

### PR DESCRIPTION
**Pull request by KyriosGN0**
like in mimir, we need to pass `ingester.ring.instance-availability-zone` when enabled zone aware ingestion 
FYI @zalegrala

### CODE REVIEW

**Comment by zalegrala** [comment]
I get the following when trying to pass that flag.
```
flag provided but not defined: -ingester.ring.instance-availability-zone
```

**Comment by KyriosGN0** [comment]
@zalegrala weird, in our mimir we use this flag, but according to the Cortex Config it should be `-ingester.availability-zone`
i'll try to compile in jsonnet since it also has a Zone Aware config

**Comment by KyriosGN0** [comment]
hm @zalegrala i looked into the jsonnet and they only set the env var `availability_zone` which corresponds to the `-ingester.availability-zone` cli flag according to the cortex docs, so i think its good enough.

**Comment by zalegrala** [comment]
Each database exposes different config flags, so we can't assume that because its exposed in mimir that it would be exposed in tempo.  Have you had a chance to test this change?

**Comment by KyriosGN0** [comment]
@zalegrala `-ingester.availability-zone` is equivalent to the env var set in the jsonnet file of Tempo, i'll try to deploy this locally in some KIND cluster to see that it recognizes the flag.

**Comment by KyriosGN0** [comment]
@zalegrala after taking another look in the jsonnet file i've realized i've missed other things in the chart (like services) 
i would also need to open PR to tempo itself to support this cli flag (or figure out how to implement this with the env va)
will ping you when im ready, until then i've converted this to a Draft pr

**Comment by KyriosGN0** [comment]
@zalegrala should be good now.

**Review by zalegrala — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
