### PR TITLE
[tempo] Update statefulset.yaml to enable otel-http (port 4318)

### PR DESCRIPTION
**Pull request by yosefy**
otherwise it doesn't work at all because service is set to use it but stateful set doesn't expose it

### CODE REVIEW

**Comment by yosefy** [comment]
how can i do this DCO:  Signed-off-by: Author Name <authoremail@example.com>\
on existing pr?

**Comment by ofirshtrull** [comment]
@swartz-k @annanay25 @dgzlopes @joe-elliott @mapno @mdisibio @BitProcessor @faustodavid @yosefy 
This feater is very impotent for my work, any chance we can push this forward?

**Review by ofirshtrull — APPROVED** [review]

**Comment by faustodavid** [comment]
Thanks for the contribution @yosefy!

Please sign your commits, change the Chart version to `1.2.2`, and update the docs.

**Comment by yosefy** [comment]
> Thanks for the contribution @yosefy!
> 
> Please sign off your commits, change the Chart version to `1.2.2`, and update the docs.

hi, updated the chart version, no need to update the docs as they are ok

**Comment by faustodavid** [comment]
> > Thanks for the contribution @yosefy!
> > Please sign off your commits, change the Chart version to `1.2.2`, and update the docs.
> 
> hi @faustodavid , updated the chart version, no need to update the docs as they are ok

We need to update the docs because we are changing the chart version. 

Go to the chart folder and run
```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.8.1
```

Then commit the changes. Additionally, you need to sing off your commits.

**Pull request closed without merging**
