### PR TITLE
[loki-stack] Updated Prometheus chart version

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Issue #2877

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by zalegrala — APPROVED** [review]

**Comment by StefanLobbenmeierObjego** [comment]
Can we add to the release notes that this might require manual upgrade? Since it is a minor loki-stack release I expected it to work without 

https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150

**Comment by Sheikh-Abubaker** [comment]
> Can we add to the release notes that this might require manual upgrade? Since it is a minor loki-stack release I expected it to work without
> 
> https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus/README.md#to-150

This is the first time I will add release notes, is there any example PR to which I can refer to ? also since the PR has been merged is it possible to push changes to this PR now ?

**Comment by Sheikh-Abubaker** [comment]
> I think the maintainers can edit the release notes.
> 
> In my case I even had to do delete this before the upgrade:
> 
> ```shell
> # Prepare upgrade
> kubectl delete daemonset -n monitoring monitoring-prometheus-node-exporter
> kubectl delete deployments.apps -n monitoring monitoring-prometheus-pushgateway
> 
> # Upgrade
> helm upgrade -n monitoring monitoring grafana/loki-stack 
> ```
> 
> To solve these errors:
> 
> ```
> Error: UPGRADE FAILED: cannot patch "monitoring-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "monitoring-prometheus-node-exporter" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitoring", "app.kubernetes.io/name":"prometheus-node-exporter"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable && cannot patch "monitoring-prometheus-pushgateway" with kind Deployment: Deployment.apps "monitoring-prometheus-pushgateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"monitoring", "app.kubernetes.io/name":"prometheus-pushgateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
> ```
> 
> Not sure if there was a way without

Seems like I won't be able to do anything as of now right ? Only maintainers would be able to help us here.

**Comment by JStickler** [comment]
@StefanLobbenmeierObjego these Helm Charts are community maintained and are no longer documented in the Loki documentation or Release Notes.

**Comment by StefanLobbenmeierObjego** [comment]
Is there any way to put something in the Github Release from the community? https://github.com/grafana/helm-charts/releases/tag/loki-stack-2.9.12

Otherwise its good to know that maybe we just put it in the PRs and have to remember to check there.

**Pull request merged**
