### PR TITLE
[loki-distributed] Table manager replicas from values

### PR DESCRIPTION
**Pull request by sergeyshaykhullin**
Does table manager is designed to have 1+ replicas?

If it is - i guess replicas should be set from values

If not - need to delete replicas from tableManager values and fix pdb

### CODE REVIEW

**Comment by Whyeasy** [comment]
As far as I know table manager should only run on it's own. @slim-bean @owen-d Could you please confirm?

**Comment by unguiculus** [comment]
I think so, too. That's why replicas cannot be set.

**Comment by Whyeasy** [comment]
I would say, try it and see if it's a breaking change locally 😄

**Review by Whyeasy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
