### PR TITLE
[grafana] - Add support for templating in ServiceMonitor labels

### PR DESCRIPTION
**Pull request by Allex1**
Allows adding global helm vars as label values in the form of "{{ .Release.Name }}" on the serviceMonitor resource

### CODE REVIEW

**Comment by Allex1** [comment]
@zanhsieh pls review

**Review by zanhsieh — APPROVED** [review]

**Comment by Allex1** [comment]
@maorfr @torstenwalter @Xtigyro can we merge this ?

**Comment by Allex1** [comment]
ping

**Comment by Allex1** [comment]
@maorfr @torstenwalter @Xtigyro @zanhsieh can we merge this ?

**Review by Xtigyro — APPROVED** [review]

**Pull request merged**
