### PR TITLE
[promtail] Changes in promtail config for GKE Autopilot.

### PR DESCRIPTION
**Pull request by ashmitakapoor**
GKE Autopilot only allows readOnly access to hostpath /var/log as a security consideration. It also only supports containerd as a container runtime. Therefore, the log volumes need to be modified to mount the correct directory in readOnly mode.
Refer - https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-security#built-in-security

### CODE REVIEW

**Comment by zanhsieh** [comment]
@ashmitakapoor 
Just curious, what are those helm*.md files for?

**Comment by ashmitakapoor** [comment]
The files got created when I ran helm-docs. Have removed them.

**Comment by zanhsieh** [comment]
@ashmitakapoor 
Thanks for the contribution. Could you sign DCO please?

**Comment by BSDandEspresso** [comment]
Any ETA on this? We're migrating to Autopilot clusters and I need promtail...

**Comment by zanhsieh** [comment]
@ashmitakapoor 
Also, be aware this PR might get rejected unless the code submitted works with backward compatibility.

**Pull request closed without merging**
