### PR TITLE
[loki-distributed] Add `ServiceMonitor` to `gateway` component

### PR DESCRIPTION
**Pull request by AmitBenAmi**
- Adding `ServiceMonitor` to `loki-gateway`
- Bumping the chart version

### CODE REVIEW

**Review by unguiculus — COMMENTED** [review]
That's interesting. Currently, the gateway does not expose any metrics. Why would you need that?

However, that brings me to the idea that it could be a good idea to also use the gateway to proxy metrics endpoints. That would be beneficial for network policies.

**Comment by AmitBenAmi** [comment]
Do you mean to provide a single endpoint for all of the metrics of the components?
What would then be in the NetworkPolicy? Only for Prometheus/other clients?

**Comment by unguiculus** [comment]
No, I thought about separate endpoints for each components. That was just a thought. I guess it's not a good idea because it would actually have to be per pod.

Anyways, why do you need a service monitor for the gateway? We'd have to add an exporter for Nginx in the first place, I guess?

**Comment by AmitBenAmi** [comment]
I actually have metrics in loki `v1.3.0` from `gateway`, but also there I can't find the `/metrics` endoint of nginx.
I guess it is not that important. I'll close the PR

**Pull request closed without merging**
