### PR TITLE
[loki-stack] Bumped version

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes Issue #2873

### CODE REVIEW

**Review by zalegrala — APPROVED** [review]

**Review by zalegrala — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@zalegrala I was wondering if I should bump the chart version to 2.11.0 or 2.12.0, as loki-stack is being updated to the recent version like 2.9.3 ?

**Comment by zalegrala** [comment]
That's up to the community.  In my opinion, chart versions don't need to match app versions.

**Comment by Sheikh-Abubaker** [comment]
> That's up to the community. In my opinion, chart versions don't need to match app versions.

ok thank you!

**Review by zanhsieh — APPROVED** [review]

**Comment by kingbj940429** [comment]
I pulled grafana/loki-stack v2.10.1

but, sub chart loki's version in loki-stack is v2.6.1

스크린샷 2024-01-23 오후 3 34 19

this is loki sub chart in loki-stack
image

this is loki-stack 
스크린샷 2024-01-23 오후 3 35 33

Is there something I missed?

**Comment by renzibin** [comment]
@Sheikh-Abubaker There is an issue with your pull request, 
https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml#L5 
this line version, the mapping version for Loki is v2.6.1, refer to: https://github.com/grafana/helm-charts/blob/loki-2.15.2/charts/loki/Chart.yaml#L4

**Comment by gawbul** [comment]
The subchart needs updating for this too. I am hitting issues on newer versions of Grafana because the Loki version is so out-of-date. The latest release, I believe, is 2.9.5. I had to use a hack to manually set the image repository and tag in the config to get this to work.

**Pull request merged**
