### PR TITLE
[loki] Update statefulset.yaml fix mismatch in config file names between chart and container that prevents pod launch in k8s

### PR DESCRIPTION
**Pull request by gonzalochief**
The name of the config file is not matching the name of the config file in the official container
Screen Shot 2022-08-19 at 8 37 00 PM
Screen Shot 2022-08-19 at 8 38 34 PM

### CODE REVIEW

**Comment by zanhsieh** [comment]
@gonzalochief 
Could you bump the Chart.yaml version and sign DCO please?

**Comment by gonzalochief** [comment]
The following is the helm file of the entire deployment

filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx-observability
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
releases:
- chart: jxgh/grafana-dashboard
  version: 0.2.2
  name: grafana-dashboard
  values:
  - ../../versionStream/charts/jxgh/grafana-dashboard/values.yaml.gotmpl
  - jx-values.yaml
- chart: grafana/loki
  version: 2.5.0
  name: loki
  values:
  - ../../versionStream/charts/grafana/loki/values.yaml
  - jx-values.yaml
- chart: grafana/promtail
  version: 3.5.0
  name: promtail
  values:
  - ../../versionStream/charts/grafana/promtail/values.yaml
  - jx-values.yaml
- chart: grafana/tempo
  version: 0.6.8
  name: tempo
  values:
  - ../../versionStream/charts/grafana/tempo/values.yaml
  - jx-values.yaml
- chart: grafana/grafana
  version: 6.17.4
  name: grafana
  values:
  - ../../versionStream/charts/grafana/grafana/values.yaml.gotmpl
  - jx-values.yaml
- chart: prometheus-community/prometheus
  version: 13.6.0
  name: prometheus
  values:
  - ../../versionStream/charts/prometheus-community/prometheus/values.yaml
  - jx-values.yaml
templates: {}
renderedvalues: {}

The chart with the mismatch is:

# Source: loki/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki
  namespace: jx-observability
  labels:
    app: loki
    chart: loki-2.5.0
    release: loki
    heritage: Helm
    gitops.jenkins-x.io/pipeline: 'namespaces'
  annotations:
    meta.helm.sh/release-name: 'loki'
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  selector:
    matchLabels:
      app: loki
      release: loki
  serviceName: loki-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: loki
        name: loki
        release: loki
      annotations:
        checksum/config: 78f6997851c726eba6b0b34b514bc4b3e16f10411d45e7ba4f60c7fb9e9d26b3
        prometheus.io/port: http-metrics
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: loki
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers: []
      containers:
        - name: loki
          image: "grafana/loki:2.2.0"
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/loki/loki.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: storage
              mountPath: "/data"
              subPath:
          ports:
            - name: http-metrics
              containerPort: 3100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          readinessProbe:
            httpGet:
              path: /ready
              port: http-metrics
            initialDelaySeconds: 45
          resources: {}
          securityContext:
            readOnlyRootFilesystem: true
          env:
      nodeSelector: {}
      affinity: {}
      tolerations: []
      terminationGracePeriodSeconds: 4800
      volumes:
        - name: config
          secret:
            secretName: loki
  volumeClaimTemplates:
    - metadata:
        name: storage
        annotations: {}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "10Gi"
        storageClassName:

Signed-off-by: Gonzalo Diaz Hoyos <gonzalochief@gmail.com>

**Comment by gonzalochief** [comment]
I cannot get the DCO to work
the git push is failing 
ERROR: Permission to grafana/helm-charts.git denied to gonzalochief.
fatal: Could not read from remote repository.

**Comment by zanhsieh** [comment]
> I cannot get the DCO to work the git push is failing ERROR: Permission to grafana/helm-charts.git denied to gonzalochief. fatal: Could not read from remote repository.

@gonzalochief
It seems to me that you push to grafana/helm-charts, not your own folks (gonzalochief:gonzalochief-patch-2). Please sign on your own forks. Thank you.

**Comment by gonzalochief** [comment]
i'm creating a new one with proper sign off and unifying both PR

**Pull request closed without merging**
