### PR TITLE
[promtail] Update service template to fix broken promtail.

### LINKED ISSUE #3162: [promtail] 6.16.0 breaks the application if you don't include labels with service
With the 6.16.0 release, if you use the service option without any labels it breaks the chart.
Current template
```
metadata:
  name: {{ include "promtail.fullname" . }}-metrics
  namespace: {{ include "promtail.namespaceName" . }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
    {{- toYaml .Values.service.labels | nindent 4 }} # default service.labels: {}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
```

rendered:
```
apiVersion: v1
kind: Service
metadata:
  name: release-name-promtail-metrics
  namespace: default
  labels:
    helm.sh/chart: promtail-6.16.0
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "3.0.0"
    app.kubernetes.io/managed-by: Helm
    {}
  annotations:
    {}
```

We need to exclude the empty {} from the service labels to prevent breaking the chart.
I'll try to make a PR if someone doesn't beat me to it, but a simple fix for the time being is:

```
service:
  labels:
    fix: fix
```

The fix would be to look at something like:
```
metadata:
  name: {{ include "promtail.fullname" . }}-metrics
  namespace: {{ include "promtail.namespaceName" . }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
```

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #3162

### CODE REVIEW

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh @zalegrala please approve this PR to fix broken promtail application.

**Comment by Jivvon** [comment]
how about enable test for `service-metrics.yaml` in `ci/service-values.yaml` ?
```yaml
service:
  enabled: true
```
there is values only for `service-extra.yaml` in this file

**Comment by Sheikh-Abubaker** [comment]
@Xtigyro can you please approve this.

**Comment by Sheikh-Abubaker** [comment]
@jkroepke can you please approve this!

**Comment by jkroepke** [comment]
I'm not a maintainer

**Review by zalegrala — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh can you please approve this, sorry for mentioning every now and then, I'm not in a any sort of hurry but the promtail remains broken if this PR is not merged.

**Comment by jkroepke** [comment]
In general, the chart development is a big issue at grafana. I postet this already on slack

https://grafana.slack.com/archives/CBA3NSALE/p1717428598756549

but no one cares about.

**Comment by Sheikh-Abubaker** [comment]
> In general, the chart development is a big issue at grafana. I postet this already on slack
> 
> https://grafana.slack.com/archives/CBA3NSALE/p1717428598756549
> 
> but no one cares about.

I understand your concern, and the maintainers do care but the thing is this helm charts repo is so vast we need more active maintainers, and some of the maintainers are Individual contributors, so I think the active maintainers are doing great job, but it's just the volume of PRs are huge so we just need more maintainers and then everything would be fine.

**Comment by jkroepke** [comment]
> > In general, the chart development is a big issue at grafana. I postet this already on slack
> > [grafana.slack.com/archives/CBA3NSALE/p1717428598756549](https://grafana.slack.com/archives/CBA3NSALE/p1717428598756549)
> > but no one cares about.
> 
> I understand your concern, and the maintainers do care but the thing is this helm charts repo is so vast we need more active maintainers, and some of the maintainers are Individual contributors, so I think the active maintainers are doing great job, but it's just the volume of PRs are huge so we just need more maintainers and then everything would be fine and it is the same scenario for Grafana Loki also.

The problem that I see:

- half year ago, the minimum reviewer counter was increased to 2 which is too much with the current amount of maintainers. It was fine before.
- It's an chicken egg problem. I have no clue, who is the community lead here. The Prometheus Community had similar issues, until they create a dedicated issues for that topic: https://github.com/prometheus-community/helm-charts/issues/1656

**Comment by Sheikh-Abubaker** [comment]
> The problem that I see:
> 
> * half year ago, the minimum reviewer counter was increased to 2 which is too much with the current amount of maintainers. It was fine before.

That's right, and to resolve it if more active maintainers are required I'd be more than happy to step up and collaborate.

**Comment by Sheikh-Abubaker** [comment]
> > The problem that I see:
> > 
> > * half year ago, the minimum reviewer counter was increased to 2 which is too much with the current amount of maintainers. It was fine before.
> 
> @jkroepke That's right, and to resolve it if more active maintainers are required I'd be more than happy to step up and collaborate.

**Comment by Sheikh-Abubaker** [comment]
> * It's an chicken egg problem. I have no clue, who is the community lead here. The Prometheus Community had similar issues, until they create a dedicated issues for that topic: [Chart maintainers needed prometheus-community/helm-charts#1656](https://github.com/prometheus-community/helm-charts/issues/1656)

I think there should be similar solution needed for this repo also.

**Comment by Sheikh-Abubaker** [comment]
@Whyeasy can you please approve this PR!

**Comment by Sheikh-Abubaker** [comment]
@Xtigyro could you please approve this

**Review by dimitarvdimitrov — APPROVED** [review]

**Pull request merged**
