### PR TITLE
[agent-operator] Move crds(agent, prometheus) into separate subcharts

### PR DESCRIPTION
**Pull request by kuzm1ch**
Fix: https://github.com/grafana/loki/issues/7488 
```
Prometheus is installed using another chart (or any other method). The Prometheus CRDs are provided by this installation method. Installing also the CRD from the loki chart may produce CRD upgrade and downgrade with possible data lost.
```

These changes allow users to disable installation of specific CRD groups so users can avoid the situation when multiple helm charts manage/install the same CRDs.

Also, moving CRDs into subchart has some other benefits - https://github.com/prometheus-community/helm-charts/issues/3548.

### CODE REVIEW

**Comment by Vinaum8** [comment]
man, i need this!

**Comment by Vinaum8** [comment]
@kuzm1ch i think that you need mark the code owner for this code for PR is to review.

[CODE OWNERS - Grafana Helm Charts](https://github.com/grafana/helm-charts/blob/main/.github/CODEOWNERS)

**Comment by kuzm1ch** [comment]
@Vinaum8 agent-operator is not in a list in the https://github.com/grafana/helm-charts/blob/main/.github/CODEOWNERS, so I'll tag  @grafana/helm-charts-admins.  

If this simple PR is ok in general for @grafana/helm-charts-admins, I will fix conflicts and it can be merged.

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@kuzm1ch 
Can you fix the conflicts please?

**Comment by kuzm1ch** [comment]
> @kuzm1ch Can you fix the conflicts please?

done

**Review by zanhsieh — APPROVED** [review]

**Comment by Vinaum8** [comment]
@zanhsieh still need something in this PR?

**Comment by zanhsieh** [comment]
@Vinaum8 Grafana repo required two approvals in order to merge, so nothing I can do now.

**Comment by Vinaum8** [comment]
> @Vinaum8 Grafana repo required two approvals in order to merge, so nothing I can do now.

Thanks man!

**Comment by bobertrublik** [comment]
It would be awesome if we could merge this. We're managing CRDs separately from the Helm chart deployment and have issues integrating this chart.

**Comment by Vinaum8** [comment]
> It would be awesome if we could merge this. We're managing CRDs separately from the Helm chart deployment and have issues integrating this chart.

me too.

i waiting for this merge.

**Comment by mrclrchtr** [comment]
I don't understand that right now. Was the PR simply closed and therefore not merged? Does that mean the change will not be made?

**Pull request closed without merging**
