### PR TITLE
[loki-distributed] Added support for newer Ingress versions (v1) for the Gateway component

### PR DESCRIPTION
**Pull request by sherifkayad**
Signed-off-by: Sherif Ayad <sherif.k.ayad@gmail.com>

### CODE REVIEW

**Comment by sherifkayad** [comment]
@Whyeasy could you maybe have a look at this one here?

**Comment by Whyeasy** [comment]
Hey @sherifkayad,

Thanks for adding this, could you please increase the chart version to `0.35.0`? As this is a bigger change and people need to be aware of it 😄

**Comment by sherifkayad** [comment]
Sure thing .. let me do that and add some notes in the README 😉

**Comment by sherifkayad** [comment]
@Whyeasy can you check now?

**Review by Whyeasy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
