### PR TITLE
[tempo] add additional otlp ports

### PR DESCRIPTION
**Pull request by adrianliechti**
The OTLP change the default ports for http and grpc:
https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md

this also fixed a startup issue when defining both of the otlp protocols.

I kept the original one likewise the OTLP team seems to do this during transition phase

```
level=error ts=2021-03-29T19:00:27.711699252Z caller=app.go:235 msg="module failed" module=distributor err="invalid service state: Failed, expected: Running, failure: failed to start subservices not healthy, 0 terminated, 1 failed: [Error starting receiver listen tcp 0.0.0.0:55680: bind: address already in use]"
```

values in single-binary helm chart would then look like this:
```
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:55681
          grpc:
            endpoint: 0.0.0.0:4317
```

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thank you for this. I knew that OTLP was changing their default ports, but I wasn't tracking when it occurred.  Do you mind making the same change to the distributed helm chart? If it's a hassle I can grab it.

Also, it seems like it wants you to rerun that helm-docs command.

**Comment by adrianliechti** [comment]
sure!

I opened a second pull request as this bot told me to do: https://github.com/grafana/helm-charts/pull/350
also I ran helm-docs - but seems not happy with it. If you have an idea I'm happy to try it

**Comment by joe-elliott** [comment]
It looks like you are generating docs with 1.5.0 but this repo is using 1.4.0 when it checks. I think if you run the below it will work:

```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

**Review by joe-elliott — APPROVED** [review]

**Comment by joe-elliott** [comment]
Thanks for the contribution!

**Pull request merged**
