### PR TITLE
[tempo-distributed] add max_outstanding_per_tenant config in query frontend

### PR DESCRIPTION
**Pull request by bvillanueva-mdsol**
add max_outstanding_per_tenant config in query frontend as per https://grafana.com/docs/tempo/latest/configuration/#query-frontend

### CODE REVIEW

**Comment by bvillanueva-mdsol** [comment]
Hi! how can we run the required workflows?

**Comment by bvillanueva-mdsol** [comment]
Hi tempo-distributed admin, please approve workflows. Thanks!

**Review by mapno — APPROVED** [review]
LGTM

**Comment by bvillanueva-mdsol** [comment]
Updated the order of new config. Workflows should pass now. @mapno Please approve again workflow requests. Thanks a lot for checking.

**Comment by mapno** [comment]
We need a second approval. Let's me see if I find one.

**Review by joe-elliott — APPROVED** [review]

**Comment by bvillanueva-mdsol** [comment]
Thank you!

**Pull request merged**
