### PR TITLE
[tempo-distributed] structuredConfig support

### PR DESCRIPTION
**Pull request by rlex**
Add tempo structuredconfig override

### CODE REVIEW

**Comment by rlex** [comment]
Looks like this chart is ignored in helm-docs, so i temporary removed it from ignores, re-generated it and manually picked some changes. Should be fine i guess?

**Comment by rlex** [comment]
should close https://github.com/grafana/helm-charts/issues/838

**Comment by rlex** [comment]
added some info to README as well with examples

**Review by joe-elliott — APPROVED** [review]
Nice improvement, thanks!

I'll dig into why we are currently in `.helmdocsignore`. I had recently noticed that it was no longer requiring regenning the readme.md but I hadn't dug into why. Thanks for the heads up.

**Pull request merged**
