### PR TITLE
[tempo-distributed] Allow configurable replication factor for the ingester

### PR DESCRIPTION
**Pull request by AlexDHoffer**
Signed-off-by: AlexDHoffer <alexdchoffer@gmail.com>

Resolves https://github.com/grafana/helm-charts/issues/1110

### CODE REVIEW

**Comment by joe-elliott** [comment]
Yup, this we need this update. I'm tempted to default to 3 which is the only RF I'd consider appropriate for production.

WDYT?

**Comment by joe-elliott** [comment]
Yup, let's do both. Increase ingesters and RF to 3 by default. If someone is using tempo-distributed they are likely looking for a distributed, fault tolerant system and the defaults should give them that.

Thanks for these fixes!

**Comment by AlexDHoffer** [comment]
@joe-elliott Hey Joe, this is ready to go but there's a hard pod anti-affinity on the Ingester that is causing issues with CI/CD because there aren't enough nodes to satisfy the requirement.

Shall I turn down that affinity to ``preferred`` rather than ``required``?

**Comment by joe-elliott** [comment]
Yeah, after some thought let's try setting the pod anti-affinifty to preferred for `kubernetes.io/hostname`. If that doesn't work we can just go back to defaulting to RF1 and 1 ingester.

**Comment by AlexDHoffer** [comment]
@joe-elliott all set here

**Review by joe-elliott — APPROVED** [review]
Great stuff. Thanks Alex!

**Pull request merged**
