### PR TITLE
[loki-distributed] enable StatefulSetAutoDeletePVC feature for ingester

### PR DESCRIPTION
**Pull request by ivanfavi**
I followed a similar implementation from [loki-simple-scalable] [PR-1488](https://github.com/grafana/helm-charts/pull/1488) for this.

Signed-off-by: Ivan Farre  [ivan@bluelabs.eu](mailto:ivan@bluelabs.eu)

### CODE REVIEW

**Comment by ivanfavi** [comment]
Hi @unguiculus @Whyeasy ,

Could you please take another look and let me know if there are any thing that need to be addressed?

Thank you!

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@ivanfavi 
Thanks for the contribution. Can you fix the doc issue please?

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@ivanfavi
Thanks for the contribution. Can you fix the doc issue please?

**Comment by ivanfavi** [comment]
@zanhsieh I believe the documentation issue has been resolved. Please let me know if I've missed anything else.

**Review by zanhsieh — APPROVED** [review]

**Comment by ivanfavi** [comment]
Thanks for your updates and support on this @zanhsieh :heart:

**Pull request merged**
