### PR TITLE
[loki-distributed] add loki.structuredConfig for structured config overrides

### PR DESCRIPTION
**Pull request by wondersd**
@stevehipwell 

fixes: https://github.com/grafana/helm-charts/issues/978

### CODE REVIEW

**Comment by zanhsieh** [comment]
@wondersd 
Please bump the chart version to latest. Thank you.

**Comment by wondersd** [comment]
@zanhsieh looks like another pr was merged that updated to 0.42.0, should this go to 0.43.0?

**Comment by zanhsieh** [comment]
> @zanhsieh looks like another pr was merged that updated to 0.42.0, should this go to 0.43.0?

Sure. Please bump the chart version to latest. Thank you.

**Comment by Whyeasy** [comment]
@wondersd could you please add a small description in the Readme. So people are aware they could provide the config in 2 different ways.

**Comment by wondersd** [comment]
@Whyeasy please review documentation updates

**Comment by Whyeasy** [comment]
@wondersd LGTM, could you fix the conflicts so we can get this merged.

**Comment by wondersd** [comment]
@Whyeasy looks like @zanhsieh updated my branch, i think were good.

**Review by Whyeasy — APPROVED** [review]
LGTM!

**Pull request merged**
