### PR TITLE
[enterprise-metrics] feat: Upgrade to v1.4.1 release

### PR DESCRIPTION
**Pull request by jdbaldry**
To review the diff without the exports: https://github.com/grafana/helm-charts/pull/529/commits/b671e3c425087fcf30891c8fdb5ff0890de865b8

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by simonswine** [comment]
@jdbaldry I struggle to get f95eb22  working with pretty much any values files:

```
$ helm version                                                                                                                                                                                                                                                                      
version.BuildInfo{Version:"v3.2.1", GitCommit:"fe51cd1e31e6a202cba7dead9552a6d418ded79a", GitTreeState:"clean", GoVersion:"go1.13.10"}

$ helm install gem-test-a ./ --set-file "license.contents=$HOME/.grafana/gem-test-a" --set "minio.enabled=true" -f small.yaml
Error: template: enterprise-metrics/templates/store-gateway-statefulset.yaml:60:28: executing "enterprise-metrics/templates/store-gateway-statefulset.yaml" at <include (print $.Template.BasePath "/secret.yaml") .>: error calling include: template: enterprise-metrics/templates/secret.yaml:12:30: executing "enterprise-metrics/templates/secret.yaml" at <tpl (toYaml .Values.config) .>: error calling tpl: error during tpl function execution for "admin_client:\n  storage:\n    type: s3\nalertmanager:\n  data_dir: /data\n  enable_api: true\n  external_url: /alertmanager\n  sharding_enabled: true\n  sharding_ring:\n    kvstore:\n      store: memberlist\napi:\n  response_compression_enabled: true\nauth_enabled: false\nblocks_storage:\n  backend: s3\n  bucket_store:\n    sync_dir: /data/tsdb-sync\n  tsdb:\n    dir: /data/tsdb\ncluster_name: '{{ .Release.Name }}'\ncompactor:\n  sharding_enabled: true\n  sharding_ring:\n    kvstore:\n      store: memberlist\ndistributor:\n  pool:\n    health_check_ingesters: true\n  ring:\n    kvstore:\n      store: memberlist\n  shard_by_all_labels: true\nfrontend:\n  log_queries_longer_than: 10s\ningester:\n  lifecycler:\n    final_sleep: 0s\n    join_after: 0s\n    num_tokens: 512\n    ring:\n      kvstore:\n        store: memberlist\n      replication_factor: 1\n  max_transfer_retries: 0\ningester_client:\n  grpc_client_config:\n    max_recv_msg_size: 104857600\n    max_send_msg_size: 104857600\ninstrumentation:\n  distributor_client:\n    address: dns://\"{{ template \"enterprise-metrics.fullname\" . }}-distributor.{{\n      .Release.Namespace }}.svc:{{ .Values.config.server.grpc_listen_port }}\"\n  enabled: true\nlicense:\n  path: /license/license.jwt\nlimits:\n  enforce_metric_name: false\n  reject_old_samples: true\n  reject_old_samples_max_age: 168h\nmemberlist:\n  bind_port: 7946\nquerier:\n  active_query_tracker_dir: /data/enterprise-metrics/querier\n  query_ingesters_within: 12h\nquery_range:\n  align_queries_with_step: true\n  cache_results: true\n  results_cache:\n    cache:\n      memcached:\n        expiration: 1h\n      memcached_client:\n        timeout: 1s\n  split_queries_by_interval: 24h\nruler:\n  enable_alertmanager_discovery: false\n  enable_api: true\n  enable_sharding: true\n  ring:\n    kvstore:\n      store: memberlist\n  rule_path: /data\nruntime_config:\n  file: /var/enterprise-metrics/runtime.yaml\nserver:\n  grpc_listen_port: 9095\n  grpc_server_max_concurrent_streams: 1000\n  grpc_server_max_recv_msg_size: 104857600\n  grpc_server_max_send_msg_size: 104857600\n  http_listen_port: 8080\nstorage:\n  engine: blocks\nstore_gateway:\n  sharding_enabled: true\n  sharding_ring:\n    kvstore:\n      store: memberlist": parse error at (enterprise-metrics/templates/store-gateway-statefulset.yaml:52): unexpected unclosed action in command
```

**Comment by jdbaldry** [comment]
Hmm, thanks for taking a look. I think the nested templating to resolve the distributor address is being a nuisance and isn't caught by the CI because of the changes I have to make in order for it to run there. Let me take a look into this

**Comment by jdbaldry** [comment]
@simonswine I am unable to reproduce with Helm 3.6.1:
```console
$ helm version
version.BuildInfo{Version:"v3.6.1", GitCommit:"", GitTreeState:"", GoVersion:"go1.16.5"}
```

**Comment by jdbaldry** [comment]
I have a sense that it something to do with the use of variables in the values.yaml but I'll need to keep looking for confirmation of that. In the mean time, I'm force pushing a clean up of the instrumentation.distributor_client.address for readability.

**Review by chaudum — APPROVED** [review]
lgtm

**Pull request merged**
