### PR TITLE
[grafana] Added support for .spec.loadBalancerClass

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Issue #2717

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Sheikh-Abubaker 
Thanks for the contribution. Can you bump the version in Chart.yaml and fixing the lint-test error please?

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Thanks for the contribution. Can you bump the version in Chart.yaml and fixing the lint-test error please?

I did bumped the version from 6.61.1 to 6.61.2 but that doesn't seem to have any effect and also about the lint-test error can you please guide me how to fix that error

**Comment by zanhsieh** [comment]
> > @Sheikh-Abubaker Thanks for the contribution. Can you bump the version in Chart.yaml and fixing the lint-test error please?
> 
> I did bumped the version from 6.61.1 to 6.61.2 but that doesn't seem to have any effect and also about the lint-test error can you please guide me how to fix that error

Doesn't the github tell you what is the error if you scroll down?

https://github.com/grafana/helm-charts/pull/2730/files

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Doesn't the github tell you what is the error if you scroll down?
> 
> https://github.com/grafana/helm-charts/pull/2730/files

It does and I know the error is showing up due to the reason "[key-duplicates] duplication of key "type" in mapping" but my query is that we need to specify there config for two types of  services "ClusterIP" and "LoadBalancer" so how do I do it with using "type" key twice ?

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Doesn't the github tell you what is the error if you scroll down? Line 200 vs 211:
> 
> https://github.com/grafana/helm-charts/pull/2730/files

Hi @zanhsieh,

I have fixed the error please check if everything is upto the mark.

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh, in order to keep this PR up to date with main branch I push some latest changes but due to some reason the lint test failed in this [commit](https://github.com/grafana/helm-charts/pull/2730/commits/7d2a5151332780f1453241624bfb5d121383c869) to fix the lint error I committed again but this time using GUI and I think that was the mistake I made from that point no matter how many time ran rebase the DCO check kept failing so I think I should close this PR and open a fresh one

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh, please checkout this new [PR](https://github.com/grafana/helm-charts/pull/2743)

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Sheikh-Abubaker 
Can you sign DCO please?

https://github.com/grafana/helm-charts/pull/2730/checks?check_run_id=18089636060

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Can you sign DCO please?
> 
> https://github.com/grafana/helm-charts/pull/2730/checks?check_run_id=18089636060

@zanhsieh, Please check this new [PR](https://github.com/grafana/helm-charts/pull/2743), I have fixed errors and also signed the DCO it's all done

**Pull request closed without merging**
