### PR TITLE
[tempo-distributed] Add required name label to ingesters

### PR DESCRIPTION
**Pull request by alex5517**
`name` label is required on pods that should be managed by the rollout-operator this pr ensure that it is added.
https://github.com/grafana/rollout-operator/issues/15

### CODE REVIEW

**Comment by Sheikh-Abubaker** [comment]
@alex5517 is this PR intended for rollout-operator helm charts ?

**Comment by alex5517** [comment]
@Sheikh-Abubaker 

Sorry if the PR was a bit slim on information...

The PR is for the Tempo-Distributed chart. "Recently" the chart got support for deploying the the Tempo ingesters with zone awareness and to manage these new statefulsets it leverage the Grafana Rollout-Operator, but this is not working since the resulting pods from the statefulsets does not have the currently required `name` label.
The issue for removing this requirement was the link i referred to: https://github.com/grafana/rollout-operator/issues/15

**Review by mapno — APPROVED** [review]
LGTM

**Comment by Sheikh-Abubaker** [comment]
> The PR is for the Tempo-Distributed chart. "Recently" the chart got support for deploying the the Tempo ingesters with zone awareness and to manage these new statefulsets it leverage the Grafana Rollout-Operator, but this is not working since the resulting pods from the statefulsets does not have the currently required `name` label. The issue for removing this requirement was the link i referred to: [grafana/rollout-operator#15](https://github.com/grafana/rollout-operator/issues/15)

@alex5517 If I didn't get it wrong the scope of this change is to include `name` label within the ingester pods created when tempo-distributed chart is deployed ?

Like the ingester pods below right ?
```
$ kubectl get pods
NAME                                       READY   STATUS    RESTARTS        AGE 
my-tempo-compactor-56787b9bc7-bgpzp        1/1     Running   0               120m
my-tempo-distributor-588558c94b-xp2hg      1/1     Running   0               120m
my-tempo-ingester-0                        1/1     Running   0               120m
my-tempo-ingester-1                        1/1     Running   0               120m
my-tempo-ingester-2                        1/1     Running   0               120m
my-tempo-memcached-0                       1/1     Running   0               120m
my-tempo-querier-685bb964f4-p5d25          1/1     Running   0               120m
my-tempo-query-frontend-69958dcf44-qfgr8   1/1     Running   0               120m
```

**Comment by alex5517** [comment]
@Sheikh-Abubaker,

Yes that is correct, it is the same that is done with the Mimir-distributed chart.
https://github.com/grafana/mimir/blob/main/operations/helm/charts/mimir-distributed/templates/_helpers.tpl#L296

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM! Thanks for the contribution @alex5517, keep them coming!

**Pull request merged**
