### PR TITLE
[tempo-distributed] Upgrade to v2.6.0

### PR DESCRIPTION
**Pull request by mapno**
Upgrading to Tempo v2.6.0

Tempo v2.6.0 [Changelog](https://github.com/grafana/tempo/releases/tag/v2.6.0)

### CODE REVIEW

**Comment by emilrowland** [comment]
Will this PR add v2.6.0 to the helm chart or is this only for the pre-release?

**Comment by mapno** [comment]
> Will this PR add v2.6.0 to the helm chart or is this only for the pre-release?

Yes, this was a placeholder for when v2.6.0 was cut, which was yesterday.

**Comment by truongnht** [comment]
@mapno since v2.6.0 has been cut, let's bump tempo-distributed helm chart 🙏🏼

**Review by faustodavid — APPROVED** [review]
LGTM! :)

**Pull request merged**
