### PR TITLE
[tempo-distributed] Update distributor service to use enabled

### PR DESCRIPTION
**Pull request by AlexDHoffer**
Signed-off-by: AlexDHoffer <alexdchoffer@gmail.com>

Fixes https://github.com/grafana/helm-charts/issues/1393

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for the quick fix!

If you can bump the chart minor version and run
```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.8.1
```

we will merge

**Comment by ben-natan** [comment]
Oops I missed this when I made the change..
Can you also apply the same fix to `deployment-distributor.yaml` please?

**Comment by AlexDHoffer** [comment]
@ben-natan done

@joe-elliott Running that container gives me unexpected results - it modifies the README but removes the clause about upgrading from a chart version < 0.18.0

**Comment by joe-elliott** [comment]
I believe you need to edit the `README.md.gotmpl` file instead of the readme directly.

**Comment by AlexDHoffer** [comment]
I updated the gotmpl and ran the container again and the automated README update it is doing looks more sane now.

**Review by joe-elliott — COMMENTED** [review]
Nice fix. Thanks!

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
