### PR TITLE
[enterprise-logs] Bump GEL to version 1.4

### PR DESCRIPTION
**Pull request by trevorwhitney**
* bump GEL version to 1.4
* ~use `appVersion` from `Chart.yaml` as default image tag~ (couldn't find a way to template this into the `loki-distributed` sub chart)
* don't skip `enterprise-logs` tests on ci

### CODE REVIEW

**Comment by jdbaldry** [comment]
I think for testing to be effective in CI we will need to find a way to include a license secret or modify the behavior of the tokengen to make this work.

**Comment by trevorwhitney** [comment]
@jdbaldry I agree that would make testing more effective, however, even running the test as is without a license was useful as I detected a breaking config change in the default config.

**Comment by jdbaldry** [comment]
Oh I actually thought it wouldn't work without a license :) I'm glad to see that is not the case!

**Review by MichelHollands — APPROVED** [review]
LGTM

**Pull request merged**
