### PR TITLE
[tempo-distributed] fix: force nginx gateway to resolve upstream hostname

### PR DESCRIPTION
**Pull request by rsicart**
In order to force nginx to resolve hostnames in proxy_pass directive, we
need to set a variable and use it in proxy_pass. Otherswise nginx only
resolves hostnames at boot time.

### CODE REVIEW

**Review by Sheikh-Abubaker — COMMENTED** [review]
Hey there @rsicart, thanks for the contribution! have you tested these changes ?

**Comment by rsicart** [comment]
> Hey there @rsicart, thanks for the contribution! have you tested these changes ?

helm template is ok.

Installing the chart locally in a [kind](https://kind.sigs.k8s.io/) cluster works fine, nginx config syntax is ok and gateway is _Running_:

```
~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » helm upgrade --install tempo-distributed . --set gateway.nginxConfig.resolver=10.96.0.10
Release "tempo-distributed" does not exist. Installing it now.
NAME: tempo-distributed
LAST DEPLOYED: Thu Jul 25 17:29:02 2024
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
***********************************************************************
 Welcome to Grafana Loki
 Chart version: 0.79.0
 Loki version: 2.9.6
***********************************************************************

Installed components:
* gateway
* ingester
* distributor
* querier
* query-frontend

~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » kubectl get pods   
NAME                                                              READY   STATUS    RESTARTS   AGE
tempo-distributed-loki-distributed-distributor-7f587f7b9-tmf58    1/1     Running   0          61s
tempo-distributed-loki-distributed-gateway-674764559d-4s6q2       1/1     Running   0          61s
tempo-distributed-loki-distributed-ingester-0                     1/1     Running   0          61s
tempo-distributed-loki-distributed-querier-0                      1/1     Running   0          61s
tempo-distributed-loki-distributed-query-frontend-7d85cbffmz6ph   1/1     Running   0          61s

~/repos/github.com/rsicart/grafana-helm-charts/charts/loki-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » kubectl exec -ti tempo-distributed-loki-distributed-gateway-674764559d-4s6q2 -- nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
```

**Comment by rsicart** [comment]
> Hey there @rsicart, thanks for the contribution! have you tested these changes ?

helm template works correctly.

Installing the chart locally in a [kind](https://kind.sigs.k8s.io/) cluster works fine, gateway is Running and nginx config syntax is ok:

```
~/repos/github.com/rsicart/grafana-helm-charts/charts/tempo-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » helm upgrade --install tempo-distributed . --set gateway.enabled=true --set gateway.nginxConfig.resolver=10.96.0.10
Release "tempo-distributed" has been upgraded. Happy Helming!
NAME: tempo-distributed
LAST DEPLOYED: Thu Jul 25 17:41:50 2024
NAMESPACE: default
STATUS: deployed
REVISION: 2
TEST SUITE: None
NOTES:
***********************************************************************
 Welcome to Grafana Tempo
 Chart version: 1.13.3
 Tempo version: 2.5.0
***********************************************************************

Installed components:
* ingester
* distributor
* querier
* query-frontend
* compactor
* memcached
* gateway

~/repos/github.com/rsicart/grafana-helm-charts/charts/tempo-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » kubectl get pods                                                                                                   
NAME                                                READY   STATUS    RESTARTS   AGE
tempo-distributed-compactor-5d79c7bb84-vk6ld        1/1     Running   0          3m56s
tempo-distributed-distributor-5bbc4987bb-s2jvq      1/1     Running   0          3m56s
tempo-distributed-gateway-77fc9757d4-2gmd6          1/1     Running   0          65s
tempo-distributed-ingester-0                        1/1     Running   0          3m56s
tempo-distributed-ingester-1                        1/1     Running   0          3m56s
tempo-distributed-ingester-2                        1/1     Running   0          3m56s
tempo-distributed-memcached-0                       1/1     Running   0          3m56s
tempo-distributed-querier-77c846fffd-k89n4          1/1     Running   0          3m56s
tempo-distributed-query-frontend-557b864d98-gs6lf   1/1     Running   0          3m56s

~/repos/github.com/rsicart/grafana-helm-charts/charts/tempo-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » kubectl exec -ti tempo-distributed-gateway-77fc9757d4-2gmd6 -- nginx -t
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful

~/repos/github.com/rsicart/grafana-helm-charts/charts/tempo-distributed k8s:kind-kind:: ~ git:rsi/tempo-distributed-force-nginx-resolve-dns-proxy-pass » helm ls
NAME                    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
tempo-distributed       default         2               2024-07-25 17:41:50.286024148 +0200 CEST        deployed        tempo-distributed-1.13.3        2.5.0
```

**Review by Sheikh-Abubaker — COMMENTED** [review]
@rsicart Could you please fix the CI lint docs error ?

**Comment by rsicart** [comment]
Is it ok for you @Sheikh-Abubaker ?

**Review by Sheikh-Abubaker — COMMENTED** [review]
@rsicart It is okay, I am just in the last phase of testing, if everything goes well I'll approve it.

**Comment by Sheikh-Abubaker** [comment]
> helm template works correctly.
> Installing the chart locally in a [kind](https://kind.sigs.k8s.io/) cluster works fine, gateway is Running and nginx config syntax is ok:

@rsicart In the logs you provided you tested helm template, gateway and Nginx config which are up and running, but could you please explain how did you concluded that NGINX is now resolving hostnames without being restarted ? and correct me if I am wrong this PR is regarding Dynamic resolution right ? Incase any pods or service IP changes NGINX dynamically updates it ?

**Comment by Sheikh-Abubaker** [comment]
> Nginx open source works like this, the only way to force dns resolution at each request is by setting a variable and using it in proxy_pass.
> 
> If you do a git blame or git log to check gateway's nginx configuration history in this repository, you'll find that every time someone proposed the same change for other locations it's for the same reasons in this PR.

I meant to say if you have tested in a same scenario where before proposing these changes NGINX was failing dns resolution and after this change NGINX is successfully performing dns resolution ?

**Review by zanhsieh — APPROVED** [review]

**Review by Sheikh-Abubaker — APPROVED** [review]

**Comment by rsicart** [comment]
> > Nginx open source works like this, the only way to force dns resolution at each request is by setting a variable and using it in proxy_pass.
> > If you do a git blame or git log to check gateway's nginx configuration history in this repository, you'll find that every time someone proposed the same change for other locations it's for the same reasons in this PR.
> 
> I meant to say if you have tested in a same scenario where before proposing these changes NGINX was failing dns resolution and after this change NGINX is successfully performing dns resolution ?

Sorry, I misunderstood you question.

Yesterday I tried to reproduce the problem using kind, locally, without success.

Anyway, thanks for reviewing and for your reactivity!

**Comment by Sheikh-Abubaker** [comment]
> Yesterday I tried to reproduce the problem using kind, locally, without success.

Could you elaborate more ?

**Comment by rsicart** [comment]
> > Yesterday I tried to reproduce the problem using kind, locally, without success.
> 
> Could you elaborate more ?

I wanted to reproduce the problem before and after applying my changes, in order to verify that this PR fixes an issue.

For that, I deployed the latest release (the version before my PR) of this chart in my kind cluster, and tried to reproduce the DNS refresh problem, but I didn't find a way to do it.

I stopped my test because I wasn't able to validate the hypothesis.

**Comment by Sheikh-Abubaker** [comment]
> I wanted to reproduce the problem before and after applying my changes, in order to verify that this PR fixes an issue.
> 
> For that, I deployed the latest release (the version before my PR) of this chart in my kind cluster, and tried to reproduce the DNS refresh problem, but I didn't find a way to do it.
> 
> I stopped my test because I wasn't able to validate the hypothesis.

@rsicart The reason you weren't able to validate this due to that fact that we have NGINX+K8S, Dynamic hostname resolution comes out of the box due to k8s dns which means even without this PR dynamic resolution is taken care by K8S already, but I think it'd be better as it enhances the NGINX config even more.

**Pull request merged**
