### PR TITLE
[mimir-distributed] Add HPA to Alertmanager, Ingester, Distributor

### PR DESCRIPTION
**Pull request by bueti**
First time contributing to this Helm repo. I tried to follow the existing patterns and add it backwards compatible, HPA is disabled by default.

Signed-off-by: Benjamin Buetikofer <benjamin.buetikofer@ricardo.ch>

### CODE REVIEW

**Comment by bueti** [comment]
@ Grafana: What do you require to continue with this PR?

**Comment by SamuelBagattin** [comment]
@bueti Why don't you include HPAs for others mimir components ?
Would this be a bad practice to autoscale querier, query-frontend, etc... ? Or is this something to do ?

**Comment by bueti** [comment]
> [CLA assistant check](https://cla-assistant.io/grafana/helm-charts?pullRequest=1342) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/helm-charts?pullRequest=1342) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/helm-charts?pullRequest=1342) it.

I guess this is a new requirement? It doesn't seem quite ready yet (rate limit exceeded): 
image

**Comment by zanhsieh** [comment]
mimir-distributed has been [moved](https://github.com/grafana/mimir/tree/main/operations/helm/charts/mimir-distributed).

**Comment by bueti** [comment]
well, i guess it was worth a try.

**Pull request closed without merging**
