### PR TITLE
[tempo] Add overrides to Tempo

### PR DESCRIPTION
**Pull request by gabrieloandco**
We needed to add overrides to Tempo to change some configurations.

### CODE REVIEW

**Review by annanay25 — COMMENTED** [review]
Thanks, the PR will need a helm charts version bump. 

Also can you please fix the docs with
```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

**Comment by gabrieloandco** [comment]
> Thanks, the PR will need a helm charts version bump.
> 
> Also can you please fix the docs with
> 
> ```
> docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
> ```

Done fixing the docs. I am not sure if the version requires a bump since the PR is very recent.

**Comment by annanay25** [comment]
Oh, no every change requires a bump so the latest changes will be available with the next release
https://github.com/grafana/helm-charts/runs/4394359506?check_suite_focus=true

**Comment by gabrieloandco** [comment]
> Oh, no every change requires a bump so the latest changes will be available with the next release https://github.com/grafana/helm-charts/runs/4394359506?check_suite_focus=true

bumped to 0.12.1 is that right?

**Comment by annanay25** [comment]
Thanks for your patience @gabrieloandco. You will have to run the docs update again after updating the version number. 

```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

And also Ci requires that you sign the commits.

**Comment by annanay25** [comment]
I've opened a new PR with the required changes as we were going back and forth a bit. Your commits have been squashed and signed. Let me know if that works!

**Comment by gabrieloandco** [comment]
> I've opened a new PR with the required changes as we were going back and forth a bit. Your commits have been squashed and signed. Let me know if that works!

Yes that would be perfect, sorry for the inconveniences first PR I do on this project.

**Comment by annanay25** [comment]
No worries, its all good. :)

In general I would recommend looking at the CI failures and working backwards to figure out what needs to be fixed.

Thanks for your contribution!

**Pull request closed without merging**
