### PR TITLE
[tempo-distributed] Fix Ingester config variables

### PR DESCRIPTION
**Pull request by faustodavid**
The Ingester config values for maxBlockBytes, maxBlockDuration, and completeBlockTimeout didn't match in the config template.

```
    ingester:
      lifecycler:
        ring:
          replication_factor: 1
          kvstore:
            store: memberlist
        tokens_file_path: /var/tempo/tokens.json
      {{- if .Values.ingester.config.maxBlockBytes }}
      max_block_bytes: {{ .Values.ingester.config.maxBlockBytes }}
      {{- end }}
      {{- if .Values.ingester.config.maxBlockDuration }}
      max_block_duration: {{ .Values.ingester.config.maxBlockDuration }}
      {{- end }}
      {{- if .Values.ingester.config.completeBlockTimeout }}
      complete_block_timeout: {{ .Values.ingester.config.completeBlockTimeout }}
```

### CODE REVIEW

**Review by annanay25 — COMMENTED** [review]
Thanks for your changes @faustodavid. We would need an update to the chart version. And also please run

```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

From the root of the repo to format docs!

**Comment by faustodavid** [comment]
> Thanks for your changes @faustodavid. We would need an update to the chart version. And also please run
> 
> ```
> docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
> ```
> 
> From the root of the repo to format docs!

Thanks @annanay25, done.

**Review by annanay25 — COMMENTED** [review]
Oof. I had no idea it would make all these changes in other directories. Can we only add `tempo-distributed` changes to this PR

**Comment by faustodavid** [comment]
Hey @annanay25 I updated just tempo-distributed docs, but I see a lot of changes in the docs, not sure if this is correct.

**Pull request closed without merging**
