### PR TITLE
[tempo-distributed] Add Sheikh-Abubaker as maintainer

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
I've contributed several times to this [repository](https://github.com/grafana/helm-charts/pulls?q=is%3Apr+author%3ASheikh-Abubaker), [loki](https://github.com/grafana/loki/pulls?q=is%3Apr+author%3ASheikh-Abubaker) and [Prometheus-community](https://github.com/prometheus-community/helm-charts/pulls?q=is%3Apr+author%3ASheikh-Abubaker), so I am familiar with helm charts and if possible I'd like to step up and help in maintaining helm charts in this repo,

Though most of my contributions lie in tempo-distributed and promtail but since promtail is a feature complete, I'm considering  tempo-distributed, tempo and grafana.

 what do you think @zanhsieh @jkroepke @zalegrala @Xtigyro ?

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by zalegrala** [comment]
cc @faustodavid @BitProcessor @swartz-k @mapno for review.

**Comment by faustodavid** [comment]
hey @Sheikh-Abubaker can you please update the branch?

**Comment by Sheikh-Abubaker** [comment]
> hey @Sheikh-Abubaker can you please update the branch?

Yeah sure, just a min!

**Review by faustodavid — APPROVED** [review]
LGTM, Welcome @Sheikh-Abubaker!

**Comment by Sheikh-Abubaker** [comment]
> LGTM, Welcome @Sheikh-Abubaker!

Thank you!! @faustodavid

**Comment by Sheikh-Abubaker** [comment]
@zalegrala Thank you for inviting!! just wanted to know if I could be invited as a member ?

**Comment by Sheikh-Abubaker** [comment]
> Ping me on the community slack if you want to chat more about it.

Yeah sure! please checkout your slack

**Pull request merged**
