### PR TITLE
[grafana] use sh -x for download script

### LINKED ISSUE #530: grafana init container download-dashboards can hang/fail silently / no logs
The command 

charts/grafana/templates/_pod.tpl:    args: [ "-c", "mkdir -p /var/lib/grafana/dashboards/default && /bin/sh /etc/grafana/download_dashboards.sh" ]

is ran without -x so when it hangs there is no trace as to why/why step

### PR DESCRIPTION
**Pull request by ldemailly**
Fixes #530

### CODE REVIEW

**Comment by torstenwalter** [comment]
@ldemailly you need to sign you commits. See https://github.com/grafana/helm-charts/pull/531/checks?check_run_id=2933539546
For every change of a chart you also need to increase it's version number in Chart.yaml

**Comment by ldemailly** [comment]
I did make the signed-off change - for the version I was thinking it would just go/get batched with some other more significant change? but if you want I can change it

**Comment by zanhsieh** [comment]
@ldemailly 
Could you bump the chart version to latest? Without it, this PR won't pass the link-test and cannot be merged.

**Comment by ldemailly** [comment]
@zanhsieh done, I think (sorry I'm not familiar with your repo's setup nor its CI)

let me know if you meant something else (like rebase)

**Comment by ldemailly** [comment]
having a few issues ... with sign off etc ... let me either fix this quickly or redo the mr

**Comment by ldemailly** [comment]
I failed at edit in place, so closing for #532

**Pull request closed without merging**
