### PR TITLE
[loki-simple-scalable] Fix metric duplication of headless service

### PR DESCRIPTION
**Pull request by wappam**
Add bool label on write/read headless service-read-headless
Add matchExpressions selector on the write/read servicemonitor

Fix for #1237 

Signed-off-by: Hugues Gosselin <hugues.gosselin@ubisoft.com>

### CODE REVIEW

**Comment by wappam** [comment]
Its technically the same code as in https://github.com/grafana/helm-charts/pull/1159

**Review by trevorwhitney — APPROVED** [review]
Thank you! LGTM

**Comment by aservedio** [comment]
Hello! Any updates on this? would be nice!! :P

**Comment by trevorwhitney** [comment]
I didn't realize a maintainer had to approve the CI run since this is @wappam's first contribution, sorry about that! Looks like we just need a version bump to get this merged.

**Comment by wappam** [comment]
I just commited a bump of the chart version to 1.2.0.

**Pull request merged**
