### PR TITLE
[grafana] Update Grafana to 10.2.0

### PR DESCRIPTION
**Pull request by akselleirv**

### CODE REVIEW

**Comment by venkatamutyala** [comment]
I'm not sure how common this situation is but my team and I just tested an upgrade to 10.2.0 using the kube prometheus stack and found blocking bugs for our use case and rolled back to 10.1.5. I have a feeling this 10.2.0 is a version that folks should skip entirely: 
https://github.com/grafana/grafana/issues?q=is%3Aissue+is%3Aopen+10.2.0

A link to the issue I opened: https://github.com/grafana/grafana/issues/77211

Hope this helps!

**Comment by akselleirv** [comment]
Why did you close the PR @zanhsieh ?

**Comment by lynkz-matt-psaltis** [comment]
Would also love to have an explanation why this was closed @zanhsieh - It's pretty confusing to deploy a helm chart with an app version of 10.1.5 and then override it with an image tag of 10.2 could you please elaborate? Will there be no further updates to the helm chart in terms of app versions?

**Comment by nourspace** [comment]
@lynkz-matt-psaltis, the elaboration is in the above comment.
https://github.com/grafana/grafana/issues/77082#issuecomment-1782533763 says
> Looks like this fix will be a part of the next 10.2.x patch release (which should be 10.2.1) :)

The fix release is already out.
https://github.com/grafana/grafana/releases/tag/v10.2.1

**Pull request closed without merging**
