### PR TITLE
[tempo] feat: add readiness and liveness probe

### LINKED ISSUE #3185: [Tempo] Add Readiness and Liveness Probe Configuration Options to Tempo Helm Chart
The Grafana Tempo Helm chart(https://github.com/grafana/helm-charts/tree/main/charts/tempo) currently lacks the ability to configure readiness and liveness probes. These probes are essential for monitoring and ensuring the health and availability of the Tempo service in a Kubernetes environment. Without these probes, users have to manually modify the Helm chart templates to include this critical functionality.

Proposed Solution:

Add configurable options for readiness and liveness probes in the values.yaml file of the Tempo Helm chart. This will allow users to define their own probe configurations without needing to alter the chart templates directly. The configuration should include parameters such as initialDelaySeconds, periodSeconds, timeoutSeconds, failureThreshold, and successThreshold.

Example Configuration:
```
...
tempo:
  server:
    http_listen_port: 3100

  livenessProbe:
    httpGet:
      path: /metrics
      port: 3100
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  readinessProbe:
    httpGet:
      path: /metrics
      port: 3100
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
....
```
note that the "statefulset.yaml" also need to be updated

Benefits:

Improved  reliability of Tempo pods.
Simplified customization of health checks.
Enhanced user experience by reducing the need for manual chart modifications.
Steps to Reproduce:

Deploy the current Grafana Tempo Helm chart.
Observe the absence of readiness and liveness probe configurations in the values.yaml file.
Expected Outcome:

The Helm chart should provide out-of-the-box support for configuring readiness and liveness probes via the values.yaml file.

### PR DESCRIPTION
**Pull request by Mistral-valaise**
this change resolves #3185 by adding readiness and liveness probe configuration options to tempo helm chart

### CODE REVIEW

**Comment by Mistral-valaise** [comment]
i did it more than 5 months ago but unfortunately it was not reviewed. i will update the branch and validate all again

**Comment by joe-elliott** [comment]
thx for the PR! can you review the linting issues?

**Comment by Mistral-valaise** [comment]
i made the last 2 commits without signoff, since i had merged the main branch to mine afterwards, i have difficulties to validate DCO afterwards.
I could continue working on it during the weekend.
Can I create a new branch and do it again?

**Comment by Sheikh-Abubaker** [comment]
> i made the last 2 commits without signoff, since i had merged the main branch to mine afterwards, i have difficulties to validate DCO afterwards. I could continue working on it during the weekend. Can I create a new branch and do it again?

Sure! you could open a new fresh PR.

**Comment by Mistral-valaise** [comment]
After reviewing the Grafana Tempo documentation (https://grafana.com/docs/tempo/latest/api_docs/#readiness-probe), I found that the /ready endpoint is available for readiness probes. However, there isn’t a specific endpoint designated for liveness probes. To address this, I propose using the /ready endpoint for the readiness probe and the /metrics endpoint for the liveness probe. Could you please share your thoughts on this approach?
Thank you for your consideration.
e.g
livenessProbe:
  httpGet:
    path: /metrics
    port: 3100
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /ready
    port: 3100
  initialDelaySeconds: 5
  periodSeconds: 10

**Comment by Mistral-valaise** [comment]
here is my new PR https://github.com/grafana/helm-charts/pull/3489

**Pull request closed without merging**
