### PR TITLE
[tempo] specify grpc appProtocol for tempo service

### PR DESCRIPTION
**Pull request by walkafwalka**
Istio uses port name prefixes or `appProtocol` to determine the protocol.
Currently, the names have the protocol as a suffix, but using appProtocol felt like a smaller change.

Relates to https://github.com/grafana/helm-charts/issues/104.

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for the contribution. Looks like you need to bump the chart version and run helm-docs:

```
docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

One question. What versions of k8s supports this field? Will this cut off users on earlier versions?

**Comment by walkafwalka** [comment]
> One question. What versions of k8s supports this field? Will this cut off users on earlier versions?

`appProtocol` was introduced in Kubernetes version 1.18. As an alternative, we could prefix port names with `grpc` instead of as a suffix.

**Comment by walkafwalka** [comment]
> Add the prefix like you're suggesting

I went with the prefix for simplicity.

**Review by joe-elliott — APPROVED** [review]
Thanks for the improvement!

**Comment by kmai** [comment]
@joe-elliott this wasn't merged onto `tempo-distributed`, right?

**Pull request merged**
