### PR TITLE
[grafana] Fix initContainers when initDatasources provided

### PR DESCRIPTION
**Pull request by transkonduktor**
#1135 
Signed-off-by: Krzyszof Dziegielewski <dziegielewski.krzysztof@gmail.com>

### CODE REVIEW

**Comment by zanhsieh** [comment]
@transkonduktor 
Could you bump the chart version to latest?

**Comment by transkonduktor** [comment]
@zanhsieh 
done

**Comment by transkonduktor** [comment]
> Could you bump the chart version to latest?

@zanhsieh 
done

**Comment by zanhsieh** [comment]
@transkonduktor 
Could you sign DCO again?

**Comment by transkonduktor** [comment]
@zanhsieh 
done

**Comment by zanhsieh** [comment]
@transkonduktor 
I don't see DCO got signed. Please refer to link next to DCO (Details next to DCO) on the bottom of this PR page

**Comment by transkonduktor** [comment]
@zanhsieh no idea how to fix that, because I created empty commit with signoff parameter and I don't have time to fix that now, so it was quicker to create new branch and make changes once again.

I created new PR, this one can be removed 

#1158

**Pull request closed without merging**
