### PR TITLE
[tempo-distributed] allow configuration of the Kafka receiver

### PR DESCRIPTION
**Pull request by jleloup**
I would like to be able to configure a Kafka receiver in Grafana Tempo.

To do so I propose to use a set of values in the current `traces` map & include it in the overall `config` value.

While this approach helps to configure all possible Kafka parameters without duplicating them as Helm values, it breaks consistency with other receivers which are boolean only.

### CODE REVIEW

**Comment by joe-elliott** [comment]
Yeah, I don't know why the other receivers are just true/false. I much prefer this way. Let's get the conflicts cleaned up and we'll merge.

**Review by joe-elliott — DISMISSED** [review]

**Review by annanay25 — COMMENTED** [review]
@jleloup some other PRs were merged recently and are now conflicting with these changes. Please resolve and we will merge!

**Comment by jleloup** [comment]
> @jleloup some other PRs were merged recently and are now conflicting with these changes. Please resolve and we will merge!

Sure thing, I have resolved those conflicts. I think it is now up to date.

**Review by mapno — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
