### PR TITLE
[loki-distributed] memcache service port name update

### PR DESCRIPTION
**Pull request by ceastman-r7**
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/#explicit-protocol-selection

This will update the memcached helm charts so the services that are created will be Istio compliant

For Istio compliance kubernetes service port names need to follow the correct naming convention.

### CODE REVIEW

**Comment by ceastman-r7** [comment]
For instance the current chart values cause this error in the istio-proxy container:

{"upstream_host":null,"authority":null,"downstream_remote_address":"10.0.15.169:50102","upstream_local_address":null,"x_forwarded_for":null,"user_agent":null,"request_id":null,"protocol":"HTTP/1.1","downstream_local_address":"10.0.15.1:11211","upstream_transport_failure_reason":null,"path":null,"requested_server_name":null,"response_flags":"DPE","request_duration":null,"connection_termination_details":null,"response_code_details":"http1.codec_error","start_time":"2022-09-01T21:20:22.583Z","response_duration":null,"response_code":400,"response_tx_duration":null,"bytes_received":0,"upstream_cluster":null,"method":null,"bytes_sent":11,"duration":0}

**Comment by zanhsieh** [comment]
@ceastman-r7 
Could you sign DCO please?

**Comment by ceastman-r7** [comment]
@zanhsieh DCO Signed and CLA agreement are done.

**Review by zanhsieh — APPROVED** [review]

**Comment by hgranillo** [comment]
This change should have been flagged as a potentially breaking change. Changing port names will mess with Loki memcached_client service discovery.

As per Loki documentation:
`# Configures how to connect to one or more memcached servers.
memcached_client:
  # The hostname to use for memcached services when caching chunks. If
  # empty, no memcached will be used. A SRV lookup will be used.
  # CLI flag: -<prefix>.memcached.hostname
  [host: <string>]

  # SRV service used to discover memcached servers.
  # CLI flag: -<prefix>.memcached.service
  [service: <string> | default = "memcached"]`

If you had something like this in your memcached_client configuration:

```
            memcached_client:
              consistent_hash: true
              host: {{ include "loki.memcachedIndexQueriesFullname" . }}
              service: http
```
Means that your memcached are no longer discoverable by loki leading to errors like:

```
level=error ts=2022-10-05T10:43:21.747611638Z caller=memcached.go:144 org_id=fake msg="Failed to get keys from memcached" keysrequested=1 err="memcache: no servers configured or available"
	
level=warn ts=2022-10-05T10:43:05.831170768Z caller=memcached_client.go:228 msg="error updating memcache servers" err="lookup _http._tcp.loki-loki-distributed-memcached-chunks on 172.20.0.10:53: no such host"
```

**Pull request merged**
