### PR TITLE
[grafana] add support for dual stack clusters

### PR DESCRIPTION
**Pull request by M0NsTeRRR**

### CODE REVIEW

**Comment by M0NsTeRRR** [comment]
I would like to create some PR on others charts I use but others charts have multiple services. Do I need to create a global configuration to enable dual stack or I add one configuration per service ?
Regards,

**Comment by M0NsTeRRR** [comment]
Hello,
I noticed, @zanhsieh, that you merged something into my branch. Is there anything I need to do on my end to facilitate a review for my PR and get it merged ?
Regards,

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@M0NsTeRRR This repo required **_2_** approvals. I only can help one.

**Comment by M0NsTeRRR** [comment]
No worries, thank you for your review. I hope it gets merged soon :)

**Comment by M0NsTeRRR** [comment]
Hello @jrockway,

Sorry to trap you like this, but is it possible to get the last approval needed for this little PR? 👀

**Comment by M0NsTeRRR** [comment]
Hello @jkroepke,

Sorry to trap you like this, but is it possible to get the last approval needed for this little PR? 👀

**Comment by jkroepke** [comment]
Hey @M0NsTeRRR 

thanks for the poke here to review my first PR. I could remember that you also contribute that feature to kube-prometheus-stack.

https://github.com/prometheus-community/helm-charts/pull/4472

On KPS, you apply a different semantic and I would like to know, if you want to unify them?

**Comment by M0NsTeRRR** [comment]
> Hey @M0NsTeRRR
> 
> thanks for the poke here to review my first PR. I could remember that you also contribute that feature to kube-prometheus-stack.
> 
> [prometheus-community/helm-charts#4472](https://github.com/prometheus-community/helm-charts/pull/4472)
> 
> On KPS, you apply a different semantic and I would like to know, if you want to unify them? Or is there an reason for a different scheme?

Hey,

Thanks for your quick answer, yes it was me :)

In the first PR I did on KPS https://github.com/prometheus-community/helm-charts/pull/4424, I used the same implementation as this one. However, a maintainer asked me to follow the implementation from other charts in KPS repository, so I did.

I prefer my implementation over KPS. As a Kubernetes user, it is easier to find attributes if they are Kubernetes attributes (when you can). This is the approach I took on other charts I've contributed to (External Secret Operator, Cert Manager, K8up, CNPG, etc.).

**Comment by jkroepke** [comment]
>  This is the approach I took on other charts I've contributed to (External Secret Operator, Cert Manager, K8up, CNPG, etc.).

Great! That's a valid reason. I just like consistency.

**Review by jkroepke — APPROVED** [review]

**Pull request merged**
