### PR TITLE
[tempo-distributed] Add a comment about enabling metrics generator processors in helm chart

### PR DESCRIPTION
**Pull request by Davenury**
PR enhancing information about metrics generators and enablement of the processors, according to [slack thread](https://grafana.slack.com/archives/C01D981PEE5/p1700053533544369) and various people encountering this misunderstanding.

### CODE REVIEW

**Comment by zalegrala** [comment]
Thanks for the PR.  The linter is quite specific, take a look at the CI and let us know when you're ready for another review.

**Comment by Davenury** [comment]
@zalegrala I think it should be fine now (can you point a link to docs with how to setup linter locally - config is passed through env variable, so I wasn't able to reproduce the steps)?

**Comment by zalegrala** [comment]
I think the lint is complaining about whitespace this time.

**Comment by Davenury** [comment]
> I think the lint is complaining about whitespace this time.

I must have not regenerate docs, sorry

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
