### PR TITLE
[loki-stack] Loki 2.2.0

### PR DESCRIPTION
**Pull request by slim-bean**
Signed-off-by: Edward Welch <edward.welch@grafana.com>

### CODE REVIEW

**Comment by ncolboc** [comment]
@slim-bean
Hello, It would be great to merge this PR as currently loki-stack latest chart version still reference old loki package 2.1.0.
Do you have any idea why test step has failed?

**Comment by fasmat** [comment]
Pump for visibility. We would also like to use a more recent version of Loki with your helm chart. Any ETA for this feature?

**Comment by Nexus2k** [comment]
+1 we currently experience crash looping promtail pods due to the old Loki version...

**Comment by onedr0p** [comment]
> +1 we currently experience crash looping promtail pods due to the old Loki version...

I would advise to use the separate Loki and promtail chart. There's little actively it seems on most of the PRs in this repo unfortunately.

**Comment by Nexus2k** [comment]
> > +1 we currently experience crash looping promtail pods due to the old Loki version...
> 
> I would advise to use the separate Loki and promtail chart. There's little actively it seems on most of the PRs in this repo unfortunately.

That's indeed what we ended up doing and it fixed the issue.

**Pull request closed without merging**
