### PR TITLE
[loki] Fix typo

### PR DESCRIPTION
**Pull request by josephshanak**

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@josephshanak 
Thank you for the contribution. Could you bump the version in Chart.yaml and sign DCO please?

**Comment by josephshanak** [comment]
> @josephshanak Thank you for the contribution. Could you bump the version in Chart.yaml and sign DCO please?

I don't think there is a relevant Chart.yaml in this case, unless I'm missing something.

**Comment by zanhsieh** [comment]
> 

@josephshanak 
Any change shall bump the version in Chart.yaml, otherwise the CI won't let it pass.

**Comment by nchal** [comment]
I was looking for fixing this typo and I saw this PR.  
And like @josephshanak, I don't see any Chart.yml to change in this particular folder, it's just a README indicate that grafana/loki has moved location

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
