### PR TITLE
[tempo] make tempo automountServiceAccountToken configurable

### PR DESCRIPTION
**Pull request by gerhard-strauss-jambit**
just a simple change to make tempo automountServiceAccountToken configurable

### CODE REVIEW

**Comment by BitProcessor** [comment]
Thanks for your contribution, a few questions/remarks:

* What would be the use case? 
* Why are you setting it both on serviceaccount and pod level? See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
* please change the title of the PR and add the correct prefix

**Comment by gerhard-strauss-jambit** [comment]
> * What would be the use case?
> * Why are you setting it both on serviceaccount and pod level? See: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
I know that its kinda redundant, but it also doesnt hurt. We have a Policy in our Kubernetes Clusters active, that requires the automountServiceAccountToken on Pod Level and we cant influence this. To Deploy this Chart we need this Setting.

> * please change the title of the PR and add the correct prefix
Done

**Comment by BitProcessor** [comment]
Thanks for your feedback. Please also update the helm-docs.

**Comment by gerhard-strauss-jambit** [comment]
> Thanks for your feedback. Please also update the helm-docs.

done

**Comment by BitProcessor** [comment]
It seems your helm-docs ran all over the place ;) 
Can you remove the changes in this file?

Screenshot 2022-09-09 at 13 22 22

**Comment by gerhard-strauss-jambit** [comment]
> It seems your helm-docs ran all over the place ;) Can you remove the changes in this file?
> 
> Screenshot 2022-09-09 at 13 22 22

yes, sorry for that.
done

**Review by zanhsieh — APPROVED** [review]

**Comment by gerhard-strauss-jambit** [comment]
@zanhsieh can you merge?

**Pull request merged**
