### PR TITLE
[loki-distributed] Allow maxUnavailable to be set as 0

### PR DESCRIPTION
**Pull request by siryur**
Fixes: #2848

Whenever the PDB maxUnavailable is set to 0, the following condition fails (i.e. for indexGateway):
```
{{- if not .Values.indexGateway.maxUnavailable }}
```

---

To fix it, I used [one of the solutions](https://github.com/helm/helm/issues/3164#issuecomment-709537506) given by the helm issue that seems to be backwards compatible.

Note: I believe this issue might be happening in more implementations of this chart or other charts.

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@siryur 
Can you sign DCO and bump the version in Chart.yaml please?

**Comment by siryur** [comment]
Should be ready now @zanhsieh

**Review by zanhsieh — APPROVED** [review]

**Comment by siryur** [comment]
@unguiculus and @Whyeasy can we get this merged?

**Comment by zanhsieh** [comment]
@zalegrala 
Can you review this? Rest of maintainers are not active regularly.

**Review by zalegrala — APPROVED** [review]

**Pull request merged**
