### PR TITLE
[tempo] update to v2.6.0

### PR DESCRIPTION
**Pull request by portswigger-tim**
Update Tempo to version 2.6.0 in the simple tempo Helm chart.

### CODE REVIEW

**Comment by portswigger-tim** [comment]
Doesn't quite work as expected. Investigating...

**Comment by portswigger-tim** [comment]
Seeing: `failed to get trace with id: <trace-id> Status: 404 Not Found Body:` since updating to 2.6.0. Refreshing a lot can occasionally get a result back so I'm guessing that blocks aren't being replicated around or something 🤷  - will ask about in the main Tempo repo or in Slack.

**Comment by Sheikh-Abubaker** [comment]
> Seeing: `failed to get trace with id: <trace-id> Status: 404 Not Found Body:` since updating to 2.6.0. Refreshing a lot can occasionally get a result back so I'm guessing that blocks aren't being replicated around or something 🤷 - will ask about in the main Tempo repo or in Slack.

any updates on this ?

**Comment by portswigger-tim** [comment]
I think it is as a result of the chart not setting up the querer/ingestor rings when deploying > 1 replica so instances of tempo are not aware of each other.

**Pull request closed without merging**
