### PR TITLE
[agent-operator] fixed Helm chart should template namespace Signed-off-by: Sheikh-Abubaker <sheikhabubaker761@gmail.com>

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Implemented the solution as asked in grafana loki issue: https://github.com/grafana/loki/issues/8044

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Sheikh-Abubaker 
Can you bump the version in Chart.yaml please?

**Comment by Sheikh-Abubaker** [comment]
yeah sure.

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh,

I have updated the version please check it out.

**Comment by Sheikh-Abubaker** [comment]
Hi @zanhsieh,

I updated the chart version and also included the signed off message in commit, I don't get it now why DCO is failing ?

**Comment by zanhsieh** [comment]
> Hi @zanhsieh,
> 
> I updated the chart version and also included the signed off message in commit, I don't get it now why DCO is failing ?

The `Details` next to DCO explains why and the solution:

https://github.com/grafana/helm-charts/pull/2697/checks?check_run_id=17627737798

**Comment by Sheikh-Abubaker** [comment]
Hi @zanhsieh,

I have resolved the DCO check failure, please check it out.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
