### PR TITLE
[grafana] Add value for pod.spec.automountServiceAccountToken

### PR DESCRIPTION
**Pull request by jkroepke**
fixes https://github.com/grafana/helm-charts/issues/2986
fixes https://github.com/grafana/helm-charts/pull/2987

### CODE REVIEW

**Review by Footur — APPROVED** [review]

**Comment by zanhsieh** [comment]
@Xtigyro @zalegrala Can you review this PR please?

**Comment by philipfreude** [comment]
This PR appears to be pretty incomplete. The [old config value](https://github.com/grafana/helm-charts/blob/df7ae36c21bce12712c04a91115c165a04b7cdbf/charts/grafana/values.yaml#L44) was not removed and the [README.md](https://github.com/grafana/helm-charts/blob/df7ae36c21bce12712c04a91115c165a04b7cdbf/charts/grafana/README.md?plain=1#L226) was not updated.

**Comment by jkroepke** [comment]
> The [old config value](https://github.com/grafana/helm-charts/blob/df7ae36c21bce12712c04a91115c165a04b7cdbf/charts/grafana/values.yaml#L44) was not removed

The old config value you mention isn't old and still used inside the ServiceAccount configuration.

**Comment by philipfreude** [comment]
Could you please point me to the location where `serviceAccount.autoMount` is being used? I cannot find it 😕

**Comment by jkroepke** [comment]
> Could you please point me to the location where `serviceAccount.autoMount` is being used? I cannot find it 😕

I would appreciate an review from you in #2997, it it meets your expectation. Thanks!

**Pull request merged**
