### PR TITLE
[grafana] feat(network policy): extend Ingress

### PR DESCRIPTION
**Pull request by C4tWithShell**
Add extraIngress parameter to network policy since it does not allow to specify additional sources from the grafana helm chart . For example, I can not set up  load balancer in the cluster.

### CODE REVIEW

**Comment by C4tWithShell** [comment]
@Sheikh-Abubaker @jkatsos @maorfr @torstenwalter @Xtigyro  @zanhsieh 
Appreciate if able to review the PR when available, thanks!

**Review by zanhsieh — APPROVED** [review]

**Review by Sheikh-Abubaker — COMMENTED** [review]
@C4tWithShell Have you tested the proposed solution ?

**Comment by C4tWithShell** [comment]
> @C4tWithShell Thanks for the Contribution! Have you tested the proposed solution ?

Yes, I did

**Comment by Sheikh-Abubaker** [comment]
@C4tWithShell If I didn't get you wrong in the `extraIngress` comments, you've illustrated an example of accepting traffic from NGINX right by setting appropriate `matchLabels` ? in order to use to different ingress sources right ?

**Comment by Sheikh-Abubaker** [comment]
I believe we could achieve the same result, by adding the appropriate labels in the existing `networkpolicy.yaml` right here: https://github.com/grafana/helm-charts/blob/e930987a79ef7656b10bcd3883b285d6e726121c/charts/grafana/templates/networkpolicy.yaml#L49

I'd recommend you to try and test the existing `networkpolicy.yaml` utilizing the above feature and I believe it would help you to achieve the same result as `extraIngress`.

Incase you want to accept traffic from some different namespace, you could utilize the `explicitNamespaceSelector` feature for that:
https://github.com/grafana/helm-charts/blob/e930987a79ef7656b10bcd3883b285d6e726121c/charts/grafana/values.yaml#L1326

**Comment by Sheikh-Abubaker** [comment]
@C4tWithShell any updates on this one ?

**Comment by C4tWithShell** [comment]
> @C4tWithShell any updates on this one ?

Hi! Yes, I was able to configure ingress network policy with adding the addition label to ingress-nginx pod. 
Even though I think it is a little bit confusing to set up network policy indirectly

**Comment by Sheikh-Abubaker** [comment]
> > @C4tWithShell any updates on this one ?
> 
> Hi! Yes, I was able to configure ingress network policy with adding the addition label to ingress-nginx pod.

You mean by the existing Network Policy right ?

**Comment by C4tWithShell** [comment]
> > > @C4tWithShell any updates on this one ?
> > 
> > 
> > Hi! Yes, I was able to configure ingress network policy with adding the addition label to ingress-nginx pod.
> 
> You mean by the existing Network Policy right ?

Yes. By adding the grafana-client label

**Comment by Sheikh-Abubaker** [comment]
> Yes. By adding the grafana-client label

All right! shall I close this one then ?

**Pull request closed without merging**
