### PR TITLE
[loki-distributed] Provide loki configuration as object

### PR DESCRIPTION
**Pull request by dbluxo**
Closes https://github.com/grafana/helm-charts/issues/433

### CODE REVIEW

**Comment by stevehipwell** [comment]
@dbluxo could you also convert the `affinity` values into objects instead of strings?

**Review by unguiculus — COMMENTED** [review]
I don't think we should change this. It has been designed like this on purpose. Converting the config object YAML for templating has its limitations. You will only be able to template values in the YAML that are strings because you need to quote template expressions. You wouldn't be able to template ports anymore, for example. Also, it would be a breaking change that breaks existing installation that rely on this.
Furthermore, with the existing solution you can externalize the config as YAML file using `--set-file`, which would no longer work.

**Comment by stevehipwell** [comment]
I've just come to the same conclusion today @unguiculus.

**Comment by Whyeasy** [comment]
Can we close this PR if we are not going to change it?

**Pull request closed without merging**
