### PR TITLE
[grafana] Added support for loadBalancerClass

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Issue #2717 

Hi @zanhsieh,

Please look into this PR if I have got it right this time, I just went through the issue again and understood the loadBalancerClass definition was just needed to be appended to service.yaml and it's entry in values.yaml

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Sheikh-Abubaker 
I believe you should come out service type equals to `LoadBalancer` case. If service type is not `LoadBalancer` then all subsequent attributes / stanzas (e.g. `LoadBalancerSourceRanges`) shall be hide. Also, you should consider `LoadBalancer` auto-assign case since the user has no idea he would need to hardcode the IP ranges / load balancer class in order to work.

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker I believe you should come out service type equals to `LoadBalancer` case. 

@zanhsieh I remember some weeks ago when I did changed service type equals to `LoadBalancer` you forbidden me to do it as it doesn't support most of the use case and due to that the CI lint test also kept failing

**Comment by zanhsieh** [comment]
> @zanhsieh I remember some weeks ago when I did changed service type to `LoadBalancer` you forbidden me to do it as it doesn't support most of the use case and due to that the CI lint test also kept failing.

@Sheikh-Abubaker Yes, but that does not stop you to put your implementation in the templates/services.yaml. The current implementation is half-mature.

**Comment by Sheikh-Abubaker** [comment]
> Also, you should consider `LoadBalancer` auto-assign case since the user has no idea he would need to hardcode the IP ranges / load balancer class in order to work.

@zanhsieh have a look at this is this what you meant here.

image

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Yes, but that does not stop you to put your implementation in the templates/services.yaml. The current implementation is half-mature.

@zanhsieh I did that but the lint test is failing again as before.

**Comment by zanhsieh** [comment]
> > Also, you should consider `LoadBalancer` auto-assign case since the user has no idea he would need to hardcode the IP ranges / load balancer class in order to work.
> 
> @zanhsieh have a look at this is this what you meant ?
> 
> image

No. You shall put something on template/service.yaml as once service type is LoadBalancer, the related values shall show up; otherwise all of LoadBalancer related values shall be automatically hidden.

**Comment by Sheikh-Abubaker** [comment]
> I believe you should come out service type equals to `LoadBalancer` case. If service type is not `LoadBalancer` then all subsequent attributes / stanzas (e.g. `LoadBalancerSourceRanges`) shall be hide. Also, you should consider `LoadBalancer` auto-assign case since the user has no idea he would need to hardcode the IP ranges / load balancer class in order to work.

@zanhsieh Have a look, does the below image fulfills all the things you mentioned above?
helm charts

**Review by zanhsieh — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh is everything all right about this PR ?

**Comment by zanhsieh** [comment]
@Sheikh-Abubaker 
Everything is ok. Just currently Grafana.com, the owner of this community repo, now required two approvals to get this PR merge.

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Everything is ok. Just currently Grafana.com, the owner of this community repo, now required two approvals to get this PR merge.

Thank you so much @zanhsieh for being patient and guiding me through this issue, I've learned a lot about helm and k8s while being contributing to this issue, looking forward to learn and contribute to more issues under the guidance of a maintainer like you, once again thank you!!

**Review by Xtigyro — APPROVED** [review]

**Pull request merged**
