### PR TITLE
[promtail] Update README.md

### PR DESCRIPTION
**Pull request by titouan13**
I think it would be great to add this info. It broke my promtail / loki / grafana installation on my cluster.
I had to manually set docker to make it work.

### CODE REVIEW

**Review by unguiculus — CHANGES_REQUESTED** [review]
Looks good. Please fix DCO and bump the chart version.

**Comment by titouan13** [comment]
I guess it should be OK

**Comment by torstenwalter** [comment]
> I guess it should be OK

DCO check still fails: Check https://github.com/grafana/helm-charts/pull/389/checks?check_run_id=2916499347 how to fix it.

**Review by zanhsieh — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Comment by zanhsieh** [comment]
@unguiculus @Whyeasy 
Could you review this PR and approve it? I don't really expect we could get @titouan13 to sign on license/cla since this PR is too old. I will just set it pass.

**Comment by titouan13** [comment]
As @zanhsieh mentioned, it's obsolete now.

**Pull request closed without merging**
