### PR TITLE
[loki-stack] Updated dependency loki app version

### LINKED ISSUE #2930: loki-stack update app version
hi Abubaker
There is an issue with your pull request: https://github.com/grafana/helm-charts/pull/2875,
https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/requirements.yaml#L5
this line version, the mapping version for Loki is v2.6.1, refer to: https://github.com/grafana/helm-charts/blob/loki-2.15.2/charts/loki/Chart.yaml#L4
Therefore, it is not only necessary to change the outer version, but also to change the mapping version of the loki

Best Regards,
Zibin Ren

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #2930

### CODE REVIEW

**Comment by zalegrala** [comment]
It looks like possibly a dependency changed and a reference no longer exists.

**Comment by Sheikh-Abubaker** [comment]
> It looks like possibly a dependency changed and a reference no longer exists.

but the values file from loki

> It looks like possibly a dependency changed and a reference no longer exists.

As far as I know that reference is pointing to loki-stack `values.yaml` right

**Comment by Sheikh-Abubaker** [comment]
@zanhsieh what do you think about this PR, I stopped working on this after loki-stack was deprecated.

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker Since deprecated, I will close this ticket. Feel free to reopen it if you have another thought.

Alright!

**Pull request closed without merging**
