### PR TITLE
[loki-distributed] Add tlsConfig to memcache serviceMonitor in loki-distribution chart

### PR DESCRIPTION
**Pull request by xbglowx**

### CODE REVIEW

**Comment by zanhsieh** [comment]
@xbglowx 
Please bump the chart to latest version. Thank you.

**Comment by xbglowx** [comment]
> @xbglowx Please bump the chart to latest version. Thank you.

How does it look now?

**Review by zanhsieh — APPROVED** [review]

**Comment by xbglowx** [comment]
Should I bump the chart version to 0.42.1?

Screen Shot 2022-01-25 at 11 49 55 PM

**Comment by zanhsieh** [comment]
Sure.

**Comment by xbglowx** [comment]
I think I am ready for another review.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
