### PR TITLE
[loki] Fix double rule evaluation

### PR DESCRIPTION
**Pull request by azuwis**
See https://github.com/grafana/loki/issues/3005#issuecomment-770401967 for issue detail.

### CODE REVIEW

**Review by 644755 — APPROVED** [review]

**Comment by zanhsieh** [comment]
@azuwis 
Could you bump the chart to latest please?

**Comment by azuwis** [comment]
> @azuwis Could you bump the chart to latest please?

Done.

**Comment by zanhsieh** [comment]
@azuwis 
Please also sign DCO. The instruction shows next on the bottom of this PR page (click Details next to "Action required after 1s - DCO)

**Review by zanhsieh — DISMISSED** [review]

**Comment by azuwis** [comment]
> @azuwis Please also sign DCO. The instruction shows next on the bottom of this PR page (click Details next to "Action required after 1s - DCO)

Done

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
