### PR TITLE
[lgtm-distributed] Add Grafana OnCall to the chart dependencies.

### LINKED ISSUE #2698: [lgtm-distributed] Add optional Grafana OnCall to the chart
As suggested in [#1397](https://github.com/grafana/helm-charts/issues/1397#issuecomment-1747289091), it would be useful to add a [Grafana OnCall](https://github.com/grafana/oncall/tree/dev/helm/oncall) to the chart dependencies, but keep it disabled by default. This should be a minor version change.

### PR DESCRIPTION
**Pull request by Sheikh-Abubaker**
Fixes #2698

### CODE REVIEW

**Review by zalegrala — APPROVED** [review]

**Review by zalegrala — APPROVED** [review]

**Comment by timberhill** [comment]
This is very nice, is there anyone else that could review this? @zalegrala

**Comment by zalegrala** [comment]
Not sure who maintains this chart.  I don't see owners in `.github/CODEOWNERS`

**Comment by timberhill** [comment]
@zalegrala I have created it and asked to add myself to the list of maintainers in the chart, but nothing about codeowners. I guess it would be good to add 2+ people. [Here is the initial PR](https://github.com/grafana/helm-charts/pull/2666), which was reviewed by @zanhsieh (who might have some thoughts on this).

I am not part of the org, so not sure where to go from here :)

**Comment by Sheikh-Abubaker** [comment]
@timberhill if maintainers are needed I could come up as one!

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
