### PR TITLE
[grafana] Adding missing mountPath for csi extraVolumeMount

### PR DESCRIPTION
**Pull request by jifwin**
mountPath is required

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@jifwin 
Thanks for the contribution. Can you bump the version in Chart.yaml so the CI can merge this PR once approved?

**Comment by jifwin** [comment]
Version bumped.

**Comment by zanhsieh** [comment]
Please sign DCO too.

**Comment by jifwin** [comment]
Signed.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
