### PR TITLE
[enterprise-metrics] fix: Remove jsonnet-bundler symlink for tanka-util

### LINKED ISSUE #502: symlink in repo prevents charts import in rancher
Maybe not feature that everyone is looking for but it would be good to not have symlinks in chart repos.  It seems to be a bad practice anyways.

Upon installation on grafana charts in new Rancher 2.5.7 there is an error message
Screenshot 2021-06-16 at 13 49 32

With the blame of
Screenshot 2021-06-16 at 13 50 57

Would be great if this matters to anyone.
CC: @jdbaldry 

Cheers.

### PR DESCRIPTION
**Pull request by jdbaldry**
Symlinks break Rancher helm repository import.

Fixes #502 

Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by jdbaldry** [comment]
Linting is failing as I have not increased the chart version for enterprise-metrics. I'd rather not have to bump the chart version to get  this merged if possible.

**Comment by torstenwalter** [comment]
It's not possible to publish a new version of a chart without increasing it's version,

**Comment by jdbaldry** [comment]
Thanks for confirmation. I had another outstanding PR for this chart that has since been merged so I can now rebase this branch and bump the chart version to get this PR mergeable.

**Review by 56quarters — APPROVED** [review]
LGTM

**Pull request merged**
