### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).

The misspellings had been reported at https://github.com/jsoref/helm2-grafana/commit/f7d835ef86640ee9ebfcae2e0aaf5e1bb3ebf58a

The action reports that the changes in this PR would make it happy: https://github.com/jsoref/helm2-grafana/commit/d170ccfd0e74177210b21e7fd1bbccc70309a246

Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

--
this is a rebase of #1 -- but practically speaking it should have been done using `git filter-branch --tree-filter` to deal w/ a directory rename.

### CODE REVIEW

**Comment by scottrigby** [comment]
@jsoref because chart version packages should be immutable, even a spelling change must bump the chart version:

See the [action log](https://github.com/grafana/helm-charts/pull/5/checks?check_run_id=1071354936): 
>  ✖︎ grafana => (version: "5.6.0", path: "charts/grafana") > Chart version not ok. Needs a version bump!

Because of this, spelling changes in charts should not normally be done during an initial git filter-branch operation, but in subsequent PRs as you're doing now.

**Comment by jsoref** [comment]
@scottrigby: I wasn't talking about that, it was a reference to https://github.com/grafana/helm-charts/pull/1#issuecomment-686890952 for @torstenwalter -- as to why the merge failed and how one could have done the apply to get the commits onto the top of the tree.

**Comment by scottrigby** [comment]
@jsoref ah I see what you mean. Hm, I can follow up as to why. For future ref @torstenwalter GitHub now allows you to change the base branch of an existing PR https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by torstenwalter** [comment]
> For future ref @torstenwalter GitHub now allows you to change the base branch of an existing PR https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-base-branch-of-a-pull-request 

That's what I did and GitHub decided to close the PR. Could be because git histories have been unrelated.

**Review by torstenwalter — APPROVED** [review]
Thanks for the contribution.

**Pull request merged**
