### PR TITLE
[tempo] fix tempo-oltp-http ports

### PR DESCRIPTION
**Pull request by flokli**
`values.yaml` configures `receivers.otlp.protocols.http` to `0.0.0.0:4318`.

The service should match that config.

### CODE REVIEW

**Comment by flokli** [comment]
In the meantime, this can be worked around by manually setting the port in the config to the one that's configured in the service:

```yaml
tempo:
  receivers:
    otlp:
      protocols:
        http:
          # workaround for https://github.com/grafana/helm-charts/pull/916/files
          endpoint: 0.0.0.0:55681
```

**Review by mapno — COMMENTED** [review]
Thanks for the change. Please bump the chart version and this is good to go.

**Comment by flokli** [comment]
@mapno thanks for the review! I now included a bump of the chart version, PTAL.

**Comment by annanay25** [comment]
Hi @flokli, thanks for the PR, you'd have to run the helm docs command after a version bump

```
 docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```

You can find this in the failing CI run https://github.com/grafana/helm-charts/runs/4664347234?check_suite_focus=true

**Review by zanhsieh — APPROVED** [review]

**Comment by flokli** [comment]
Thanks!

**Pull request merged**
