### PR TITLE
[loki-distributed] Allow to configure storage and schema configs with chart values

### PR DESCRIPTION
**Pull request by 0xgui**
In order to configure storages and schemas without redoing all the loki config I've added `schemaConfig` and `storageConfig` parameters in `values.yaml`to allow the configuration of individual storages. Default values remain the same. 

The helm chart of tempo-distributed already implements a similar approach. 

Also, fixed some bugs in the README.md.gotmpl that were creating errors with helm-docs.

### CODE REVIEW

**Comment by Whyeasy** [comment]
Hi @0xgui,

Can you please fix the conflicts and use `0.36.0` as a version. Initially we were not planning to support this, but it seems Tempo got it merged and this is the second time it got requested. 

So lets get is merged! 😄

**Comment by 0xgui** [comment]
Hello, can this still be merged ? It was supposed to be merged with version 0.36.0 but we are already at 0.37.1.

**Comment by jdbaldry** [comment]
Sorry to remove myself from this review but I'm not best placed to progress this PR.

**Comment by 0xgui** [comment]
Closing this PR because I don't have time to track this issue anymore.
Please review PR #804. It's exactly the same issue and people seem to really need it merged. It was supposed to be merged already in version 0.36.0.
Thanks

**Pull request closed without merging**
