### PR TITLE
[synthetic-monitoring-agent] Add default emptyDir for /tmp with synthetic-agent

### PR DESCRIPTION
**Pull request by BlackDex**
The synthetic-monitoring-agent needs a writeable `/tmp` to allow k6 script to be run. When running as a non root user and a read only fs this will break currently.

This PR adds a default emptyDir for the /tmp folder so this will work. I did not add optional volume mounts here since i do not see the value in that for this pod.

### CODE REVIEW

**Comment by BlackDex** [comment]
@Sheikh-Abubaker, should i bump the chart number?
And to what? `0.3.1` or `0.4.0`?

**Comment by Sheikh-Abubaker** [comment]
> @Sheikh-Abubaker, should i bump the chart number? And to what? `0.3.1` or `0.4.0`?

Before this PR was it a breaking change ? and if it was have you tested it now if it is patched ?

**Comment by BlackDex** [comment]
It isn't a breaking change as far as i can see.
I have tested it, as now k6 works on my environment, without this it doesn't.

**Comment by Sheikh-Abubaker** [comment]
>  without this it doesn't.

So you mean to say, without this PR the environment broke right ? could you share the error logs that showed up when the environment broke without these changes.

**Comment by BlackDex** [comment]
Yes, without this PR it breaks. It reports that it can't write the k6 file to `/tmp`.
If you want the exact error message i can check that tomorrow.

**Comment by Sheikh-Abubaker** [comment]
> Yes, without this PR it breaks. It reports that it can't write the k6 file to `/tmp`. If you want the exact error message i can check that tomorrow.

Great! feel free to post it here!

**Review by Sheikh-Abubaker — COMMENTED** [review]
@BlackDex Bump the chart version to `0.4.0` to fix CI lint error.

**Comment by Sheikh-Abubaker** [comment]
@BlackDex  You need to run helm-docs also to fix the docs error.

**Comment by BlackDex** [comment]
Ok.. should be done now too.
Sorry for all these extra haha.

**Comment by Sheikh-Abubaker** [comment]
> Ok.. should be done now too. Sorry for all these extra haha.

No worries!

**Comment by BlackDex** [comment]
Here is the log entry btw:

```json
"msg": {
  "error": "cannot create temporary directory: mkdir /tmp/k6-runner284628990: read-only file system",
  "caller": "github.com/grafana/synthetic-monitoring-agent/internal/prober/scripted/scripted.go:65",
  "program": "synthetic-monitoring-agent",
  "level": "error",
  "subsystem": "adhoc",
  "message": "running probe",
  "time": 1724150537937
}
```

**Comment by BlackDex** [comment]
I also used the same helm-docs now as the ci does.

**Comment by Sheikh-Abubaker** [comment]
> Here is the log entry btw:
> 
> ```json
> "msg": {
>   "error": "cannot create temporary directory: mkdir /tmp/k6-runner284628990: read-only file system",
>   "caller": "github.com/grafana/synthetic-monitoring-agent/internal/prober/scripted/scripted.go:65",
>   "program": "synthetic-monitoring-agent",
>   "level": "error",
>   "subsystem": "adhoc",
>   "message": "running probe",
>   "time": 1724150537937
> }
> ```

Isn't there any logs from terminal ?

**Comment by BlackDex** [comment]
> > Here is the log entry btw:
> > ```json
> > "msg": {
> >   "error": "cannot create temporary directory: mkdir /tmp/k6-runner284628990: read-only file system",
> >   "caller": "github.com/grafana/synthetic-monitoring-agent/internal/prober/scripted/scripted.go:65",
> >   "program": "synthetic-monitoring-agent",
> >   "level": "error",
> >   "subsystem": "adhoc",
> >   "message": "running probe",
> >   "time": 1724150537937
> > }
> > ```
> 
> Isn't there any logs from terminal ?

That is the log from the terminal. It's in json format.

**Comment by Sheikh-Abubaker** [comment]
> That is the log from the terminal. It's in json format.

Yeah it is in json, but the terminal logs aren't json are they ?

**Comment by BlackDex** [comment]
> > That is the log from the terminal. It's in json format.
> 
> Yeah it is in json, but the terminal logs aren't json are they ?

This is straight from the K9s log overview. Nothing manipulated (except for new lines and indenting)

**Review by zanhsieh — APPROVED** [review]

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM!

**Pull request merged**
