### PR TITLE
[tempo] Add ability to set `persistentVolumeClaimRetentionPolicy` in Tempo StatefulSet

### PR DESCRIPTION
**Pull request by aerfio**
Add ability to set `persistentVolumeClaimRetentionPolicy` like in other charts:
- https://github.com/grafana/helm-charts/blob/83365ca13d40222b636d81b33b2fe703fc970505/charts/loki-distributed/templates/compactor/statefulset-compactor.yaml#L24
- https://github.com/grafana/helm-charts/blob/83365ca13d40222b636d81b33b2fe703fc970505/charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml#L24
- https://github.com/grafana/helm-charts/blob/83365ca13d40222b636d81b33b2fe703fc970505/charts/loki-distributed/templates/ingester/statefulset-ingester.yaml#L29
- Loki repo: https://github.com/grafana/loki/blob/26dfd628f0effe2367420f591da36727ebe78806/production/helm/loki/templates/single-binary/statefulset.yaml#L34

I can also expose the ability to override
```yaml
    whenDeleted: Delete
    whenScaled: Delete
```
if requested.

### CODE REVIEW

**Comment by aerfio** [comment]
Hi @Sheikh-Abubaker, I see that you're reviewing other PRs, could you please take a look at this one? Thank you in advance 😄

**Comment by Sheikh-Abubaker** [comment]
> Hi @Sheikh-Abubaker, I see that you're reviewing other PRs, could you please take a look at this one? Thank you in advance 😄

Hey @aerfio sorry for the delay, I'm a bit occupied as of now, but I'll review it soon!

**Review by zanhsieh — APPROVED** [review]

**Comment by Sheikh-Abubaker** [comment]
Hey @aerfio you'd need to bump chart version to `1.14.0` before I could approve this!

**Comment by aerfio** [comment]
@Sheikh-Abubaker done!

**Comment by Sheikh-Abubaker** [comment]
@aerfio could you please address the failed CI check by running the `helm-docs` inside `/charts/tempo/`

**Comment by aerfio** [comment]
@Sheikh-Abubaker re-run `helm-docs`.

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM!

**Pull request merged**
