### PR TITLE
Update charts for Loki 2.1.0

### PR DESCRIPTION
**Pull request by slim-bean**
This should update everything to the latest Loki release

### CODE REVIEW

**Comment by slim-bean** [comment]
going to open up new PR's, one for each chart

**Comment by slim-bean** [comment]
on second thought...

**Comment by slim-bean** [comment]
I'll have to put some thought into how to handle this better for a future release, for now I'm going to cheat a little and force the merge because I can override the requirement that a PR does not cover multiple charts

**Review by joe-elliott — APPROVED** [review]
Merry Christmas!  Ho Ho Ho!

**Pull request merged**
