### PR TITLE
[loki-distributed] DOCS fix typo ingester

### PR DESCRIPTION
**Pull request by mattclegg**
Split from https://github.com/grafana/helm-charts/pull/2791

@Whyeasy @unguiculus Anything else needed changing here?

### CODE REVIEW

**Comment by mattclegg** [comment]
Merged upstream @Whyeasy @unguiculus

**Comment by Sheikh-Abubaker** [comment]
Hey there @mattclegg thanks for the contribution, could you please bump the chart version and address the failed CI lint checks ?

**Review by Sheikh-Abubaker — COMMENTED** [review]
Hey there @mattclegg thanks for the contribution, could you please bump the chart version and address the failed CI lint checks ?

**Comment by mattclegg** [comment]
ok @Sheikh-Abubaker

**Review by Sheikh-Abubaker — COMMENTED** [review]
Hey there @mattclegg  Could you please address the CI lint error, if you're facing any issues resolving that error, let me know!!

**Review by Sheikh-Abubaker — APPROVED** [review]
LGTM!

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
