### PR TITLE
[grafana] correct array formatting for grafana.ini

### PR DESCRIPTION
**Pull request by nathwill**
fixes array format in configmap grafana.ini.

previously produced: `org_mapping = ["a" "b" "c"]`, which grafana did not apply correctly
now produces: `org_mapping = ["a", "b", "c"]`, which grafana applies correctly

of note:
for some reason this only seems to work when applied as TOML style array lists `["a", "b", "c"]`, even though the file type is nominally ini, which would suggest the following would actually be appropriate:
```
org_mapping[] = "a"
org_mapping[] = "b"
org_mapping[] = "c"
```

🤷

### CODE REVIEW

**Comment by jkroepke** [comment]
Could you link documentation, where array style is used?

for org_mapping, I can only find a space separated string:

```
org_mapping = org_foo:org_foo:Viewer org_bar:org_bar:Editor *:org_baz:Editor
```

**Comment by jkroepke** [comment]
but with the join method, it will result into:

```
org_mapping = [a,b,c]
```

not

```
org_mapping = ["a","b","c"]
```

**Comment by nathwill** [comment]
yeah, string-wrapping is optional as it's written and afaik only required when spaces are involved (?)... if we want to enforce string-wrapping i can update the PR accordingly, just wanted to only do the minimal needed so it could be made to work via values...

in our patched version of the chart we're passing values in like this:

```
    org_mapping:
    - '"SRE:1:Admin"'
    - '"Support:1:Editor"'
    - '"Data Scientists:1:Editor"'
    - '"Developers:1:Editor"'
```

which produces 

```
org_mapping = ["SRE:1:Admin", "Support:1:Editor", "Data Scientists:1:Editor", "Developers:1:Editor"]
```

**Comment by jkroepke** [comment]
instead `join`, consider using [`toJson`](https://helm.sh/docs/chart_template_guide/function_list/#tojson-musttojson)

**Comment by nathwill** [comment]
cool, i like it.

**Review by jkroepke — COMMENTED** [review]
For conistancy reasons, could you has this to the config section (15 lines above) as well?

**Review by jkroepke — APPROVED** [review]

**Pull request merged**
