### PR TITLE
[loki-distributed] Add autoscaling support

### PR DESCRIPTION
**Pull request by stevehipwell**
Fixes https://github.com/grafana/helm-charts/issues/664.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@sherifkayad you might be interested in these changes as your Index Gateway changes will allow the Querier component to be autoscaled along with the Gateway, Distributer and Query Frontend.

**Comment by sherifkayad** [comment]
@stevehipwell looks great! I am sure we can make good use of these changes once your PR is merged. Thanks for the hint.

**Comment by stevehipwell** [comment]
@Whyeasy could you take a look at this? I've rebased after #666 was merged so am happy that the CI will pass as it did previously.

**Review by Whyeasy — APPROVED** [review]
LGTM!

**Pull request merged**
