### PR TITLE
[tempo-vulture] feat: add option to deploy podmonitor and add option to remove svc

### PR DESCRIPTION
**Pull request by KyriosGN0**
added option to opt out of using a service (still enabled by default) and add podMonitor which is disabled by default

### CODE REVIEW

**Comment by KyriosGN0** [comment]
Hey @Whyeasy, @dgzlopes, can i get a review here? sorry for nagging

**Comment by KyriosGN0** [comment]
hey @Whyeasy @dgzlopesm, another ping...

**Comment by KyriosGN0** [comment]
hey @Whyeasy @dgzlopes, can i please get a review here? thanks!

**Review by zanhsieh — APPROVED** [review]

**Comment by KyriosGN0** [comment]
@Whyeasy @dgzlopes, hey sorry to nag, but its been over a month....

**Comment by KyriosGN0** [comment]
hey @Whyeasy @dgzlopes, another 2 weeks, another ping :(

**Comment by KyriosGN0** [comment]
hey, @Whyeasy @dgzlopes, im really sorry that and i might sound disrecptpful, but i opened the PR almost 2 and half months ago, and i haven't gotten a one comment from as codeowner.
i would really like to merge this, since its a really simple change

**Comment by KyriosGN0** [comment]
ping @Whyeasy @dgzlopes

**Comment by KyriosGN0** [comment]
@zanhsieh i rebased according to new chart, is it possible to get a review ? (also from codeowners?)

**Comment by zalegrala** [comment]
Hi thanks for the PR.  Can you add a little context about why this change is necessary?

**Comment by KyriosGN0** [comment]
hey @zalegrala in general in my org we prefer the option to disable services and use pod-monitors instead of service monitor

**Comment by zalegrala** [comment]
Hi, I'm a bit slow.  Is there a reason we need the service for vulture at all?

**Comment by KyriosGN0** [comment]
@zalegrala as far as i understand no, its entirely a "client" application, only reason for service is for service monitor.

**Comment by zalegrala** [comment]
In that case, what do you think about just deleting the service and skipping the option entirely?

**Comment by KyriosGN0** [comment]
@zalegrala im fine with it.

**Comment by KyriosGN0** [comment]
@zalegrala updated PR to remove service

**Review by zalegrala — APPROVED** [review]

**Pull request merged**
