### PR TITLE
[agent-operator] Fix agent-operator tests setting an empty MetricsInstance spec

### PR DESCRIPTION
**Pull request by cippaciong**
Because:

* Having a null `spec:` definition in the agent-operator MetricsInstance
  used for test, causes the test to fail with the following error during
  the apply of the manifest: 'The MetricsInstance "primary" is invalid:
  spec: Invalid value: "null": spec in body must be of type object:
  "null"'

This commit:

* Sets the value to an empty object `spec: {}` rather than null

Signed-off-by: Tommaso Sardelli <lacapannadelloziotom@gmail.com>

### CODE REVIEW

**Comment by cippaciong** [comment]
@hjet @rfratto Sorry for the direct mention, I hoped you could have a look at this.

Unfortunately when you deploy the helm chart using [terraform-provider-helm](https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release#disable_webhooks) it will automatically run the test and mark the installation as failed even if it's not, so this is kind of a blocker for me 😓

**Comment by hjet** [comment]
Thanks for this! Looks like both the test CI cluster and k3s both don't support OpenAPIV3 schema validation...

Can you run `helm-docs` and commit the changes? That'll get the last check passing. 

We didn't really test this with the terraform provider so there may be some other weirdness (usually objects deployed by `helm test` don't get cleaned up) - please file any other issues in https://github.com/grafana/agent and we'll take a look.

**Comment by hjet** [comment]
This may also solve the `helm test` cleanup issue: https://helm.sh/docs/topics/charts_hooks/#hook-deletion-policies

**Comment by cippaciong** [comment]
Thanks for the feedback @hjet 🙂 
I updated the README with `helm-docs` and added the `hook-delete-policy` annotations, let me know if there is anything else I can do.

**Review by hjet — APPROVED** [review]
lgtm!

**Comment by hjet** [comment]
Thanks so much! I tested locally and for some reason the resources were not cleaned up after the `helm test` hook passed (this was the case before as well). But fixing this is out of scope for this CL so I will merge - just be careful in your own clusters with straggler resources!

**Comment by cippaciong** [comment]
Thanks 🙂

**Pull request merged**
