### PR TITLE
[loki-distributed] DOCS fix typo ingester

### PR DESCRIPTION
**Pull request by mattclegg**
See commit log.

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@mattclegg 
Thanks for contribution. Can you bump the version in Chart.yaml to latest please?

**Comment by mattclegg** [comment]
@zanhsieh Sure, I've just rebased from main

**Comment by zanhsieh** [comment]
This PR has to split to 2 PRs since multiple charts modified.

**Comment by mattclegg** [comment]
OK @zanhsieh

[loki-distributed](https://github.com/grafana/helm-charts/pull/3129)
[tempo-distributed](https://github.com/grafana/helm-charts/pull/3027)

**Pull request closed without merging**
