### PR TITLE
[tempo-distributed] Add topologySpreadConstraints to all deployments and stateful sets

### PR DESCRIPTION
**Pull request by Joibel**

### CODE REVIEW

**Comment by zanhsieh** [comment]
@Joibel 
Thank you for contribution. To fix the CI error, please bump the version in Chart.yaml to latest. Previously I tried to help but your grafana repo fork master branch is protected.

**Comment by Joibel** [comment]
> @Joibel Thank you for contribution. To fix the CI error, please bump the version in Chart.yaml to latest. Previously I tried to help but your grafana repo fork master branch is protected.

I think that is all done, hope this is good. Yell otherwise and I'll fix it up.

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Joibel 
I think you accidentally commit `tempo` chart to this PR. Please revert the change on `tempo`.

**Comment by Joibel** [comment]
> @Joibel I think you accidentally commit `tempo` chart to this PR. Please revert the change on `tempo`.

Ha, sorry. Been quite a while since the original PR, I've forgotten what I'm doing here. I think this is good now.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
