### PR TITLE
[grafana] Fixed 'kubectl get password' command in note

### PR DESCRIPTION
**Pull request by JoeHCQ1**
Fixed kubectl get password command templating to be correct when using pre-existing secret with different data keys.

Note 1. always said:
`kubectl get secret --namespace grafana releaseName-grafana -o jsonpath="{.data.admin-password}" | base64 --decode ; echo`

Now it can say:
`kubectl get secret --namespace grafana grafana-initial-admin-password -o jsonpath="{.data.password}" | base64 --decode ; echo`

Note both secret name and jsonpath changed. Tested and it still works with empty strings per default values.yaml file.

### CODE REVIEW

**Comment by zanhsieh** [comment]
@JoeHCQ1 
Thanks for your contribution. Could you bump the version in Chart.yaml please?

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@JoeHCQ1 
Thanks for the contribution. Could you sign DCO please?

**Comment by JoeHCQ1** [comment]
@zanhsieh, what is the dco and how do I sign it?

**Comment by zanhsieh** [comment]
> @zanhsieh, what is the dco and how do I sign it?

@JoeHCQ1 
On the bottom of this PR page, you should see `DCO - DCO` above `license/ca` and click `Details`. It shall show how do you fix it.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
