### PR TITLE
[tempo] LoadBalancer cannot simultaneously support TCP and UDP protocols

### PR DESCRIPTION
**Pull request by CostisC**
Some Network Load Balancers (e.g. in GKE) cannot support UDP and TCP at the same time.  
This enhancement adds the `service.protocol` option that defines which L4 protocols to be exposed.  
Further, it will set the exposed ports according to the relevant `tempo.receivers` values.

### CODE REVIEW

**Review by Sheikh-Abubaker — COMMENTED** [review]
Hey there! @CostisC could you please address the failed CI checks ? Thank you!

**Comment by CostisC** [comment]
Thank you, @Sheikh-Abubaker!  
I did't realise that README was auto-generated.

**Comment by CostisC** [comment]
Hi @Sheikh-Abubaker. There seems to have been an env. setup failure. Could you please have a look. Cheers!

**Review by zanhsieh — APPROVED** [review]

**Comment by softhedev** [comment]
Hi there,

Any update on the PR here?

**Review by mapno — APPROVED** [review]
Tested locally, LGTM 👍

**Pull request merged**
