### PR TITLE
[tempo-distributed] add missing namespaces to gateway resource

### PR DESCRIPTION
**Pull request by jhedev**
Realized this when installing with `helm template ... ` followed by `kubectl apply`. 

If that is intended I'm happy to change it. Please let me know if I did something wrong w.r.t. contributing :)

### CODE REVIEW

**Comment by jhedev** [comment]
Is there anything else I need to do to get this reviewed?

**Comment by zanhsieh** [comment]
> Is there anything else I need to do to get this reviewed?

@jhedev 
Helm itself does support `-n` argument. Check `helm template --help`.

```console
$ helm template --help

Render chart templates locally and display the output.

Any values that would normally be looked up or retrieved in-cluster will be
faked locally. Additionally, none of the server-side testing of chart validity
(e.g. whether an API is supported) is done.

Usage:
  helm template [NAME] [CHART] [flags]

Flags:
  ...

Global Flags:
      ...
  -n, --namespace string                namespace scope for this request
      ...
```

**Comment by jhedev** [comment]
@zanhsieh Thanks for your comment!

I know the `-n` option for `helm template` but it does not work as expected. It only sets the namespace for all resources where it is set via `.Release.namespace` but not all the others. 

Example:

```shell
$ echo 'gateway:\n  enabled: true' >> custom.yaml
$ helm template --namespace foo helm/tempo-distributed --values custom.yaml
---
# Source: tempo-distributed/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-tempo
  namespace: foo
  labels:
    helm.sh/chart: tempo-distributed-1.6.10
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "2.2.3"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: false
...
---
# Source: tempo-distributed/templates/gateway/deployment-gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-tempo-gateway
  labels:
    helm.sh/chart: tempo-distributed-1.6.10
    app.kubernetes.io/name: tempo
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: gateway
    app.kubernetes.io/version: "2.2.3"
    app.kubernetes.io/managed-by: Helm
spec:
  minReadySeconds: 10
...
$ helm version
version.BuildInfo{Version:"v3.13.0", GitCommit:"825e86f6a7a38cef1112bfa606e4127a706749b1", GitTreeState:"clean", GoVersion:"go1.21.1"}
```

With the changes made in this PR it works fine across the gateway resources. 

Also see this helm issue: https://github.com/helm/helm/issues/3553

And my other PRs to other grafana charts:
- https://github.com/grafana/loki/pull/10713
- https://github.com/grafana/pyroscope/pull/2432

**Review by zanhsieh — COMMENTED** [review]
@jhedev 
Can you fix the lint error please?

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
