### PR TITLE
[loki] fix ingress support k8s.version>=1.20

### PR DESCRIPTION
**Pull request by dagmom**
#646

### CODE REVIEW

**Comment by zanhsieh** [comment]
@dagmom 
Please bump chart version to latest and sign DCO. Thank you.

**Comment by zanhsieh** [comment]
@dagmom 
Also, please separate PR. One chart one PR. It's hard to get all charts owners / reviewers to agree and merge.

**Comment by dagmom** [comment]
> 

ok

**Comment by dagmom** [comment]
> @dagmom Please bump chart version to latest and sign DCO. Thank you.

what means "bump"? 
promtail chart version: 2.4.1
helm version: v3.7.2

**Comment by zanhsieh** [comment]
> 

"bump Chart version" means updating the respective chart version to latest. For example, the current promtail chart version: 3.9.1 -> 3.9.2.

**Comment by dagmom** [comment]
> promtail chart version: 2.4.1
> helm version: v3.7.2

loki chart version: 2.8.4
helm version: v3.7.2

**Pull request closed without merging**
