### PR TITLE
[tempo-distributed] add metrics_generator_processors when metrics generator is enabled

### PR DESCRIPTION
**Pull request by YayBurritos**
@joe-elliott: Second attempt at this. New fork, new branch, with essentially the same changes.  Hopefully this time we got it right. The other PR (https://github.com/grafana/helm-charts/pull/2070) can be deleted if all is well with this one.

### CODE REVIEW

**Comment by joe-elliott** [comment]
....spinning.............SPINNING

**Comment by joe-elliott** [comment]
:eye: _ :eye:

image

**Review by joe-elliott — APPROVED** [review]
it's been a journey, @YayBurritos. Thanks for sticking with it!

hope to catch you in a future PR :pray:

**Comment by YayBurritos** [comment]
> it's been a journey, @YayBurritos. Thanks for sticking with it!
> 
> hope to catch you in a future PR 🙏

Sure has! Thanks for all the guidance. This serves as my first official contribution to the OSS community. And I see someone is already asking if you can "turn off the service graph processor" (https://grafana.slack.com/archives/C01D981PEE5/p1674234384357619) 😄

**Comment by joe-elliott** [comment]
haha :), that's the way it goes!

**Pull request merged**
