### PR TITLE
[tempo-distributed] Added missing components

### PR DESCRIPTION
**Pull request by xogoodnow**
Hi,

Not all components were mentioned in the chart.

Cheers

### CODE REVIEW

**Comment by xogoodnow** [comment]
I did not mention the enterprise gateway and the Memcached exporter.
Should they be included as well?

**Comment by zalegrala** [comment]
Thanks for the PR.  The enterprise components sound reasonable to mention also.  Admin-api, gateway and memcached all sound reasonable.

**Comment by xogoodnow** [comment]
> Thanks for the PR. The enterprise components sound reasonable to mention also. Admin-api, gateway and memcached all sound reasonable.

Added all components.
Also changed "gateway.get.example.com" to "gateway.gem.example.com" (sorry I'm a little OCD :) )

Cheers

**Comment by xogoodnow** [comment]
@zalegrala,
This is not related to this PR.

I wanted to send a PR so all ingress sample domains would use {{ .Release.name }} instead of the the hardcoded sample (like the ones in Mimir chart)
If you agree please let me know.

Cheers

**Comment by xogoodnow** [comment]
> Thanks for the PR. The enterprise components sound reasonable to mention also. Admin-api, gateway and memcached all sound reasonable.

Done.

**Review by zalegrala — APPROVED** [review]

**Review by Sheikh-Abubaker — APPROVED** [review]

**Pull request merged**
