### PR TITLE
[grafana] allow for searchNamespace flag to be passed as a list

### PR DESCRIPTION
**Pull request by Allex1**
Signed-off-by: birca <birca@adobe.com>

### CODE REVIEW

**Review by Xtigyro — DISMISSED** [review]
Hey @Allex1 👋 Thank you for your contribution - it's appreciated! 💯 

Could you please document this on the respective lines in the comments in `values.yaml` and also in the `README`? And bump the chart version to `6.7.0`?

**Comment by Allex1** [comment]
@Xtigyro I'm not sure we should document this yet as `k8s-sidecar` only accepts 1 namespace as string. We'd like to be able to pass namespaces as list in helm as we are using a modified `k8s-sidecar` version which is not yet contributed back. This pr does not change the behaviour of the helm chart.

**Comment by Xtigyro** [comment]
In this case we would like to wait until the official version of `k8s-sidecar` supports it.

**Comment by Allex1** [comment]
@Xtigyro @maorfr @zanhsieh I've updated values comments and readme and contributed https://github.com/kiwigrid/k8s-sidecar/pull/136 in order for the sidecar to support this flag. Please review again.

**Review by zanhsieh — APPROVED** [review]

**Review by zanhsieh — APPROVED** [review]

**Comment by Allex1** [comment]
@Xtigyro @maorfr pls review

**Review by zanhsieh — DISMISSED** [review]

**Comment by Allex1** [comment]
@maorfr @Xtigyro @torstenwalter @zanhsieh 
can we get this merged ? This change will bring consistency between components like [kube-state-metrics](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/deployment.yaml#L90) and [PrometheusOperator](https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/templates/prometheus-operator/deployment.yaml#L59) especially in a setup like Kube-prometheus-stack where you need to define namespaces once for all components.

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
