### PR TITLE
[tempo-distributed] Allow to manage reporting to grafana.com

### PR DESCRIPTION
**Pull request by Krast76**
Hello 👋 

This MR allow to manage reporting for tempo-distributed (the same way tempo chart handle it)

### CODE REVIEW

**Comment by zalegrala** [comment]
Looks good to me.  We'll need a version bump for this and then I can check back.

**Comment by Krast76** [comment]
@zalegrala Done

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@Krast76 
Thank you for the contribution. Could you update the README.md with helm-docs and sign DCO please?

**Comment by Krast76** [comment]
@zanhsieh I did it :)

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
