### PR TITLE
[grafana] make datasource sidecar watchMethod configurable

### PR DESCRIPTION
**Pull request by D3luxee**
This PR makes the watchMethod for the datasource sidecar configurable like the dashboard sidecar.
The current default behavior is kept.

### CODE REVIEW

**Comment by zanhsieh** [comment]
@D3luxee 
Could you bump the chart version and sign DCO please?

**Comment by D3luxee** [comment]
Hi, i wasn't sure if i should bump the chart or if you guys do it only on releases.
Now i've bumped it from 6.17.5 to 6.17.6 and signed off the DCO for all commits.

**Review by zanhsieh — APPROVED** [review]

**Comment by xeor** [comment]
I'm not sure if this works as intended. Setting `sidecar.datasources.watchMethod` to `WATCH` for me on chart `6.18.1` makes grafana not able to start..

**Comment by zanhsieh** [comment]
@D3luxee 
Could you look into @xeor 's case please ?

**Comment by D3luxee** [comment]
I can confirm this issue, it seems i missed the fact that the datasource sidecar is an init container and the k8s-sidecar will not exit in watch mode.

I was using this chart as part of kube prometheus stack on friday this was finally updated to use the latest version of the grafana chart. I've run into the same issue as @xeor and spend the friday with debugging and figuring out how to resolve it.

There are a few things to consider in trying to make the chart able to dynamically provision datasources.

Grafana does not watch for new datasources in the provisioning folder, it does poll new dashboards but not new datasources!
This means that Grafana will only load datasources at startup. https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources

This might be the reason why this was on watchMethod LIST and as an init container.. but there is still a way to get it working!

Grafana supports reloading the provisioned datasources via api and the k8s sidecar supports sending requests when a config map changed. 
https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations
https://github.com/kiwigrid/k8s-sidecar#configuration-environment-variables

I can provide a configuration example here for others to find and we could discuss if this should be added to the chart. 
The k8s-sidecar would need to be configured with grafana admin credentials to allow it reloading via admin api.

**Comment by D3luxee** [comment]
@xeor 
The settings below will define a second container which will watch for new datasources.
What happens is:
1. original datasource sidecar will start as init container and provision datasources
2. the extra datasource sidecar will start in WATCH mode and add any new datasources and trigger a reload via api
```
    grafana:
      extraContainers: |
        - name: grafana-dynamic-datasources
          image: "quay.io/kiwigrid/k8s-sidecar:1.14.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: METHOD
              value: WATCH
            - name: LABEL
              value: "dynamic_datasource"
            - name: FOLDER
              value: "/etc/grafana/provisioning/datasources"
            - name: RESOURCE
              value: "both"
            - name: NAMESPACE
              value: ALL
            - name: REQ_URL
              value: http://grafana/api/admin/provisioning/datasources/reload
            - name: REQ_METHOD
              value: POST
            - name: REQ_USERNAME
              value: admin
            - name: REQ_PASSWORD
              value: YourGrafanaAdminPassword
          resources: {}
          volumeMounts:
            - name: sc-datasources-volume
              mountPath: "/etc/grafana/provisioning/datasources"
```

**Pull request merged**
