### PR TITLE
[lgtm-distributed] #1397 LGTM stack helm chart

### PR DESCRIPTION
**Pull request by timberhill**
Adding a new chart with an whole LGTM stack in a microservice mode.

Contributes to #1397 

### Testing done

Deployed to a KIND cluster with k8s version `v1.24.0`.

Loki datasource populated with `grafana-agent` chart:

```sh
helm upgrade --install grafana-agent grafana-agent -f grafana-agent-values.yaml --repo https://grafana.github.io/helm-charts
```

<details>
  <summary>grafana-agent-values.yaml</summary>
  
  Heavily plagiarised from the config @Chewie shared [here](https://github.com/grafana/helm-charts/issues/1397#issuecomment-1523354592)
  
  ```yaml
  ---
  mounts:
    varlog: true
    dockercontainers: true
  agent:
    configMap:
      content: |
        discovery.kubernetes "all_pods" {
          role = "pod"
        }

        discovery.relabel "all_pods" {
          targets = discovery.kubernetes.all_pods.targets
          rule {
            source_labels = ["__meta_kubernetes_namespace"]
            target_label = "namespace"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_name"]
            target_label = "pod"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_container_name"]
            target_label = "container"
          }
          rule {
            source_labels = ["__meta_kubernetes_pod_controller_name"]
            target_label = "controller"
          }
        }

        loki.source.kubernetes "all_pods" {
          targets = discovery.relabel.all_pods.output
          forward_to = [loki.process.all_pods.receiver]
        }

        loki.process "all_pods" {
          forward_to = [loki.write.loki.receiver]

          stage.cri {}
        }

        loki.source.journal "read" {
          forward_to = [loki.relabel.journal.receiver]
        }

        loki.relabel "journal" {
          forward_to = [loki.write.loki.receiver]
          rule {
            source_labels = ["__journal__systemd_unit"]
            target_label = "unit"
          }
        }

        loki.source.kubernetes_events "events" {
          forward_to = [loki.write.loki.receiver]
        }

        loki.write "loki" {
          external_labels = {
            cluster = "loutretel",
          }
          endpoint {
            url = "http://lgtm-stack-loki-distributor:3100/loki/api/v1/push"
          }
        }

        discovery.kubernetes "all_nodes" {
          role = "node"
        }

        discovery.relabel "all_nodes" {
          targets = discovery.kubernetes.all_nodes.targets
          rule {
            source_labels = ["__meta_kubernetes_node_name"]
            target_label = "node"
          }
        }

        prometheus.scrape "kubelet" {
          targets = discovery.relabel.all_nodes.output
          forward_to = [prometheus.remote_write.mimir.receiver]

          scrape_interval = "15s"
          metrics_path = "/metrics"
          scheme = "https"

          bearer_token_file = "/var/run/secrets/kubernetes.io/serviceaccount/token"
          tls_config {
            ca_file = "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
          }
        }

        prometheus.scrape "default" {
          // Tell the scraper to scrape at http://localhost:12345/metrics.
          // The http:// and metrics are implied but able to be overwritten.
          targets = [{"__address__" = "localhost:12345"}]
          // Forward the scrape results to the receiver. In general,
          // Flow uses forward_to to tell which receiver to send results to.
          // The forward_to is an argument of prometheus.scrape.default and
          // the receiver is an exported field of prometheus.remote_write.prom.
          forward_to = [prometheus.remote_write.prom.receiver]
        }

        prometheus.exporter.unix {
          procfs_path = "/host/proc"
          sysfs_path = "/host/sys"
          rootfs_path = "/host/root"
        }

        discovery.kubernetes "all_services" {
          role = "service"
        }

        prometheus.remote_write "mimir" {
          endpoint {
            url = "http://lgtm-stack-mimir-distributor:8080/api/v1/push"

            headers = {
              X-Scope-OrgID: "fake"
            }
          }
        }

  ```
</details>

>NOTE: Loki datasource is populated and queryable straight after the deployment. Mimir, however, needs authentication to send data to. With the above config, the agent gets `server returned HTTP status 401 Unauthorized: no org id`. It would be nice to fix it.

### Notes for the reviewer
- This chart is using the 'distributed' versions of Loki, Mimir and Tempo, which spawns a whole lot of pods. It is reasonable to have another chart with non-distributed versions too, but that will have to be another PR.
- Default values add datasources connecting Grafana to LTM
- There is currently no agent deployed with this chart (see above)

### Questions
- Does this need a Grafana Agent dependency like some other charts here do? IMHO, collection and storage should be separate deployments, but an agent that is disabled by default would be okay. I might need help getting the default config together though.

### CODE REVIEW

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@timberhill 
Thanks for the contribution. Can you add yourself as one of the maintainers please? A chart without maintainers would be hard to keep it up.

**Comment by timberhill** [comment]
Added the maintainer now.

Something funny is going on with the `lint-test` though - [it seems to have timed out.](https://github.com/grafana/helm-charts/actions/runs/6263623519/job/17022677952)
One of the errors is label too long because the namespace name is quite long I guess. Those workloads aren't starting and aren't available for the other workloads that depend on them, if understand this correctly.

```
4m30s       Warning   FailedCreate            statefulset/lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a                                                             statefulset-controller                                                                               create Pod lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a-0 in StatefulSet lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a failed error: Pod "lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a-0" is invalid: metadata.labels: Invalid value: "lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a-5b7897ffff": must be no more than 63 characters   9m59s        17      lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-a.17870e3d09c78a72
```

Similar thing happening to Loki:

```
4m30s       Warning   FailedCreate            statefulset/lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c                                                             statefulset-controller                                                                               create Pod lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c-0 in StatefulSet lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c failed error: Pod "lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c-0" is invalid: metadata.labels: Invalid value: "lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c-5b9899ff5c": must be no more than 63 characters   9m58s        17      lgtm-distributed-5z5x6fvuwh-mimir-store-gateway-zone-c.17870e3d4554ee23
```

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@timberhill 
Can you fix the lint error please?

**Comment by timberhill** [comment]
Hey @zanhsieh! From what I can see, this is not a lint error, but an issue of a pod name over 63 characters. Setting a namespace and/or the release name to a string like `lgtm-distributed-gj1qqwrmws` results in very long names and hits the 63 char limit. I have tested this locally in a KIND cluster as well and reproduced it with the long names.

As I have very little control over the underlying charts, is there a way to override the release name for the CI to be shorter? It would be useful to document this in the readme too in that case.

**Comment by zanhsieh** [comment]
@timberhill 
Same. CI still stuck somewhere.

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@timberhill 
Same. CI still stuck somewhere.

**Comment by timberhill** [comment]
The issue was that the CPU resource request exceeded the CPU available in the github runner. I have reduced the default requests and replicas to a minimum, hopefully that works now. It's not elegant though, would be nicer to pass some `test-value.yaml` to the chart testing, but it's not an option as far as I can see.

**Review by zanhsieh — APPROVED** [review]

**Comment by ewoolsey** [comment]
As a helm noob, is there any chance we could get a simple deploy and configure tutorial in the readme? Not 100% sure how to get this to work.

**Pull request merged**
