### PR TITLE
[tempo] Allow custom configuration of Tempo server

### PR DESCRIPTION
**Pull request by jleloup**
As described in issue [#487](https://github.com/grafana/helm-charts/issues/487) it would be nice to be able to provide some custom configuration to Tempo server in the single binary chart.

In order to solve that we can use a similar approach to what is already available for other Tempo sub components (like ingester) so a `.Values.tempo.server ` could be used to provide YAML configuration to the server.

Note: to make this change consistent the previous value `httpListenPort: 3100` is modified to be set as any other server configuration.

### CODE REVIEW

**Comment by joe-elliott** [comment]
Thanks for the contribution!

This is technically a breaking change. Since our major version < 1 we don't technically have to update it, but maybe just update the minor rev instead of patch?

**Comment by jleloup** [comment]
> Thanks for the contribution!
> 
> This is technically a breaking change. Since our major version < 1 we don't technically have to update it, but maybe just update the minor rev instead of patch?

Sure I'll go for a minor rev.
I wonder if I need to also update some documentation ?

**Comment by joe-elliott** [comment]
Apologies for the ci checks. I think the last thing you need to do is just run helm-docs. I do this:
```
 docker run --rm --volume "$(pwd):/helm-docs" -u "$(id -u)" jnorwood/helm-docs:v1.4.0
```
Thank you for sticking with this.

**Comment by jleloup** [comment]
You're welcome :)
I think the Helm documentation is now up to date

**Review by joe-elliott — APPROVED** [review]

**Pull request merged**
