### PR TITLE
[promtail] bump promtail version to 2.9.3

### PR DESCRIPTION
**Pull request by venkatamutyala**
Fix bugs/CVEs: https://github.com/grafana/loki/releases/tag/v2.9.3

### CODE REVIEW

**Comment by venkatamutyala** [comment]
:shipit:  🚀 🌕

**Review by zanhsieh — APPROVED** [review]

**Review by siryur — APPROVED** [review]

**Comment by gasmick** [comment]
would be great to get this merged🥺

**Comment by zanhsieh** [comment]
@venkatamutyala Can you update the base branch? It was out-of-the-date.

**Comment by venkatamutyala** [comment]
@zanhsieh sorry my notifs got messed up. Should be good now? Please tag me if you need anything else.

**Comment by zanhsieh** [comment]
@venkatamutyala I believe it should be good. For your own fork grafana repo, plz allow the maintainers to modify; otherwise I can't rebase the out-of-date branch.

@zalegrala Just curious who else are in the "Loki Maintainers" team since neither @unguiculus or @Whyeasy  aren't active maintaining this chart.

**Comment by venkatamutyala** [comment]
@zanhsieh, it appears I can't fix that in my ORG fork: https://github.com/orgs/community/discussions/5634

**Comment by zanhsieh** [comment]
@venkatamutyala I think any Grafana engineer should be able to approve this PR.

**Review by zalegrala — APPROVED** [review]

**Comment by zalegrala** [comment]
@zanhsieh I'm not sure, but I suspect that this takes a back burner after the loki team moved the chart to the loki repo, that's the one that gets their attention the most.

**Comment by venkatamutyala** [comment]
@zalegrala can you link us to it? Perhaps we should just switch charts and deprecate this repo?

**Comment by zalegrala** [comment]
https://github.com/grafana/loki/tree/main/production/helm

**Comment by venkatamutyala** [comment]
> https://github.com/grafana/loki/tree/main/production/helm

Thanks. In their promtail folder it points back to this repo: 
image


Ref:
https://github.com/grafana/loki/blob/main/production/helm/promtail/README.md

**Comment by zalegrala** [comment]
I believe all Loki chart development that involves the Loki team has moved to the Loki repo.  Additionally the team left a note on the `loki` chart here.  https://github.com/grafana/helm-charts/tree/main/charts/loki

**Comment by javiplx** [comment]
Any reason to not merge this already approved PR?
Although I know will make no difference, I would prefer not to explicitly pin the promtail release number and just use the new chart release

**Comment by venkatamutyala** [comment]
@zalegrala how about now?

**Comment by venkatamutyala** [comment]
image

**Pull request merged**
