### PR TITLE
[loki-stack] Bump chart dependecies and loki/promtail to 2.7.0

### PR DESCRIPTION
**Pull request by elcomtik**
Current Loki dependencies are old and prevent installing this chart on k8s v1.25.x due to deprecated API policy/v1beta1. A newer chart solves this. I also updated the Promtail chart to match the Loki version used by the latest Loki chart.

### CODE REVIEW

**Comment by elcomtik** [comment]
this can be resolved by changing the affected line to

`value: "{{ ((.Values.loki).service).port }}"`

**Comment by elcomtik** [comment]
@zanhsieh I rebased the code, would you please approve workflows?

**Comment by elcomtik** [comment]
@zanhsieh I forgot to bump the chart version, which I just fixed. I also fixed the lint issue mentioned above and tested locally. Could you please aprowe workflows again?

**Comment by LarsBingBong** [comment]
v2.7.1 is out ... will this get us that version?

**Comment by elcomtik** [comment]
> v2.7.1 is out ... will this get us that version?

Unfortunatelly no, I can take a look at it

**Comment by elcomtik** [comment]
@LarsBingBong No, currently there is no support for 2.7.1 in either of the dependency charts used.

**Comment by elcomtik** [comment]
More work will be needed as the Loki sub-chart had a major version increase. From its docs:


## Upgrading from v2.x

v3.x represents a major milestone for this chart, showing a committment by the Loki team to provide a better supported, scalable helm chart.
In addition to moving the source code for this helm chart into the Loki repo itself, it also combines what were previously two separate charts,
[`grafana/loki`](https://github.com/grafana/helm-charts/tree/main/charts/loki) and [`grafana/loki-simple-scalable`](https://github.com/grafana/helm-charts/tree/main/charts/loki-simple-scalable) into one chart. This chart will automatically assume the "Single Binary" mode previously deployed by the `grafana/loki` chart if you are using a filesystem backend, and will assume the "Scalable" mode previoulsy deployed by the `grafana/loki-simple-scalable` chart if you are using an object storage backend.

As a result of this major change, upgrades from the charts this replaces might be difficult. We are attempting to support the 3 most common upgrade paths.

  1. Upgrade from `grafana/loki` using local `filesystem` storage
  1. Upgrade from `grafana/loki-simple-scalable` using a cloud based object storage such as S3 or GCS, or an api compatible equivilent like MinIO.

### Upgrading from `grafana/loki`

The default installation of `grafana/loki` is a single instance backed by `filesystem` storage that is not highly available. As a result, this upgrade method will involve downtime. The upgrade will involve deleting the previously deployed loki stateful set, the running the `helm upgrade` which will create the new one with the same name, which should attach to the existing PVC or ephemeral storage, thus preserving you data. Will still highly recommend backing up all data before conducting the upgrade.

To upgrade, you will need at least the following in your `values.yaml`:

```yaml
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
```

Currently, it is crashing on trying to run multiple replicas on a single node test cluster. So, I must update CI values to deploy only a single replica as proposed in the migration guide above.

**Comment by elcomtik** [comment]
@zanhsieh it is ready to be tested. One more  approval for the workflows, please.

**Comment by zanhsieh** [comment]
@elcomtik 
I think the above migration document shall be put into README.md, so the user shall know the scope of the upgrade operation.

**Comment by elcomtik** [comment]
Ok, I'll put it there ASAP

**Comment by elcomtik** [comment]
My suggestion is to set these values as default at values.yaml. This will retain backward compatibility with the previous chart versions. Users still can override this to be able to deploy scalable Loki deployment. I will also bump a minor version of this chart, to notify users about this change.

**Comment by elcomtik** [comment]
@zanhsieh I think it is ready to be tested. One more approval for the workflows, please.

**Comment by apt-x4869** [comment]
Any update on this PR? When will this be merged?

**Review by zanhsieh — CHANGES_REQUESTED** [review]
@elcomtik @apt-x4869 
There is some lint error, as well as some conflict on Chart.yaml.

**Comment by elcomtik** [comment]
There are more problems than lint issue only. Changes in loki helmchart v3.x were quite significant and not well documented. If you search for issues in loki repository you will find few opened on this topics. I'm working on incorporating necessary changes in this loki-stack PR. Unfortunately, I have very little spare time and progress is quite slow. Hopefully I'll finish it this week.

**Comment by joschne** [comment]
Any updates on this @elcomtik ? We'd really appreciate to use loki 2.7.0+ with loki-stack. Thank you for the information.

**Comment by elcomtik** [comment]
I have working code, just need some time to update readme and push.

**Comment by apt-x4869** [comment]
@elcomtik Any updates?

**Comment by elcomtik** [comment]
Soon, sorry for delay.

**Comment by Totalus** [comment]
I'd also like to see that one merged soon if possible.

**Comment by mickours** [comment]
It seems that the failing test might be due to a lack of resources.
https://github.com/grafana/helm-charts/actions/runs/4624738451/jobs/8179848813?pr=2055#step:9:7600

Is there anything I can do to help this PR?

**Comment by zanhsieh** [comment]
> It seems that the failing test might be due to a lack of resources. https://github.com/grafana/helm-charts/actions/runs/4624738451/jobs/8179848813?pr=2055#step:9:7600
> 
> Is there anything I can do to help this PR?

@mickours So how?

**Comment by Bernix01** [comment]
any update on this?

**Comment by robdatasembly** [comment]
> any update on this?

Also looking for an update, getting blocked on GCP Kubernetes Engine, clusters can't automatically upgrade to Kubernetes 1.25, but will forcibly upgrade after GKE's Kubernetes 1.24 EOL on October 31, 2023

**Comment by robdatasembly** [comment]
> > any update on this?
> 
> Also looking for an update, getting blocked on GCP Kubernetes Engine, clusters can't automatically upgrade to Kubernetes 1.25, but will forcibly upgrade after GKE's Kubernetes 1.24 EOL on October 31, 2023

Workaround here https://github.com/grafana/loki/issues/7431

**Comment by elcomtik** [comment]
I had no spare time for this, however I should be able to complete it until the end of this week.

**Comment by feym78** [comment]
> I had no spare time for this, however I should be able to complete it until the end of this week.

Hi!
Any updates?
It would be great to update loki-stack chart to the up-to-date loki and promtail at least. Tried just to up chart versions in dependencies, but it didn't pass templating bcs some confclicts.

**Pull request closed without merging**
