### PR TITLE
[grafana] app version to 10.2.3

### PR DESCRIPTION
**Pull request by akselleirv**
Closes https://github.com/grafana/helm-charts/issues/2878

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Review by Xtigyro — APPROVED** [review]

**Comment by Xtigyro** [comment]
@akselleirv Please sign the DCO.

**Comment by davordbetter** [comment]
@Xtigyro would you be able to fix DCO (https://github.com/grafana/helm-charts/pull/2879/checks?check_run_id=20252902007)?

**Comment by Xtigyro** [comment]
@akselleirv Please resolve the conflicts.

**Comment by akselleirv** [comment]
@Xtigyro I resolved the conflicts!

**Comment by Xtigyro** [comment]
@akselleirv Seems I can't merge this because your branch is not up-to-date with our `main` branch.

**Comment by akselleirv** [comment]
@Xtigyro I updated the branch now!

**Pull request merged**
