### PR TITLE
[loki-stack] Update Grafana tag image to latest version

### PR DESCRIPTION
**Pull request by techieforfun**
From `7.5.0` to `8.1.5`

### CODE REVIEW

**Comment by zanhsieh** [comment]
@techieforfun 
Please sign DCO and bounce chart version to latest.

**Comment by techieforfun** [comment]
@zanhsieh by chart version if you meant Grafana, looks like it's already updated.

**Comment by joejulian** [comment]
With every change to a chart, the Chart.yaml must have a version bump, in this instance `charts/loki-stack/Charts.yaml` needs to be bumped to `2.4.2`.

**Comment by Gbps** [comment]
Unfortunately this example install command is broken until this is merged in:

https://grafana.com/docs/loki/latest/installation/helm/
### Deploy Loki Stack (Loki, Promtail, Grafana, Prometheus) with persistent volume claim
```
helm upgrade --install loki grafana/loki-stack  --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false,loki.persistence.enabled=true,loki.persistence.storageClassName=standard,loki.persistence.size=5Gi
```

This is due to removal of deprecated components from the older version of the install with `grafana.enabled=true`.

Error received:

```
Error: unable to build kubernetes objects from release manifest: [unable to recognize "": no matches for kind "ClusterRole" in version "rbac.authorization.k8s.io/v1beta1", unable to recognize "": no matches for kind "ClusterRoleBinding" in version "rbac.authorization.k8s.io/v1beta1"]
```

As per #671

**Pull request closed without merging**
