### PR TITLE
[grafana] Update Grafana to 11.1.0

### PR DESCRIPTION
**Pull request by sboulkour**
Update Grafana version.
From 11.0.0 to 11.1.0.

### CODE REVIEW

**Comment by jkroepke** [comment]
hi, please resolve MR conflicht

**Comment by sboulkour** [comment]
> hi, please resolve MR conflicht

Done :)

**Review by jkroepke — APPROVED** [review]
LGTM 👍

**Comment by derekperkins** [comment]
Very interested in this landing

**Review by zanhsieh — APPROVED** [review]

**Pull request merged**
