### PR TITLE
[tempo-distributed] Add capability to define additional ports on gateway service

### PR DESCRIPTION
**Pull request by eviscares**
This creates a way to use the gateway for more complex scenarios in combination with .Values.gateway.nginxConfig.httpSnippet.

### CODE REVIEW

**Comment by BitProcessor** [comment]
If this is a useful scenario, it would be great to have it documented a bit more?
```
    # -- Additional ports that might be required on the gateway service
     additionalPorts: {}
```
Is a bit vague imho.
"ports that might be required" is as saying:
"Here is a car, and here are some screws that might be required"
Euh, yeah, thanks I guess 🤷🏻‍♂️

**Comment by eviscares** [comment]
Hey, I updated the comment string a bit, but I am unsure on how to make it clearer, as it is a pretty flexible thing.

**Comment by mapno** [comment]
It needs updating the docs, please run helm-docs and commit changes!

**Comment by eviscares** [comment]
I'm trying. XD Should be good now

**Review by mapno — APPROVED** [review]
LGTM, thanks for the patience with the docs.

**Pull request merged**
