### PR TITLE
[promtail] Add automount option for service account and pod

### PR DESCRIPTION
**Pull request by emilkor1**
Azure recommended actions suggests disabling automount of API credentials.

### CODE REVIEW

**Review by zanhsieh — APPROVED** [review]

**Comment by emilkor1** [comment]
Duplicate PR: #2991

**Comment by jkroepke** [comment]
@emilkor1 my PR covers grafana only. Not promtail, this is PR is still valid.

**Comment by emilkor1** [comment]
Thanks for letting me know.. was too quick there

**Comment by emilkor1** [comment]
Can someone look at this? @unguiculus @Whyeasy

**Comment by a-hat** [comment]
For security hardening we also need this. Any reason why this does not get merged?

**Review by jkroepke — APPROVED** [review]
LGTM

**Comment by jkroepke** [comment]
@zanhsieh - I'm not an official promtail maintainer, I point this PR to you back. Feel to merge.

**Pull request merged**
